/*******************************************************************************
' WIPCaster.cs
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008/07/04 15:53:51
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
*******************************************************************************/

using System;
using com.miracom.transceiverx;
using com.miracom.transceiverx.session;
using com.miracom.transceiverx.message;
using com.miracom.transceiverx.message.former;

using Miracom.MsgHandler;

namespace Miracom.DNMCore
{
    public class TPDRCaster
    {
        private static string mRPTBASChannel;
        private static int RPTBASTTL;

        public static string RPTBASChannel
        {
            get
            {
                return mRPTBASChannel;
            }
            set
            {
                mRPTBASChannel = value;
            }
        }

        public static int WIPTTL
        {
            get
            {
                return RPTBASTTL;
            }
            set
            {
                RPTBASTTL = value;
            }
        }

        public static bool RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out)
        {
            return RPT_SQL_Query_DataTable_Result(Sql_In, ref Sql_Out, "", 0, DeliveryMode.RReply);
        }
        public static bool RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel)
        {
            return RPT_SQL_Query_DataTable_Result(Sql_In, ref Sql_Out, channel, 0, DeliveryMode.RReply);
        }
        //타임아웃 10배 증가 함수 20110525 BGL
        public static bool Long_RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel)
        {
            return RPT_SQL_Query_DataTable_Result(Sql_In, ref Sql_Out, channel, 0, DeliveryMode.RReply);
        }
        public static bool RPT_SQL_Query_DataTable_Result(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel, int ttl, DeliveryMode mode)
        {
            try
            {
                if (null == channel || channel.Trim().Equals(""))
                {
                    if (null == RPTBASChannel || RPTBASChannel.Trim().Equals(""))
                        throw new TrxException(TrxException.INVALID_CHANNEL);
                    channel = RPTBASChannel;
                }
                if (channel.IndexOf("QMS") >= 0 || channel.IndexOf("RPTM") >= 0 || channel.IndexOf("RPT1") >= 0) //channel.IndexOf("QMM") > -1
                {
                    //타임아웃 설정( 설정 값은 밀리세컨드임 )
                    ttl = 180000;
                }
                else
                {
                    ttl = ttl <= 0 ? RPTBASTTL : ttl;
                }
                //ttl = ttl <= 0 ? RPTBASTTL : ttl;
                Message msg = MPMH.Instance.createMessage();
                msg.putProperty(MessageConst.XGEN_TAG_VERSION, MessageConst.XGEN_VERSION);
                msg.putProperty(MessageConst.XGEN_TAG_MODULE, "RPTBAS");
                msg.putProperty(MessageConst.XGEN_TAG_INTERFACE, "RPTBAS");
                msg.putProperty(MessageConst.XGEN_TAG_OPERATION, "RPT_SQL_Query_DataTable_Result");
                StreamTransformer former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_RPT_SQL_Query_In_Tag(former, Sql_In);
                msg.putData(former.getBytes());
                Message rep = null;
                MPMH.Instance.sendMessage(msg, ref rep, channel, ttl, (short)mode);
                if (DeliveryMode.RReply == mode) /* Just RequestReply */
                {
                    if (null == rep)
                        throw new TrxException(TrxException.INVALID_MESSAGE);
                    former = new StreamTransformerImpl((byte[])rep.getData());
                    RPTBASType.transform_RPT_SQL_Query_DataTable_Result_Out_Tag(former, ref Sql_Out);
                }
                return true;
            }
            catch (Exception e)
            {
                MPMH.StatusMessage = e.Message;
                return false;
            }
        }
        public static bool RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out)
        {
            return RPT_View_Dynamic(Sql_In, ref Sql_Out, "", 0, DeliveryMode.RReply);
        }
        public static bool RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel)
        {
            return RPT_View_Dynamic(Sql_In, ref Sql_Out, channel, 0, DeliveryMode.RReply);
        }
        //타임아웃 10배 증가 함수 20110525 BGL
        public static bool Long_RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel)
        {
            return RPT_View_Dynamic(Sql_In, ref Sql_Out, channel, 0, DeliveryMode.RReply);
        }
        public static bool RPT_View_Dynamic(RPT_SQL_Query_In_Tag Sql_In, ref RPT_SQL_Query_DataTable_Result_Out_Tag Sql_Out, string channel, int ttl, DeliveryMode mode)
        {
            try
            {
                if (null == channel || channel.Trim().Equals(""))
                {
                    if (null == RPTBASChannel || RPTBASChannel.Trim().Equals(""))
                        throw new TrxException(TrxException.INVALID_CHANNEL);
                    channel = RPTBASChannel;
                }
                if (channel.IndexOf("QMS") >= 0 || channel.IndexOf("RPTM") >= 0 || channel.IndexOf("RPT1") >= 0) //channel.IndexOf("QMM") > -1
                {
                    //타임아웃 설정( 설정 값은 밀리세컨드임 )
                    ttl = 180000;
                }
                else
                {
                    ttl = ttl <= 0 ? RPTBASTTL : ttl;
                }
                //ttl = ttl <= 0 ? RPTBASTTL : ttl;
                Message msg = MPMH.Instance.createMessage();
                msg.putProperty(MessageConst.XGEN_TAG_VERSION, MessageConst.XGEN_VERSION);
                msg.putProperty(MessageConst.XGEN_TAG_MODULE, "RPTBAS");
                msg.putProperty(MessageConst.XGEN_TAG_INTERFACE, "RPTBAS");
                msg.putProperty(MessageConst.XGEN_TAG_OPERATION, "RPT_View_Dynamic");
                StreamTransformer former = new StreamTransformerImpl("utf-8");
                RPTBASType.serialize_RPT_SQL_Query_In_Tag(former, Sql_In);
                msg.putData(former.getBytes());
                Message rep = null;
                MPMH.Instance.sendMessage(msg, ref rep, channel, ttl, (short)mode);
                if (DeliveryMode.RReply == mode) /* Just RequestReply */
                {
                    if (null == rep)
                        throw new TrxException(TrxException.INVALID_MESSAGE);
                    former = new StreamTransformerImpl((byte[])rep.getData());
                    RPTBASType.transform_RPT_SQL_Query_DataTable_Result_Out_Tag(former, ref Sql_Out);
                }
                return true;
            }
            catch (Exception e)
            {
                MPMH.StatusMessage = e.Message;
                return false;
            }
        }
    }
}