namespace SOI.Samples.SampleControls
{
    partial class frmSampleGrid
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance26 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance27 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn3 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("seq", 0);
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn4 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn5 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 2);
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance14 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance16 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance15 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand2 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn9 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("chk", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn10 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn11 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 2);
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand3 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn12 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn13 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn14 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 2);
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance98 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance99 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance30 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand4 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("", 1);
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance100 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance28 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance29 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook4 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance101 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand5 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn15 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("code", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn16 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("desc", 1);
            Infragistics.Win.Appearance appearance80 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance102 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook5 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance103 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance31 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance32 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance33 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand6 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn6 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("chk", 0);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn7 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("code", 1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn17 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("desc", 2);
            Infragistics.Win.Appearance appearance34 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance35 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance36 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance37 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance38 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance39 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance40 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook6 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance97 = new Infragistics.Win.Appearance();
            this.soiGroupBox4 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid4 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            this.soiGroupBox3 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid3 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            this.soiGroupBox2 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid2 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            this.soiGroupBox1 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid1 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            this.soiGroupBox5 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid5 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            this.soiGroupBox6 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiGrid6 = new SOI.OIFrx.SOIControls.SOIGrid(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox4)).BeginInit();
            this.soiGroupBox4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox3)).BeginInit();
            this.soiGroupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox2)).BeginInit();
            this.soiGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).BeginInit();
            this.soiGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox5)).BeginInit();
            this.soiGroupBox5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox6)).BeginInit();
            this.soiGroupBox6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid6)).BeginInit();
            this.SuspendLayout();
            // 
            // soiGroupBox4
            // 
            this.soiGroupBox4._UseOITheme = false;
            this.soiGroupBox4._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance25.BackColor = System.Drawing.Color.Black;
            appearance25.BackColor2 = System.Drawing.Color.Black;
            appearance25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance25.BorderColor2 = System.Drawing.Color.Black;
            appearance25.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox4.Appearance = appearance25;
            this.soiGroupBox4.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance26.BackColor = System.Drawing.Color.Black;
            appearance26.BackColor2 = System.Drawing.Color.Black;
            appearance26.BorderColor = System.Drawing.Color.Black;
            appearance26.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox4.ContentAreaAppearance = appearance26;
            this.soiGroupBox4.Controls.Add(this.soiGrid4);
            appearance27.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance27.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance27.BorderColor = System.Drawing.Color.Black;
            appearance27.BorderColor2 = System.Drawing.Color.Black;
            appearance27.FontData.BoldAsString = "True";
            appearance27.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox4.HeaderAppearance = appearance27;
            this.soiGroupBox4.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox4.Location = new System.Drawing.Point(550, 238);
            this.soiGroupBox4.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox4.Name = "soiGroupBox4";
            this.soiGroupBox4.Size = new System.Drawing.Size(519, 214);
            this.soiGroupBox4.TabIndex = 7;
            this.soiGroupBox4.Text = "Sequence / Text";
            this.soiGroupBox4.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid4
            // 
            this.soiGrid4._UseOITheme = true;
            appearance5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid4.DisplayLayout.Appearance = appearance5;
            this.soiGrid4.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            appearance61.TextHAlignAsString = "Center";
            appearance61.TextVAlignAsString = "Middle";
            ultraGridColumn3.CellAppearance = appearance61;
            ultraGridColumn3.DataType = typeof(int);
            ultraGridColumn3.Header.Caption = "";
            ultraGridColumn3.Header.VisiblePosition = 0;
            ultraGridColumn3.Width = 50;
            ultraGridColumn4.Header.Caption = "Column 2";
            ultraGridColumn4.Header.VisiblePosition = 1;
            ultraGridColumn4.Width = 97;
            ultraGridColumn5.Header.Caption = "Column 3";
            ultraGridColumn5.Header.VisiblePosition = 2;
            ultraGridColumn5.Width = 118;
            ultraGridBand1.Columns.AddRange(new object[] {
            ultraGridColumn3,
            ultraGridColumn4,
            ultraGridColumn5});
            this.soiGrid4.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.soiGrid4.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid4.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid4.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid4.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance6.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance6.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance6.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance6.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid4.DisplayLayout.GroupByBox.Appearance = appearance6;
            appearance8.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid4.DisplayLayout.GroupByBox.BandLabelAppearance = appearance8;
            this.soiGrid4.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid4.DisplayLayout.GroupByBox.Hidden = true;
            appearance7.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance7.BackColor2 = System.Drawing.SystemColors.Control;
            appearance7.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance7.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid4.DisplayLayout.GroupByBox.PromptAppearance = appearance7;
            this.soiGrid4.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid4.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid4.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid4.DisplayLayout.Override.ActiveCellAppearance = appearance11;
            appearance14.BackColor = System.Drawing.SystemColors.Highlight;
            appearance14.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid4.DisplayLayout.Override.ActiveRowAppearance = appearance14;
            this.soiGrid4.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid4.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid4.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid4.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance16.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid4.DisplayLayout.Override.CardAreaAppearance = appearance16;
            appearance12.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance12.FontData.BoldAsString = "True";
            appearance12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance12.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance12.TextVAlignAsString = "Middle";
            this.soiGrid4.DisplayLayout.Override.CellAppearance = appearance12;
            this.soiGrid4.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid4.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid4.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance10.BackColor = System.Drawing.SystemColors.Control;
            appearance10.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance10.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance10.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance10.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid4.DisplayLayout.Override.GroupByRowAppearance = appearance10;
            appearance9.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance9.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance9.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance9.FontData.BoldAsString = "True";
            appearance9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance9.TextHAlignAsString = "Center";
            this.soiGrid4.DisplayLayout.Override.HeaderAppearance = appearance9;
            this.soiGrid4.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid4.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance94.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid4.DisplayLayout.Override.HotTrackRowCellAppearance = appearance94;
            appearance15.BackColor = System.Drawing.SystemColors.Window;
            appearance15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid4.DisplayLayout.Override.RowAppearance = appearance15;
            this.soiGrid4.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid4.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance13.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid4.DisplayLayout.Override.TemplateAddRowAppearance = appearance13;
            appearance95.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook1.ThumbAppearance = appearance95;
            this.soiGrid4.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.soiGrid4.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid4.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid4.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid4.Location = new System.Drawing.Point(2, 28);
            this.soiGrid4.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid4.Name = "soiGrid4";
            this.soiGrid4.Size = new System.Drawing.Size(515, 184);
            this.soiGrid4.TabIndex = 0;
            this.soiGrid4.Text = "soiGrid4";
            this.soiGrid4.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid4.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid4.UseSOIContextMenu = true;
            // 
            // soiGroupBox3
            // 
            this.soiGroupBox3._UseOITheme = false;
            this.soiGroupBox3._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance46.BackColor = System.Drawing.Color.Black;
            appearance46.BackColor2 = System.Drawing.Color.Black;
            appearance46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance46.BorderColor2 = System.Drawing.Color.Black;
            appearance46.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox3.Appearance = appearance46;
            this.soiGroupBox3.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance47.BackColor = System.Drawing.Color.Black;
            appearance47.BackColor2 = System.Drawing.Color.Black;
            appearance47.BorderColor = System.Drawing.Color.Black;
            appearance47.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox3.ContentAreaAppearance = appearance47;
            this.soiGroupBox3.Controls.Add(this.soiGrid3);
            appearance60.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance60.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance60.BorderColor = System.Drawing.Color.Black;
            appearance60.BorderColor2 = System.Drawing.Color.Black;
            appearance60.FontData.BoldAsString = "True";
            appearance60.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox3.HeaderAppearance = appearance60;
            this.soiGroupBox3.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox3.Location = new System.Drawing.Point(550, 14);
            this.soiGroupBox3.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox3.Name = "soiGroupBox3";
            this.soiGroupBox3.Size = new System.Drawing.Size(519, 214);
            this.soiGroupBox3.TabIndex = 6;
            this.soiGroupBox3.Text = "Check Box / Text";
            this.soiGroupBox3.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid3
            // 
            this.soiGrid3._UseOITheme = true;
            appearance48.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance48.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid3.DisplayLayout.Appearance = appearance48;
            this.soiGrid3.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn9.DataType = typeof(bool);
            ultraGridColumn9.Header.Caption = "";
            ultraGridColumn9.Header.VisiblePosition = 0;
            ultraGridColumn9.Width = 50;
            ultraGridColumn10.Header.Caption = "Column 2";
            ultraGridColumn10.Header.VisiblePosition = 1;
            ultraGridColumn10.Width = 97;
            ultraGridColumn11.Header.Caption = "Column 3";
            ultraGridColumn11.Header.VisiblePosition = 2;
            ultraGridColumn11.Width = 118;
            ultraGridBand2.Columns.AddRange(new object[] {
            ultraGridColumn9,
            ultraGridColumn10,
            ultraGridColumn11});
            this.soiGrid3.DisplayLayout.BandsSerializer.Add(ultraGridBand2);
            this.soiGrid3.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid3.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid3.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid3.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance49.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance49.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance49.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance49.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid3.DisplayLayout.GroupByBox.Appearance = appearance49;
            appearance50.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid3.DisplayLayout.GroupByBox.BandLabelAppearance = appearance50;
            this.soiGrid3.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid3.DisplayLayout.GroupByBox.Hidden = true;
            appearance51.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance51.BackColor2 = System.Drawing.SystemColors.Control;
            appearance51.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance51.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid3.DisplayLayout.GroupByBox.PromptAppearance = appearance51;
            this.soiGrid3.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid3.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid3.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance52.BackColor = System.Drawing.SystemColors.Window;
            appearance52.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid3.DisplayLayout.Override.ActiveCellAppearance = appearance52;
            appearance53.BackColor = System.Drawing.SystemColors.Highlight;
            appearance53.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid3.DisplayLayout.Override.ActiveRowAppearance = appearance53;
            this.soiGrid3.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid3.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid3.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid3.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance54.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid3.DisplayLayout.Override.CardAreaAppearance = appearance54;
            appearance55.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance55.FontData.BoldAsString = "True";
            appearance55.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance55.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance55.TextVAlignAsString = "Middle";
            this.soiGrid3.DisplayLayout.Override.CellAppearance = appearance55;
            this.soiGrid3.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid3.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid3.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance56.BackColor = System.Drawing.SystemColors.Control;
            appearance56.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance56.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance56.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance56.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid3.DisplayLayout.Override.GroupByRowAppearance = appearance56;
            appearance57.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance57.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance57.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance57.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance57.FontData.BoldAsString = "True";
            appearance57.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance57.TextHAlignAsString = "Center";
            this.soiGrid3.DisplayLayout.Override.HeaderAppearance = appearance57;
            this.soiGrid3.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid3.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance92.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid3.DisplayLayout.Override.HotTrackRowCellAppearance = appearance92;
            appearance58.BackColor = System.Drawing.SystemColors.Window;
            appearance58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid3.DisplayLayout.Override.RowAppearance = appearance58;
            this.soiGrid3.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid3.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance59.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid3.DisplayLayout.Override.TemplateAddRowAppearance = appearance59;
            appearance93.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook2.ThumbAppearance = appearance93;
            this.soiGrid3.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.soiGrid3.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid3.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid3.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid3.Location = new System.Drawing.Point(2, 28);
            this.soiGrid3.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid3.Name = "soiGrid3";
            this.soiGrid3.Size = new System.Drawing.Size(515, 184);
            this.soiGrid3.TabIndex = 0;
            this.soiGrid3.Text = "soiGrid3";
            this.soiGrid3.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid3.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid3.UseSOIContextMenu = true;
            // 
            // soiGroupBox2
            // 
            this.soiGroupBox2._UseOITheme = false;
            this.soiGroupBox2._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance62.BackColor = System.Drawing.Color.Black;
            appearance62.BackColor2 = System.Drawing.Color.Black;
            appearance62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance62.BorderColor2 = System.Drawing.Color.Black;
            appearance62.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox2.Appearance = appearance62;
            this.soiGroupBox2.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance63.BackColor = System.Drawing.Color.Black;
            appearance63.BackColor2 = System.Drawing.Color.Black;
            appearance63.BorderColor = System.Drawing.Color.Black;
            appearance63.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox2.ContentAreaAppearance = appearance63;
            this.soiGroupBox2.Controls.Add(this.soiGrid2);
            appearance76.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance76.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance76.BorderColor = System.Drawing.Color.Black;
            appearance76.BorderColor2 = System.Drawing.Color.Black;
            appearance76.FontData.BoldAsString = "True";
            appearance76.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox2.HeaderAppearance = appearance76;
            this.soiGroupBox2.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox2.Location = new System.Drawing.Point(14, 238);
            this.soiGroupBox2.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox2.Name = "soiGroupBox2";
            this.soiGroupBox2.Size = new System.Drawing.Size(519, 214);
            this.soiGroupBox2.TabIndex = 5;
            this.soiGroupBox2.Text = "Auto Fit Last Column";
            this.soiGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid2
            // 
            this.soiGrid2._UseOITheme = true;
            appearance64.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance64.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid2.DisplayLayout.Appearance = appearance64;
            this.soiGrid2.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn12.Header.Caption = "Column 1";
            ultraGridColumn12.Header.VisiblePosition = 0;
            ultraGridColumn12.Width = 298;
            ultraGridColumn13.Header.Caption = "Column 2";
            ultraGridColumn13.Header.VisiblePosition = 1;
            ultraGridColumn13.Width = 97;
            ultraGridColumn14.Header.Caption = "Column 3";
            ultraGridColumn14.Header.VisiblePosition = 2;
            ultraGridColumn14.Width = 118;
            ultraGridBand3.Columns.AddRange(new object[] {
            ultraGridColumn12,
            ultraGridColumn13,
            ultraGridColumn14});
            this.soiGrid2.DisplayLayout.BandsSerializer.Add(ultraGridBand3);
            this.soiGrid2.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid2.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid2.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid2.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance65.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance65.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance65.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance65.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid2.DisplayLayout.GroupByBox.Appearance = appearance65;
            appearance66.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid2.DisplayLayout.GroupByBox.BandLabelAppearance = appearance66;
            this.soiGrid2.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid2.DisplayLayout.GroupByBox.Hidden = true;
            appearance67.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance67.BackColor2 = System.Drawing.SystemColors.Control;
            appearance67.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance67.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid2.DisplayLayout.GroupByBox.PromptAppearance = appearance67;
            this.soiGrid2.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid2.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid2.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance68.BackColor = System.Drawing.SystemColors.Window;
            appearance68.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid2.DisplayLayout.Override.ActiveCellAppearance = appearance68;
            appearance69.BackColor = System.Drawing.SystemColors.Highlight;
            appearance69.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid2.DisplayLayout.Override.ActiveRowAppearance = appearance69;
            this.soiGrid2.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid2.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid2.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid2.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance70.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid2.DisplayLayout.Override.CardAreaAppearance = appearance70;
            appearance71.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance71.FontData.BoldAsString = "True";
            appearance71.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance71.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance71.TextVAlignAsString = "Middle";
            this.soiGrid2.DisplayLayout.Override.CellAppearance = appearance71;
            this.soiGrid2.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid2.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid2.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance72.BackColor = System.Drawing.SystemColors.Control;
            appearance72.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance72.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance72.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance72.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid2.DisplayLayout.Override.GroupByRowAppearance = appearance72;
            appearance73.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance73.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance73.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance73.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance73.FontData.BoldAsString = "True";
            appearance73.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance73.TextHAlignAsString = "Center";
            this.soiGrid2.DisplayLayout.Override.HeaderAppearance = appearance73;
            this.soiGrid2.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid2.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance98.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid2.DisplayLayout.Override.HotTrackRowCellAppearance = appearance98;
            appearance74.BackColor = System.Drawing.SystemColors.Window;
            appearance74.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid2.DisplayLayout.Override.RowAppearance = appearance74;
            this.soiGrid2.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid2.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance75.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid2.DisplayLayout.Override.TemplateAddRowAppearance = appearance75;
            appearance99.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook3.ThumbAppearance = appearance99;
            this.soiGrid2.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.soiGrid2.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid2.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid2.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid2.Location = new System.Drawing.Point(2, 28);
            this.soiGrid2.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid2.Name = "soiGrid2";
            this.soiGrid2.Size = new System.Drawing.Size(515, 184);
            this.soiGrid2.TabIndex = 0;
            this.soiGrid2.Text = "soiGrid2";
            this.soiGrid2.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid2.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid2.UseSOIContextMenu = true;
            // 
            // soiGroupBox1
            // 
            this.soiGroupBox1._UseOITheme = false;
            this.soiGroupBox1._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance1.BackColor = System.Drawing.Color.Black;
            appearance1.BackColor2 = System.Drawing.Color.Black;
            appearance1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance1.BorderColor2 = System.Drawing.Color.Black;
            appearance1.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox1.Appearance = appearance1;
            this.soiGroupBox1.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance2.BackColor = System.Drawing.Color.Black;
            appearance2.BackColor2 = System.Drawing.Color.Black;
            appearance2.BorderColor = System.Drawing.Color.Black;
            appearance2.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox1.ContentAreaAppearance = appearance2;
            this.soiGroupBox1.Controls.Add(this.soiGrid1);
            appearance30.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance30.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance30.BorderColor = System.Drawing.Color.Black;
            appearance30.BorderColor2 = System.Drawing.Color.Black;
            appearance30.FontData.BoldAsString = "True";
            appearance30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox1.HeaderAppearance = appearance30;
            this.soiGroupBox1.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox1.Location = new System.Drawing.Point(14, 14);
            this.soiGroupBox1.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox1.Name = "soiGroupBox1";
            this.soiGroupBox1.Size = new System.Drawing.Size(361, 214);
            this.soiGroupBox1.TabIndex = 4;
            this.soiGroupBox1.Text = "No Fit";
            this.soiGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid1
            // 
            this.soiGrid1._UseOITheme = true;
            appearance3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid1.DisplayLayout.Appearance = appearance3;
            ultraGridColumn1.Header.Caption = "Column 1";
            ultraGridColumn1.Header.VisiblePosition = 0;
            ultraGridColumn2.Header.Caption = "Column 2";
            ultraGridColumn2.Header.VisiblePosition = 1;
            ultraGridBand4.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2});
            this.soiGrid1.DisplayLayout.BandsSerializer.Add(ultraGridBand4);
            this.soiGrid1.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid1.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid1.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid1.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance4.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance4.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance4.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid1.DisplayLayout.GroupByBox.Appearance = appearance4;
            appearance17.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid1.DisplayLayout.GroupByBox.BandLabelAppearance = appearance17;
            this.soiGrid1.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid1.DisplayLayout.GroupByBox.Hidden = true;
            appearance18.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance18.BackColor2 = System.Drawing.SystemColors.Control;
            appearance18.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance18.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid1.DisplayLayout.GroupByBox.PromptAppearance = appearance18;
            this.soiGrid1.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid1.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid1.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance19.BackColor = System.Drawing.SystemColors.Window;
            appearance19.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid1.DisplayLayout.Override.ActiveCellAppearance = appearance19;
            appearance20.BackColor = System.Drawing.SystemColors.Highlight;
            appearance20.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid1.DisplayLayout.Override.ActiveRowAppearance = appearance20;
            this.soiGrid1.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid1.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid1.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid1.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance21.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid1.DisplayLayout.Override.CardAreaAppearance = appearance21;
            appearance22.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance22.FontData.BoldAsString = "True";
            appearance22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance22.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance22.TextVAlignAsString = "Middle";
            this.soiGrid1.DisplayLayout.Override.CellAppearance = appearance22;
            this.soiGrid1.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid1.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid1.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance23.BackColor = System.Drawing.SystemColors.Control;
            appearance23.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance23.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance23.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance23.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid1.DisplayLayout.Override.GroupByRowAppearance = appearance23;
            appearance24.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance24.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance24.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance24.FontData.BoldAsString = "True";
            appearance24.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance24.TextHAlignAsString = "Center";
            this.soiGrid1.DisplayLayout.Override.HeaderAppearance = appearance24;
            this.soiGrid1.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid1.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance100.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid1.DisplayLayout.Override.HotTrackRowCellAppearance = appearance100;
            appearance28.BackColor = System.Drawing.SystemColors.Window;
            appearance28.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid1.DisplayLayout.Override.RowAppearance = appearance28;
            this.soiGrid1.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid1.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance29.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid1.DisplayLayout.Override.TemplateAddRowAppearance = appearance29;
            appearance101.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook4.ThumbAppearance = appearance101;
            this.soiGrid1.DisplayLayout.ScrollBarLook = scrollBarLook4;
            this.soiGrid1.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid1.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid1.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid1.Location = new System.Drawing.Point(2, 28);
            this.soiGrid1.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid1.Name = "soiGrid1";
            this.soiGrid1.Size = new System.Drawing.Size(357, 184);
            this.soiGrid1.TabIndex = 0;
            this.soiGrid1.Text = "soiGrid1";
            this.soiGrid1.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid1.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid1.UseSOIContextMenu = true;
            // 
            // soiGroupBox5
            // 
            this.soiGroupBox5._UseOITheme = false;
            this.soiGroupBox5._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance77.BackColor = System.Drawing.Color.Black;
            appearance77.BackColor2 = System.Drawing.Color.Black;
            appearance77.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance77.BorderColor2 = System.Drawing.Color.Black;
            appearance77.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox5.Appearance = appearance77;
            this.soiGroupBox5.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance78.BackColor = System.Drawing.Color.Black;
            appearance78.BackColor2 = System.Drawing.Color.Black;
            appearance78.BorderColor = System.Drawing.Color.Black;
            appearance78.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox5.ContentAreaAppearance = appearance78;
            this.soiGroupBox5.Controls.Add(this.soiGrid5);
            appearance91.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance91.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance91.BorderColor = System.Drawing.Color.Black;
            appearance91.BorderColor2 = System.Drawing.Color.Black;
            appearance91.FontData.BoldAsString = "True";
            appearance91.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox5.HeaderAppearance = appearance91;
            this.soiGroupBox5.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox5.Location = new System.Drawing.Point(1079, 12);
            this.soiGroupBox5.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox5.Name = "soiGroupBox5";
            this.soiGroupBox5.Size = new System.Drawing.Size(519, 214);
            this.soiGroupBox5.TabIndex = 8;
            this.soiGroupBox5.Text = "Code / Description";
            this.soiGroupBox5.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid5
            // 
            this.soiGrid5._UseOITheme = true;
            appearance79.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance79.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid5.DisplayLayout.Appearance = appearance79;
            this.soiGrid5.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn15.Header.Caption = "Code";
            ultraGridColumn15.Header.VisiblePosition = 0;
            ultraGridColumn15.Width = 120;
            ultraGridColumn16.Header.Caption = "Description";
            ultraGridColumn16.Header.VisiblePosition = 1;
            ultraGridColumn16.Width = 97;
            ultraGridBand5.Columns.AddRange(new object[] {
            ultraGridColumn15,
            ultraGridColumn16});
            this.soiGrid5.DisplayLayout.BandsSerializer.Add(ultraGridBand5);
            this.soiGrid5.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid5.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid5.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid5.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance80.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance80.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance80.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance80.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid5.DisplayLayout.GroupByBox.Appearance = appearance80;
            appearance81.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid5.DisplayLayout.GroupByBox.BandLabelAppearance = appearance81;
            this.soiGrid5.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid5.DisplayLayout.GroupByBox.Hidden = true;
            appearance82.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance82.BackColor2 = System.Drawing.SystemColors.Control;
            appearance82.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance82.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid5.DisplayLayout.GroupByBox.PromptAppearance = appearance82;
            this.soiGrid5.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid5.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid5.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance83.BackColor = System.Drawing.SystemColors.Window;
            appearance83.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid5.DisplayLayout.Override.ActiveCellAppearance = appearance83;
            appearance84.BackColor = System.Drawing.SystemColors.Highlight;
            appearance84.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid5.DisplayLayout.Override.ActiveRowAppearance = appearance84;
            this.soiGrid5.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid5.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid5.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid5.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance85.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid5.DisplayLayout.Override.CardAreaAppearance = appearance85;
            appearance86.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance86.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance86.FontData.BoldAsString = "True";
            appearance86.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance86.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance86.TextVAlignAsString = "Middle";
            this.soiGrid5.DisplayLayout.Override.CellAppearance = appearance86;
            this.soiGrid5.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid5.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid5.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance87.BackColor = System.Drawing.SystemColors.Control;
            appearance87.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance87.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance87.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance87.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid5.DisplayLayout.Override.GroupByRowAppearance = appearance87;
            appearance88.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance88.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance88.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance88.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance88.FontData.BoldAsString = "True";
            appearance88.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance88.TextHAlignAsString = "Center";
            this.soiGrid5.DisplayLayout.Override.HeaderAppearance = appearance88;
            this.soiGrid5.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid5.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance102.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid5.DisplayLayout.Override.HotTrackRowCellAppearance = appearance102;
            appearance89.BackColor = System.Drawing.SystemColors.Window;
            appearance89.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid5.DisplayLayout.Override.RowAppearance = appearance89;
            this.soiGrid5.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid5.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance90.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid5.DisplayLayout.Override.TemplateAddRowAppearance = appearance90;
            appearance103.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook5.ThumbAppearance = appearance103;
            this.soiGrid5.DisplayLayout.ScrollBarLook = scrollBarLook5;
            this.soiGrid5.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid5.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid5.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid5.Location = new System.Drawing.Point(2, 28);
            this.soiGrid5.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid5.Name = "soiGrid5";
            this.soiGrid5.Size = new System.Drawing.Size(515, 184);
            this.soiGrid5.TabIndex = 0;
            this.soiGrid5.Text = "soiGrid5";
            this.soiGrid5.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid5.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid5.UseSOIContextMenu = true;
            // 
            // soiGroupBox6
            // 
            this.soiGroupBox6._UseOITheme = false;
            this.soiGroupBox6._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance31.BackColor = System.Drawing.Color.Black;
            appearance31.BackColor2 = System.Drawing.Color.Black;
            appearance31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance31.BorderColor2 = System.Drawing.Color.Black;
            appearance31.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox6.Appearance = appearance31;
            this.soiGroupBox6.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance32.BackColor = System.Drawing.Color.Black;
            appearance32.BackColor2 = System.Drawing.Color.Black;
            appearance32.BorderColor = System.Drawing.Color.Black;
            appearance32.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox6.ContentAreaAppearance = appearance32;
            this.soiGroupBox6.Controls.Add(this.soiGrid6);
            appearance45.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance45.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance45.BorderColor = System.Drawing.Color.Black;
            appearance45.BorderColor2 = System.Drawing.Color.Black;
            appearance45.FontData.BoldAsString = "True";
            appearance45.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox6.HeaderAppearance = appearance45;
            this.soiGroupBox6.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox6.Location = new System.Drawing.Point(1079, 236);
            this.soiGroupBox6.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox6.Name = "soiGroupBox6";
            this.soiGroupBox6.Size = new System.Drawing.Size(519, 214);
            this.soiGroupBox6.TabIndex = 9;
            this.soiGroupBox6.Text = "CheckBox / Code / Description";
            this.soiGroupBox6.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiGrid6
            // 
            this.soiGrid6._UseOITheme = true;
            appearance33.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid6.DisplayLayout.Appearance = appearance33;
            this.soiGrid6.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridColumn6.DataType = typeof(bool);
            ultraGridColumn6.Header.Caption = "";
            ultraGridColumn6.Header.VisiblePosition = 0;
            ultraGridColumn6.Width = 50;
            ultraGridColumn7.Header.Caption = "Code";
            ultraGridColumn7.Header.VisiblePosition = 1;
            ultraGridColumn7.Width = 97;
            ultraGridColumn17.Header.Caption = "Description";
            ultraGridColumn17.Header.VisiblePosition = 2;
            ultraGridBand6.Columns.AddRange(new object[] {
            ultraGridColumn6,
            ultraGridColumn7,
            ultraGridColumn17});
            this.soiGrid6.DisplayLayout.BandsSerializer.Add(ultraGridBand6);
            this.soiGrid6.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid6.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid6.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(217)))), ((int)(((byte)(231)))));
            this.soiGrid6.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance34.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance34.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance34.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance34.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid6.DisplayLayout.GroupByBox.Appearance = appearance34;
            appearance35.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid6.DisplayLayout.GroupByBox.BandLabelAppearance = appearance35;
            this.soiGrid6.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid6.DisplayLayout.GroupByBox.Hidden = true;
            appearance36.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance36.BackColor2 = System.Drawing.SystemColors.Control;
            appearance36.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance36.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiGrid6.DisplayLayout.GroupByBox.PromptAppearance = appearance36;
            this.soiGrid6.DisplayLayout.MaxColScrollRegions = 1;
            this.soiGrid6.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiGrid6.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance37.BackColor = System.Drawing.SystemColors.Window;
            appearance37.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiGrid6.DisplayLayout.Override.ActiveCellAppearance = appearance37;
            appearance38.BackColor = System.Drawing.SystemColors.Highlight;
            appearance38.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiGrid6.DisplayLayout.Override.ActiveRowAppearance = appearance38;
            this.soiGrid6.DisplayLayout.Override.AllowColMoving = Infragistics.Win.UltraWinGrid.AllowColMoving.NotAllowed;
            this.soiGrid6.DisplayLayout.Override.AllowMultiCellOperations = Infragistics.Win.UltraWinGrid.AllowMultiCellOperation.Copy;
            this.soiGrid6.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiGrid6.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.Solid;
            appearance39.BackColor = System.Drawing.SystemColors.Window;
            this.soiGrid6.DisplayLayout.Override.CardAreaAppearance = appearance39;
            appearance40.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            appearance40.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance40.FontData.BoldAsString = "True";
            appearance40.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            appearance40.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            appearance40.TextVAlignAsString = "Middle";
            this.soiGrid6.DisplayLayout.Override.CellAppearance = appearance40;
            this.soiGrid6.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiGrid6.DisplayLayout.Override.CellPadding = 0;
            this.soiGrid6.DisplayLayout.Override.DefaultRowHeight = 40;
            appearance41.BackColor = System.Drawing.SystemColors.Control;
            appearance41.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance41.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance41.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance41.BorderColor = System.Drawing.SystemColors.Window;
            this.soiGrid6.DisplayLayout.Override.GroupByRowAppearance = appearance41;
            appearance42.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance42.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            appearance42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance42.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            appearance42.FontData.BoldAsString = "True";
            appearance42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance42.TextHAlignAsString = "Center";
            this.soiGrid6.DisplayLayout.Override.HeaderAppearance = appearance42;
            this.soiGrid6.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.SortMulti;
            this.soiGrid6.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance96.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiGrid6.DisplayLayout.Override.HotTrackRowCellAppearance = appearance96;
            appearance43.BackColor = System.Drawing.SystemColors.Window;
            appearance43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiGrid6.DisplayLayout.Override.RowAppearance = appearance43;
            this.soiGrid6.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid6.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance44.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiGrid6.DisplayLayout.Override.TemplateAddRowAppearance = appearance44;
            appearance97.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook6.ThumbAppearance = appearance97;
            this.soiGrid6.DisplayLayout.ScrollBarLook = scrollBarLook6;
            this.soiGrid6.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiGrid6.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiGrid6.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiGrid6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGrid6.Location = new System.Drawing.Point(2, 28);
            this.soiGrid6.Margin = new System.Windows.Forms.Padding(0);
            this.soiGrid6.Name = "soiGrid6";
            this.soiGrid6.Size = new System.Drawing.Size(515, 184);
            this.soiGrid6.TabIndex = 0;
            this.soiGrid6.Text = "soiGrid6";
            this.soiGrid6.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiGrid6.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.soiGrid6.UseSOIContextMenu = true;
            // 
            // frmSampleGrid
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1600, 600);
            this.Controls.Add(this.soiGroupBox6);
            this.Controls.Add(this.soiGroupBox5);
            this.Controls.Add(this.soiGroupBox4);
            this.Controls.Add(this.soiGroupBox3);
            this.Controls.Add(this.soiGroupBox2);
            this.Controls.Add(this.soiGroupBox1);
            this.Name = "frmSampleGrid";
            this.Text = "frmSampleGrid";
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox4)).EndInit();
            this.soiGroupBox4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox3)).EndInit();
            this.soiGroupBox3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox2)).EndInit();
            this.soiGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).EndInit();
            this.soiGroupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox5)).EndInit();
            this.soiGroupBox5.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox6)).EndInit();
            this.soiGroupBox6.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiGrid6)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private OIFrx.SOIControls.SOIGroupBox soiGroupBox1;
        private OIFrx.SOIControls.SOIGrid soiGrid1;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox2;
        private OIFrx.SOIControls.SOIGrid soiGrid2;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox3;
        private OIFrx.SOIControls.SOIGrid soiGrid3;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox4;
        private OIFrx.SOIControls.SOIGrid soiGrid4;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox5;
        private OIFrx.SOIControls.SOIGrid soiGrid5;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox6;
        private OIFrx.SOIControls.SOIGrid soiGrid6;
    }
}