namespace SOI.Samples.SampleControls
{
    partial class frmSampleListBox
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance25 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance41 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance59 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance42 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand1 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn3 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("img", 0);
            Infragistics.Win.Appearance appearance43 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn5 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("data", 1);
            Infragistics.Win.Appearance appearance44 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance45 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance46 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance47 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance48 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance49 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance50 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance51 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance52 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance53 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance54 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance55 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance56 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance57 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook1 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance58 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance13 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance1 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand2 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn1 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("chk", 0);
            Infragistics.Win.Appearance appearance20 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn2 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("data", 1);
            Infragistics.Win.Appearance appearance21 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance5 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance6 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance7 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance8 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance9 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance10 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance11 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance12 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook2 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance60 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance61 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance62 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance63 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand3 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn6 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("seq", 0);
            Infragistics.Win.Appearance appearance64 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn7 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("data", 1);
            Infragistics.Win.Appearance appearance65 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance66 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance67 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance68 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance69 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance70 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance71 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance72 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance73 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance74 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance75 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance76 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance77 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance78 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook3 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance79 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance81 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance82 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance99 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance83 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinGrid.UltraGridBand ultraGridBand4 = new Infragistics.Win.UltraWinGrid.UltraGridBand("", -1);
            Infragistics.Win.UltraWinGrid.UltraGridColumn ultraGridColumn9 = new Infragistics.Win.UltraWinGrid.UltraGridColumn("data", 0);
            Infragistics.Win.Appearance appearance84 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance85 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance86 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance87 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance88 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance89 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance90 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance91 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance92 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance93 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance94 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance95 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance96 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance97 = new Infragistics.Win.Appearance();
            Infragistics.Win.UltraWinScrollBar.ScrollBarLook scrollBarLook4 = new Infragistics.Win.UltraWinScrollBar.ScrollBarLook();
            Infragistics.Win.Appearance appearance98 = new Infragistics.Win.Appearance();
            this.soiGroupBox3 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiListBox4 = new SOI.OIFrx.SOIControls.SOIListBox(this.components);
            this.soiGroupBox2 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiListBox3 = new SOI.OIFrx.SOIControls.SOIListBox(this.components);
            this.soiGroupBox1 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiListBox2 = new SOI.OIFrx.SOIControls.SOIListBox(this.components);
            this.soiGroupBox7 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiListBox1 = new SOI.OIFrx.SOIControls.SOIListBox(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox3)).BeginInit();
            this.soiGroupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox2)).BeginInit();
            this.soiGroupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).BeginInit();
            this.soiGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox7)).BeginInit();
            this.soiGroupBox7.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // soiGroupBox3
            // 
            this.soiGroupBox3._UseOITheme = false;
            this.soiGroupBox3._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance25.BackColor = System.Drawing.Color.Black;
            appearance25.BackColor2 = System.Drawing.Color.Black;
            appearance25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance25.BorderColor2 = System.Drawing.Color.Black;
            appearance25.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox3.Appearance = appearance25;
            this.soiGroupBox3.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance41.BackColor = System.Drawing.Color.White;
            appearance41.BackColor2 = System.Drawing.Color.White;
            appearance41.BorderColor = System.Drawing.Color.Black;
            appearance41.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox3.ContentAreaAppearance = appearance41;
            this.soiGroupBox3.Controls.Add(this.soiListBox4);
            appearance59.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance59.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance59.BorderColor = System.Drawing.Color.Black;
            appearance59.BorderColor2 = System.Drawing.Color.Black;
            appearance59.FontData.BoldAsString = "True";
            appearance59.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox3.HeaderAppearance = appearance59;
            this.soiGroupBox3.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox3.Location = new System.Drawing.Point(437, 241);
            this.soiGroupBox3.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox3.Name = "soiGroupBox3";
            this.soiGroupBox3.Size = new System.Drawing.Size(391, 198);
            this.soiGroupBox3.TabIndex = 9;
            this.soiGroupBox3.Text = "List Box (Image / Text)";
            this.soiGroupBox3.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiListBox4
            // 
            this.soiListBox4._UseConvertLanguage = false;
            this.soiListBox4._UseOITheme = true;
            this.soiListBox4._UseStyle = SOI.OIFrx.SOIListBoxStyle.DefaultStyle;
            appearance42.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
            appearance42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiListBox4.DisplayLayout.Appearance = appearance42;
            this.soiListBox4.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridBand1.ColHeadersVisible = false;
            appearance43.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance43.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance43.TextHAlignAsString = "Center";
            appearance43.TextVAlignAsString = "Middle";
            ultraGridColumn3.CellAppearance = appearance43;
            ultraGridColumn3.DataType = typeof(System.Drawing.Bitmap);
            ultraGridColumn3.Header.VisiblePosition = 0;
            ultraGridColumn3.Width = 50;
            appearance44.TextHAlignAsString = "Left";
            appearance44.TextVAlignAsString = "Middle";
            ultraGridColumn5.CellAppearance = appearance44;
            ultraGridColumn5.Header.VisiblePosition = 1;
            ultraGridBand1.Columns.AddRange(new object[] {
            ultraGridColumn3,
            ultraGridColumn5});
            this.soiListBox4.DisplayLayout.BandsSerializer.Add(ultraGridBand1);
            this.soiListBox4.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox4.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox4.DisplayLayout.CellHottrackInvalidationStyle = Infragistics.Win.UltraWinGrid.CellHottrackInvalidationStyle.OnlyIfHottrackAppearance;
            this.soiListBox4.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(234)))), ((int)(((byte)(251)))));
            this.soiListBox4.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.Empty;
            appearance45.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance45.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance45.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance45.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox4.DisplayLayout.GroupByBox.Appearance = appearance45;
            appearance46.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox4.DisplayLayout.GroupByBox.BandLabelAppearance = appearance46;
            this.soiListBox4.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox4.DisplayLayout.GroupByBox.Hidden = true;
            appearance47.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance47.BackColor2 = System.Drawing.SystemColors.Control;
            appearance47.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance47.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox4.DisplayLayout.GroupByBox.PromptAppearance = appearance47;
            this.soiListBox4.DisplayLayout.MaxColScrollRegions = 1;
            this.soiListBox4.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiListBox4.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance48.BackColor = System.Drawing.SystemColors.Window;
            appearance48.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiListBox4.DisplayLayout.Override.ActiveCellAppearance = appearance48;
            appearance49.BackColor = System.Drawing.SystemColors.Highlight;
            appearance49.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiListBox4.DisplayLayout.Override.ActiveRowAppearance = appearance49;
            this.soiListBox4.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.None;
            this.soiListBox4.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.None;
            appearance50.BackColor = System.Drawing.SystemColors.Window;
            this.soiListBox4.DisplayLayout.Override.CardAreaAppearance = appearance50;
            appearance51.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance51.FontData.BoldAsString = "True";
            appearance51.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(73)))), ((int)(((byte)(129)))));
            appearance51.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.soiListBox4.DisplayLayout.Override.CellAppearance = appearance51;
            this.soiListBox4.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiListBox4.DisplayLayout.Override.CellPadding = 0;
            this.soiListBox4.DisplayLayout.Override.DefaultRowHeight = 50;
            appearance52.BackColor = System.Drawing.SystemColors.Control;
            appearance52.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance52.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance52.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance52.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox4.DisplayLayout.Override.GroupByRowAppearance = appearance52;
            appearance53.TextHAlignAsString = "Left";
            this.soiListBox4.DisplayLayout.Override.HeaderAppearance = appearance53;
            this.soiListBox4.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.ExternalSortSingle;
            this.soiListBox4.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance54.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox4.DisplayLayout.Override.HotTrackRowAppearance = appearance54;
            appearance55.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox4.DisplayLayout.Override.HotTrackRowCellAppearance = appearance55;
            appearance56.BackColor = System.Drawing.SystemColors.Window;
            appearance56.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiListBox4.DisplayLayout.Override.RowAppearance = appearance56;
            this.soiListBox4.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox4.DisplayLayout.Override.RowSpacingAfter = 2;
            this.soiListBox4.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance57.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiListBox4.DisplayLayout.Override.TemplateAddRowAppearance = appearance57;
            appearance58.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook1.ThumbAppearance = appearance58;
            this.soiListBox4.DisplayLayout.ScrollBarLook = scrollBarLook1;
            this.soiListBox4.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiListBox4.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiListBox4.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiListBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiListBox4.Location = new System.Drawing.Point(2, 28);
            this.soiListBox4.Margin = new System.Windows.Forms.Padding(0);
            this.soiListBox4.Name = "soiListBox4";
            this.soiListBox4.Size = new System.Drawing.Size(387, 168);
            this.soiListBox4.TabIndex = 2;
            this.soiListBox4.Text = "soiListBox4";
            this.soiListBox4.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiListBox4.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // soiGroupBox2
            // 
            this.soiGroupBox2._UseOITheme = false;
            this.soiGroupBox2._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance17.BackColor = System.Drawing.Color.Black;
            appearance17.BackColor2 = System.Drawing.Color.Black;
            appearance17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance17.BorderColor2 = System.Drawing.Color.Black;
            appearance17.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox2.Appearance = appearance17;
            this.soiGroupBox2.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance19.BackColor = System.Drawing.Color.White;
            appearance19.BackColor2 = System.Drawing.Color.White;
            appearance19.BorderColor = System.Drawing.Color.Black;
            appearance19.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox2.ContentAreaAppearance = appearance19;
            this.soiGroupBox2.Controls.Add(this.soiListBox3);
            appearance13.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance13.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance13.BorderColor = System.Drawing.Color.Black;
            appearance13.BorderColor2 = System.Drawing.Color.Black;
            appearance13.FontData.BoldAsString = "True";
            appearance13.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox2.HeaderAppearance = appearance13;
            this.soiGroupBox2.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox2.Location = new System.Drawing.Point(14, 241);
            this.soiGroupBox2.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox2.Name = "soiGroupBox2";
            this.soiGroupBox2.Size = new System.Drawing.Size(389, 198);
            this.soiGroupBox2.TabIndex = 8;
            this.soiGroupBox2.Text = "List Box (CheckBox / Text)";
            this.soiGroupBox2.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiListBox3
            // 
            this.soiListBox3._UseConvertLanguage = false;
            this.soiListBox3._UseOITheme = true;
            this.soiListBox3._UseStyle = SOI.OIFrx.SOIListBoxStyle.DefaultStyle;
            appearance1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
            appearance1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiListBox3.DisplayLayout.Appearance = appearance1;
            this.soiListBox3.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridBand2.ColHeadersVisible = false;
            appearance20.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance20.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance20.TextHAlignAsString = "Center";
            appearance20.TextVAlignAsString = "Middle";
            ultraGridColumn1.CellAppearance = appearance20;
            ultraGridColumn1.DataType = typeof(bool);
            ultraGridColumn1.Header.VisiblePosition = 0;
            ultraGridColumn1.Width = 50;
            appearance21.TextHAlignAsString = "Left";
            appearance21.TextVAlignAsString = "Middle";
            ultraGridColumn2.CellAppearance = appearance21;
            ultraGridColumn2.Header.VisiblePosition = 1;
            ultraGridBand2.Columns.AddRange(new object[] {
            ultraGridColumn1,
            ultraGridColumn2});
            this.soiListBox3.DisplayLayout.BandsSerializer.Add(ultraGridBand2);
            this.soiListBox3.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox3.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox3.DisplayLayout.CellHottrackInvalidationStyle = Infragistics.Win.UltraWinGrid.CellHottrackInvalidationStyle.OnlyIfHottrackAppearance;
            this.soiListBox3.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(234)))), ((int)(((byte)(251)))));
            this.soiListBox3.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.Empty;
            appearance2.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance2.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance2.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance2.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox3.DisplayLayout.GroupByBox.Appearance = appearance2;
            appearance3.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox3.DisplayLayout.GroupByBox.BandLabelAppearance = appearance3;
            this.soiListBox3.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox3.DisplayLayout.GroupByBox.Hidden = true;
            appearance4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance4.BackColor2 = System.Drawing.SystemColors.Control;
            appearance4.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance4.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox3.DisplayLayout.GroupByBox.PromptAppearance = appearance4;
            this.soiListBox3.DisplayLayout.MaxColScrollRegions = 1;
            this.soiListBox3.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiListBox3.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance5.BackColor = System.Drawing.SystemColors.Window;
            appearance5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiListBox3.DisplayLayout.Override.ActiveCellAppearance = appearance5;
            appearance6.BackColor = System.Drawing.SystemColors.Highlight;
            appearance6.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiListBox3.DisplayLayout.Override.ActiveRowAppearance = appearance6;
            this.soiListBox3.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.None;
            this.soiListBox3.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.None;
            appearance7.BackColor = System.Drawing.SystemColors.Window;
            this.soiListBox3.DisplayLayout.Override.CardAreaAppearance = appearance7;
            appearance8.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance8.FontData.BoldAsString = "True";
            appearance8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(73)))), ((int)(((byte)(129)))));
            appearance8.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.soiListBox3.DisplayLayout.Override.CellAppearance = appearance8;
            this.soiListBox3.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiListBox3.DisplayLayout.Override.CellPadding = 0;
            this.soiListBox3.DisplayLayout.Override.DefaultRowHeight = 50;
            appearance9.BackColor = System.Drawing.SystemColors.Control;
            appearance9.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance9.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance9.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance9.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox3.DisplayLayout.Override.GroupByRowAppearance = appearance9;
            appearance10.TextHAlignAsString = "Left";
            this.soiListBox3.DisplayLayout.Override.HeaderAppearance = appearance10;
            this.soiListBox3.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.ExternalSortSingle;
            this.soiListBox3.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance22.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox3.DisplayLayout.Override.HotTrackRowAppearance = appearance22;
            appearance23.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox3.DisplayLayout.Override.HotTrackRowCellAppearance = appearance23;
            appearance11.BackColor = System.Drawing.SystemColors.Window;
            appearance11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiListBox3.DisplayLayout.Override.RowAppearance = appearance11;
            this.soiListBox3.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox3.DisplayLayout.Override.RowSpacingAfter = 2;
            this.soiListBox3.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiListBox3.DisplayLayout.Override.TemplateAddRowAppearance = appearance12;
            appearance24.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook2.ThumbAppearance = appearance24;
            this.soiListBox3.DisplayLayout.ScrollBarLook = scrollBarLook2;
            this.soiListBox3.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiListBox3.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiListBox3.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiListBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiListBox3.Location = new System.Drawing.Point(2, 28);
            this.soiListBox3.Margin = new System.Windows.Forms.Padding(0);
            this.soiListBox3.Name = "soiListBox3";
            this.soiListBox3.Size = new System.Drawing.Size(385, 168);
            this.soiListBox3.TabIndex = 2;
            this.soiListBox3.Text = "soiListBox3";
            this.soiListBox3.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiListBox3.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // soiGroupBox1
            // 
            this.soiGroupBox1._UseOITheme = false;
            this.soiGroupBox1._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance60.BackColor = System.Drawing.Color.Black;
            appearance60.BackColor2 = System.Drawing.Color.Black;
            appearance60.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance60.BorderColor2 = System.Drawing.Color.Black;
            appearance60.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox1.Appearance = appearance60;
            this.soiGroupBox1.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance61.BackColor = System.Drawing.Color.White;
            appearance61.BackColor2 = System.Drawing.Color.White;
            appearance61.BorderColor = System.Drawing.Color.Black;
            appearance61.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox1.ContentAreaAppearance = appearance61;
            this.soiGroupBox1.Controls.Add(this.soiListBox2);
            appearance62.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance62.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance62.BorderColor = System.Drawing.Color.Black;
            appearance62.BorderColor2 = System.Drawing.Color.Black;
            appearance62.FontData.BoldAsString = "True";
            appearance62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox1.HeaderAppearance = appearance62;
            this.soiGroupBox1.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox1.Location = new System.Drawing.Point(439, 14);
            this.soiGroupBox1.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox1.Name = "soiGroupBox1";
            this.soiGroupBox1.Size = new System.Drawing.Size(389, 198);
            this.soiGroupBox1.TabIndex = 7;
            this.soiGroupBox1.Text = "List Box (Number / Text)";
            this.soiGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiListBox2
            // 
            this.soiListBox2._UseConvertLanguage = false;
            this.soiListBox2._UseOITheme = true;
            this.soiListBox2._UseStyle = SOI.OIFrx.SOIListBoxStyle.DefaultStyle;
            appearance63.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
            appearance63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiListBox2.DisplayLayout.Appearance = appearance63;
            this.soiListBox2.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridBand3.ColHeadersVisible = false;
            appearance64.ImageHAlign = Infragistics.Win.HAlign.Center;
            appearance64.ImageVAlign = Infragistics.Win.VAlign.Middle;
            appearance64.TextHAlignAsString = "Center";
            appearance64.TextVAlignAsString = "Middle";
            ultraGridColumn6.CellAppearance = appearance64;
            ultraGridColumn6.DataType = typeof(int);
            ultraGridColumn6.Header.VisiblePosition = 0;
            ultraGridColumn6.Width = 50;
            appearance65.TextHAlignAsString = "Left";
            appearance65.TextVAlignAsString = "Middle";
            ultraGridColumn7.CellAppearance = appearance65;
            ultraGridColumn7.Header.VisiblePosition = 1;
            ultraGridBand3.Columns.AddRange(new object[] {
            ultraGridColumn6,
            ultraGridColumn7});
            this.soiListBox2.DisplayLayout.BandsSerializer.Add(ultraGridBand3);
            this.soiListBox2.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox2.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox2.DisplayLayout.CellHottrackInvalidationStyle = Infragistics.Win.UltraWinGrid.CellHottrackInvalidationStyle.OnlyIfHottrackAppearance;
            this.soiListBox2.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(234)))), ((int)(((byte)(251)))));
            this.soiListBox2.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.Empty;
            appearance66.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance66.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance66.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance66.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox2.DisplayLayout.GroupByBox.Appearance = appearance66;
            appearance67.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox2.DisplayLayout.GroupByBox.BandLabelAppearance = appearance67;
            this.soiListBox2.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox2.DisplayLayout.GroupByBox.Hidden = true;
            appearance68.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance68.BackColor2 = System.Drawing.SystemColors.Control;
            appearance68.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance68.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox2.DisplayLayout.GroupByBox.PromptAppearance = appearance68;
            this.soiListBox2.DisplayLayout.MaxColScrollRegions = 1;
            this.soiListBox2.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiListBox2.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance69.BackColor = System.Drawing.SystemColors.Window;
            appearance69.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiListBox2.DisplayLayout.Override.ActiveCellAppearance = appearance69;
            appearance70.BackColor = System.Drawing.SystemColors.Highlight;
            appearance70.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiListBox2.DisplayLayout.Override.ActiveRowAppearance = appearance70;
            this.soiListBox2.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.None;
            this.soiListBox2.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.None;
            appearance71.BackColor = System.Drawing.SystemColors.Window;
            this.soiListBox2.DisplayLayout.Override.CardAreaAppearance = appearance71;
            appearance72.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance72.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance72.FontData.BoldAsString = "True";
            appearance72.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(73)))), ((int)(((byte)(129)))));
            appearance72.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.soiListBox2.DisplayLayout.Override.CellAppearance = appearance72;
            this.soiListBox2.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiListBox2.DisplayLayout.Override.CellPadding = 0;
            this.soiListBox2.DisplayLayout.Override.DefaultRowHeight = 50;
            appearance73.BackColor = System.Drawing.SystemColors.Control;
            appearance73.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance73.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance73.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance73.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox2.DisplayLayout.Override.GroupByRowAppearance = appearance73;
            appearance74.TextHAlignAsString = "Left";
            this.soiListBox2.DisplayLayout.Override.HeaderAppearance = appearance74;
            this.soiListBox2.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.ExternalSortSingle;
            this.soiListBox2.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance75.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox2.DisplayLayout.Override.HotTrackRowAppearance = appearance75;
            appearance76.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox2.DisplayLayout.Override.HotTrackRowCellAppearance = appearance76;
            appearance77.BackColor = System.Drawing.SystemColors.Window;
            appearance77.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiListBox2.DisplayLayout.Override.RowAppearance = appearance77;
            this.soiListBox2.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox2.DisplayLayout.Override.RowSpacingAfter = 2;
            this.soiListBox2.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance78.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiListBox2.DisplayLayout.Override.TemplateAddRowAppearance = appearance78;
            appearance79.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook3.ThumbAppearance = appearance79;
            this.soiListBox2.DisplayLayout.ScrollBarLook = scrollBarLook3;
            this.soiListBox2.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiListBox2.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiListBox2.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiListBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiListBox2.Location = new System.Drawing.Point(2, 28);
            this.soiListBox2.Margin = new System.Windows.Forms.Padding(0);
            this.soiListBox2.Name = "soiListBox2";
            this.soiListBox2.Size = new System.Drawing.Size(385, 168);
            this.soiListBox2.TabIndex = 2;
            this.soiListBox2.Text = "soiListBox2";
            this.soiListBox2.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiListBox2.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // soiGroupBox7
            // 
            this.soiGroupBox7._UseOITheme = false;
            this.soiGroupBox7._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance81.BackColor = System.Drawing.Color.Black;
            appearance81.BackColor2 = System.Drawing.Color.Black;
            appearance81.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance81.BorderColor2 = System.Drawing.Color.Black;
            appearance81.BorderColor3DBase = System.Drawing.Color.Black;
            this.soiGroupBox7.Appearance = appearance81;
            this.soiGroupBox7.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.RectangularSolid;
            appearance82.BackColor = System.Drawing.Color.White;
            appearance82.BackColor2 = System.Drawing.Color.White;
            appearance82.BorderColor = System.Drawing.Color.Black;
            appearance82.BorderColor2 = System.Drawing.Color.Black;
            this.soiGroupBox7.ContentAreaAppearance = appearance82;
            this.soiGroupBox7.Controls.Add(this.soiListBox1);
            appearance99.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance99.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(36)))), ((int)(((byte)(47)))));
            appearance99.BorderColor = System.Drawing.Color.Black;
            appearance99.BorderColor2 = System.Drawing.Color.Black;
            appearance99.FontData.BoldAsString = "True";
            appearance99.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox7.HeaderAppearance = appearance99;
            this.soiGroupBox7.HeaderBorderStyle = Infragistics.Win.UIElementBorderStyle.TwoColor;
            this.soiGroupBox7.Location = new System.Drawing.Point(14, 14);
            this.soiGroupBox7.Margin = new System.Windows.Forms.Padding(5);
            this.soiGroupBox7.Name = "soiGroupBox7";
            this.soiGroupBox7.Size = new System.Drawing.Size(389, 198);
            this.soiGroupBox7.TabIndex = 6;
            this.soiGroupBox7.Text = "Default List Box (Text)";
            this.soiGroupBox7.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.Office2003;
            // 
            // soiListBox1
            // 
            this.soiListBox1._UseConvertLanguage = false;
            this.soiListBox1._UseOITheme = true;
            this.soiListBox1._UseStyle = SOI.OIFrx.SOIListBoxStyle.DefaultStyle;
            appearance83.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
            appearance83.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152)))));
            this.soiListBox1.DisplayLayout.Appearance = appearance83;
            this.soiListBox1.DisplayLayout.AutoFitStyle = Infragistics.Win.UltraWinGrid.AutoFitStyle.ExtendLastColumn;
            ultraGridBand4.ColHeadersVisible = false;
            appearance84.TextHAlignAsString = "Left";
            appearance84.TextVAlignAsString = "Middle";
            ultraGridColumn9.CellAppearance = appearance84;
            ultraGridColumn9.Header.VisiblePosition = 0;
            ultraGridBand4.Columns.AddRange(new object[] {
            ultraGridColumn9});
            this.soiListBox1.DisplayLayout.BandsSerializer.Add(ultraGridBand4);
            this.soiListBox1.DisplayLayout.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox1.DisplayLayout.CaptionVisible = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox1.DisplayLayout.CellHottrackInvalidationStyle = Infragistics.Win.UltraWinGrid.CellHottrackInvalidationStyle.OnlyIfHottrackAppearance;
            this.soiListBox1.DisplayLayout.DefaultSelectedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(234)))), ((int)(((byte)(251)))));
            this.soiListBox1.DisplayLayout.DefaultSelectedForeColor = System.Drawing.Color.Empty;
            appearance85.BackColor = System.Drawing.SystemColors.ActiveBorder;
            appearance85.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance85.BackGradientStyle = Infragistics.Win.GradientStyle.Vertical;
            appearance85.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox1.DisplayLayout.GroupByBox.Appearance = appearance85;
            appearance86.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox1.DisplayLayout.GroupByBox.BandLabelAppearance = appearance86;
            this.soiListBox1.DisplayLayout.GroupByBox.BorderStyle = Infragistics.Win.UIElementBorderStyle.Solid;
            this.soiListBox1.DisplayLayout.GroupByBox.Hidden = true;
            appearance87.BackColor = System.Drawing.SystemColors.ControlLightLight;
            appearance87.BackColor2 = System.Drawing.SystemColors.Control;
            appearance87.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance87.ForeColor = System.Drawing.SystemColors.GrayText;
            this.soiListBox1.DisplayLayout.GroupByBox.PromptAppearance = appearance87;
            this.soiListBox1.DisplayLayout.MaxColScrollRegions = 1;
            this.soiListBox1.DisplayLayout.MaxRowScrollRegions = 1;
            this.soiListBox1.DisplayLayout.Override.ActiveAppearancesEnabled = Infragistics.Win.DefaultableBoolean.False;
            appearance88.BackColor = System.Drawing.SystemColors.Window;
            appearance88.ForeColor = System.Drawing.SystemColors.ControlText;
            this.soiListBox1.DisplayLayout.Override.ActiveCellAppearance = appearance88;
            appearance89.BackColor = System.Drawing.SystemColors.Highlight;
            appearance89.ForeColor = System.Drawing.SystemColors.HighlightText;
            this.soiListBox1.DisplayLayout.Override.ActiveRowAppearance = appearance89;
            this.soiListBox1.DisplayLayout.Override.BorderStyleCell = Infragistics.Win.UIElementBorderStyle.None;
            this.soiListBox1.DisplayLayout.Override.BorderStyleRow = Infragistics.Win.UIElementBorderStyle.None;
            appearance90.BackColor = System.Drawing.SystemColors.Window;
            this.soiListBox1.DisplayLayout.Override.CardAreaAppearance = appearance90;
            appearance91.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance91.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance91.FontData.BoldAsString = "True";
            appearance91.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(73)))), ((int)(((byte)(129)))));
            appearance91.TextTrimming = Infragistics.Win.TextTrimming.EllipsisCharacter;
            this.soiListBox1.DisplayLayout.Override.CellAppearance = appearance91;
            this.soiListBox1.DisplayLayout.Override.CellClickAction = Infragistics.Win.UltraWinGrid.CellClickAction.RowSelect;
            this.soiListBox1.DisplayLayout.Override.CellPadding = 0;
            this.soiListBox1.DisplayLayout.Override.DefaultRowHeight = 50;
            appearance92.BackColor = System.Drawing.SystemColors.Control;
            appearance92.BackColor2 = System.Drawing.SystemColors.ControlDark;
            appearance92.BackGradientAlignment = Infragistics.Win.GradientAlignment.Element;
            appearance92.BackGradientStyle = Infragistics.Win.GradientStyle.Horizontal;
            appearance92.BorderColor = System.Drawing.SystemColors.Window;
            this.soiListBox1.DisplayLayout.Override.GroupByRowAppearance = appearance92;
            appearance93.TextHAlignAsString = "Left";
            this.soiListBox1.DisplayLayout.Override.HeaderAppearance = appearance93;
            this.soiListBox1.DisplayLayout.Override.HeaderClickAction = Infragistics.Win.UltraWinGrid.HeaderClickAction.ExternalSortSingle;
            this.soiListBox1.DisplayLayout.Override.HeaderStyle = Infragistics.Win.HeaderStyle.Standard;
            appearance94.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox1.DisplayLayout.Override.HotTrackRowAppearance = appearance94;
            appearance95.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(214)))), ((int)(((byte)(243)))));
            this.soiListBox1.DisplayLayout.Override.HotTrackRowCellAppearance = appearance95;
            appearance96.BackColor = System.Drawing.SystemColors.Window;
            appearance96.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiListBox1.DisplayLayout.Override.RowAppearance = appearance96;
            this.soiListBox1.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.False;
            this.soiListBox1.DisplayLayout.Override.RowSpacingAfter = 2;
            this.soiListBox1.DisplayLayout.Override.SelectTypeRow = Infragistics.Win.UltraWinGrid.SelectType.Single;
            appearance97.BackColor = System.Drawing.SystemColors.ControlLight;
            this.soiListBox1.DisplayLayout.Override.TemplateAddRowAppearance = appearance97;
            appearance98.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            scrollBarLook4.ThumbAppearance = appearance98;
            this.soiListBox1.DisplayLayout.ScrollBarLook = scrollBarLook4;
            this.soiListBox1.DisplayLayout.ScrollBounds = Infragistics.Win.UltraWinGrid.ScrollBounds.ScrollToFill;
            this.soiListBox1.DisplayLayout.ScrollStyle = Infragistics.Win.UltraWinGrid.ScrollStyle.Immediate;
            this.soiListBox1.DisplayLayout.ViewStyleBand = Infragistics.Win.UltraWinGrid.ViewStyleBand.OutlookGroupBy;
            this.soiListBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiListBox1.Location = new System.Drawing.Point(2, 28);
            this.soiListBox1.Margin = new System.Windows.Forms.Padding(0);
            this.soiListBox1.Name = "soiListBox1";
            this.soiListBox1.Size = new System.Drawing.Size(385, 168);
            this.soiListBox1.TabIndex = 2;
            this.soiListBox1.Text = "soiListBox1";
            this.soiListBox1.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.soiListBox1.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            // 
            // frmSampleListBox
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.ClientSize = new System.Drawing.Size(1600, 600);
            this.Controls.Add(this.soiGroupBox3);
            this.Controls.Add(this.soiGroupBox2);
            this.Controls.Add(this.soiGroupBox1);
            this.Controls.Add(this.soiGroupBox7);
            this.Name = "frmSampleListBox";
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox3)).EndInit();
            this.soiGroupBox3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox2)).EndInit();
            this.soiGroupBox2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).EndInit();
            this.soiGroupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox7)).EndInit();
            this.soiGroupBox7.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.soiListBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private OIFrx.SOIControls.SOIGroupBox soiGroupBox7;
        private OIFrx.SOIControls.SOIListBox soiListBox1;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox1;
        private OIFrx.SOIControls.SOIListBox soiListBox2;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox2;
        private OIFrx.SOIControls.SOIListBox soiListBox3;
        private OIFrx.SOIControls.SOIGroupBox soiGroupBox3;
        private OIFrx.SOIControls.SOIListBox soiListBox4;
    }
}