namespace SOI.HanwhaQcell.USModule.CWIP.Popup
{
    partial class frmCWIPCellLocationPopup
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            FarPoint.Win.Spread.EnhancedScrollBarRenderer enhancedScrollBarRenderer1 = new FarPoint.Win.Spread.EnhancedScrollBarRenderer();
            FarPoint.Win.Spread.EnhancedScrollBarRenderer enhancedScrollBarRenderer2 = new FarPoint.Win.Spread.EnhancedScrollBarRenderer();
            Infragistics.Win.Appearance appearance17 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance18 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance19 = new Infragistics.Win.Appearance();
            this.soiPanel1 = new SOI.OIFrx.SOIControls.SOIPanel(this.components);
            this.spdCellMap = new SOI.OIFrx.SOIControls.SOISpread();
            this.spdCellMap_Sheet1 = new FarPoint.Win.Spread.SheetView();
            this.btnFieldsReset = new SOI.OIFrx.SOIControls.SOIButton(this.components);
            this.pnlPopupTop.SuspendLayout();
            this.pnlPopupBottom.SuspendLayout();
            this.pnlPopupMiddle.SuspendLayout();
            this.pnlPopupTopMargin.SuspendLayout();
            this.pnlPopupBottomMargin.SuspendLayout();
            this.pnlPopupMiddleMargin.SuspendLayout();
            this.soiPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spdCellMap)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdCellMap_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // lblPopupTitle
            // 
            this.lblPopupTitle.Size = new System.Drawing.Size(974, 38);
            this.lblPopupTitle.Text = "Cell Location";
            // 
            // pnlPopupTop
            // 
            this.pnlPopupTop.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(120)))), ((int)(((byte)(215)))));
            this.pnlPopupTop.Location = new System.Drawing.Point(3, 4);
            this.pnlPopupTop.Size = new System.Drawing.Size(994, 48);
            // 
            // pnlPopupBottom
            // 
            this.pnlPopupBottom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.pnlPopupBottom.Location = new System.Drawing.Point(3, 436);
            this.pnlPopupBottom.Size = new System.Drawing.Size(994, 50);
            // 
            // btnClose
            // 
            this.btnClose.Location = new System.Drawing.Point(874, 0);
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // pnlPopupMiddle
            // 
            this.pnlPopupMiddle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.pnlPopupMiddle.Location = new System.Drawing.Point(3, 56);
            this.pnlPopupMiddle.Size = new System.Drawing.Size(994, 380);
            // 
            // pnlPopupTopMargin
            // 
            this.pnlPopupTopMargin.Size = new System.Drawing.Size(974, 38);
            // 
            // pnlPopupBottomMargin
            // 
            this.pnlPopupBottomMargin.Controls.Add(this.btnFieldsReset);
            this.pnlPopupBottomMargin.Size = new System.Drawing.Size(974, 40);
            this.pnlPopupBottomMargin.Controls.SetChildIndex(this.btnClose, 0);
            this.pnlPopupBottomMargin.Controls.SetChildIndex(this.btnFieldsReset, 0);
            // 
            // pnlPopupMiddleMargin
            // 
            this.pnlPopupMiddleMargin.Controls.Add(this.soiPanel1);
            this.pnlPopupMiddleMargin.Size = new System.Drawing.Size(974, 370);
            // 
            // soiPanel1
            // 
            this.soiPanel1._SetAutoScrollPanel = false;
            this.soiPanel1._UseOITheme = true;
            this.soiPanel1._UseStyle = SOI.OIFrx.SOIPanelStyle.TransparentStyle;
            this.soiPanel1.BackColor = System.Drawing.Color.Transparent;
            this.soiPanel1.Controls.Add(this.spdCellMap);
            this.soiPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiPanel1.Location = new System.Drawing.Point(0, 0);
            this.soiPanel1.Margin = new System.Windows.Forms.Padding(10, 5, 10, 5);
            this.soiPanel1.Name = "soiPanel1";
            this.soiPanel1.Size = new System.Drawing.Size(974, 370);
            this.soiPanel1.TabIndex = 3;
            // 
            // spdCellMap
            // 
            this.spdCellMap._UseAutoHeight = true;
            this.spdCellMap._UseOITheme = true;
            this.spdCellMap.AccessibleDescription = "spdCellMap, Sheet1, Row 0, Column 0, ";
            this.spdCellMap.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdCellMap.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.spdCellMap.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spdCellMap.EditModePermanent = true;
            this.spdCellMap.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            this.spdCellMap.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdCellMap.HorizontalScrollBar.Name = "";
            enhancedScrollBarRenderer1.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ArrowHoveredColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ArrowSelectedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ButtonBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer1.ButtonBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer1.ButtonHoveredBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonHoveredBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonSelectedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.TrackBarBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
            enhancedScrollBarRenderer1.TrackBarSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.spdCellMap.HorizontalScrollBar.Renderer = enhancedScrollBarRenderer1;
            this.spdCellMap.HorizontalScrollBar.TabIndex = 0;
            this.spdCellMap.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdCellMap.Location = new System.Drawing.Point(0, 0);
            this.spdCellMap.Margin = new System.Windows.Forms.Padding(0);
            this.spdCellMap.Name = "spdCellMap";
            this.spdCellMap.ScrollBarTrackPolicy = FarPoint.Win.Spread.ScrollBarTrackPolicy.Both;
            this.spdCellMap.ScrollTipPolicy = FarPoint.Win.Spread.ScrollTipPolicy.Both;
            this.spdCellMap.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spdCellMap_Sheet1});
            this.spdCellMap.Size = new System.Drawing.Size(974, 370);
            this.spdCellMap.SOICellHeight = 25;
            this.spdCellMap.SOIColumnHeight = 50;
            this.spdCellMap.TabIndex = 9;
            this.spdCellMap.TabStop = false;
            this.spdCellMap.TextTipPolicy = FarPoint.Win.Spread.TextTipPolicy.Floating;
            this.spdCellMap.UseSOIContextMenu = true;
            this.spdCellMap.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdCellMap.VerticalScrollBar.Name = "";
            enhancedScrollBarRenderer2.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ArrowHoveredColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ArrowSelectedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ButtonBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer2.ButtonBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer2.ButtonHoveredBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonHoveredBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonSelectedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.TrackBarBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
            enhancedScrollBarRenderer2.TrackBarSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.spdCellMap.VerticalScrollBar.Renderer = enhancedScrollBarRenderer2;
            this.spdCellMap.VerticalScrollBar.TabIndex = 91;
            this.spdCellMap.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdCellMap.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap.CellClick += new FarPoint.Win.Spread.CellClickEventHandler(this.spdCellMap_CellClick);
            // 
            // spdCellMap_Sheet1
            // 
            this.spdCellMap_Sheet1.Reset();
            spdCellMap_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spdCellMap_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            spdCellMap_Sheet1.ColumnCount = 26;
            spdCellMap_Sheet1.RowCount = 6;
            this.spdCellMap_Sheet1.ActiveSkin = FarPoint.Win.Spread.DefaultSkins.Classic1;
            this.spdCellMap_Sheet1.Cells.Get(0, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(0, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(0, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(0, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(1, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(1, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(1, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(2, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(2, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(2, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(3, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(3, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(3, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(4, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(4, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(4, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 0).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 0).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 1).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 1).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 2).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 2).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 3).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 3).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 4).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 4).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 5).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 5).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 6).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 6).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 7).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 7).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 8).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 8).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 9).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 9).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 10).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 10).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 11).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 11).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 12).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 12).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 13).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 13).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 14).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 14).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 15).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 15).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 16).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 16).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 17).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 17).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 18).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 18).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 19).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 19).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 20).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 20).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 21).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 21).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 22).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 22).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 23).Font = new System.Drawing.Font("굴림", 8F);
            this.spdCellMap_Sheet1.Cells.Get(5, 23).ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.Cells.Get(5, 23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdCellMap_Sheet1.Cells.Get(5, 23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdCellMap_Sheet1.ColumnFooter.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.Parent = "HeaderDefault";
            this.spdCellMap_Sheet1.ColumnFooter.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnFooter.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.ForeColor = System.Drawing.Color.White;
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.Parent = "HeaderDefault";
            this.spdCellMap_Sheet1.ColumnFooterSheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "1";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "2";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "3";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "4";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "5";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "6";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "7";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "8";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "9";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "10";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 10).Value = "11";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 11).Value = "12";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 12).Value = "13";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 13).Value = "14";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 14).Value = "15";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 15).Value = "16";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 16).Value = "17";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 17).Value = "18";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 18).Value = "19";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 19).Value = "20";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 20).Value = "21";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 21).Value = "22";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 22).Value = "23";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 23).Value = "24";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 24).Value = "25";
            this.spdCellMap_Sheet1.ColumnHeader.Cells.Get(0, 25).Value = "26";
            this.spdCellMap_Sheet1.ColumnHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.Parent = "HeaderDefault";
            this.spdCellMap_Sheet1.ColumnHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnHeader.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.ColumnHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.ColumnHeader.Rows.Get(0).Height = 50F;
            this.spdCellMap_Sheet1.ColumnHeader.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.Columns.Get(0).Label = "1";
            this.spdCellMap_Sheet1.Columns.Get(0).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(1).Label = "2";
            this.spdCellMap_Sheet1.Columns.Get(1).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(2).Label = "3";
            this.spdCellMap_Sheet1.Columns.Get(2).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(3).Label = "4";
            this.spdCellMap_Sheet1.Columns.Get(3).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(4).Label = "5";
            this.spdCellMap_Sheet1.Columns.Get(4).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(5).Label = "6";
            this.spdCellMap_Sheet1.Columns.Get(5).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(6).Label = "7";
            this.spdCellMap_Sheet1.Columns.Get(6).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(7).Label = "8";
            this.spdCellMap_Sheet1.Columns.Get(7).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(8).Label = "9";
            this.spdCellMap_Sheet1.Columns.Get(8).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(9).Label = "10";
            this.spdCellMap_Sheet1.Columns.Get(9).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(10).Label = "11";
            this.spdCellMap_Sheet1.Columns.Get(10).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(11).Label = "12";
            this.spdCellMap_Sheet1.Columns.Get(11).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(12).Label = "13";
            this.spdCellMap_Sheet1.Columns.Get(12).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(13).Label = "14";
            this.spdCellMap_Sheet1.Columns.Get(13).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(14).Label = "15";
            this.spdCellMap_Sheet1.Columns.Get(14).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(15).Label = "16";
            this.spdCellMap_Sheet1.Columns.Get(15).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(16).Label = "17";
            this.spdCellMap_Sheet1.Columns.Get(16).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(17).Label = "18";
            this.spdCellMap_Sheet1.Columns.Get(17).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(18).Label = "19";
            this.spdCellMap_Sheet1.Columns.Get(18).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(19).Label = "20";
            this.spdCellMap_Sheet1.Columns.Get(19).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(20).Label = "21";
            this.spdCellMap_Sheet1.Columns.Get(20).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(21).Label = "22";
            this.spdCellMap_Sheet1.Columns.Get(21).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(22).Label = "23";
            this.spdCellMap_Sheet1.Columns.Get(22).Width = 36F;
            this.spdCellMap_Sheet1.Columns.Get(23).Label = "24";
            this.spdCellMap_Sheet1.Columns.Get(23).Width = 32F;
            this.spdCellMap_Sheet1.Columns.Get(24).Label = "25";
            this.spdCellMap_Sheet1.Columns.Get(24).Width = 32F;
            this.spdCellMap_Sheet1.Columns.Get(25).Label = "26";
            this.spdCellMap_Sheet1.Columns.Get(25).Width = 32F;
            this.spdCellMap_Sheet1.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdCellMap_Sheet1.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.spdCellMap_Sheet1.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.DefaultStyle.Parent = "DataAreaDefault";
            this.spdCellMap_Sheet1.GrayAreaBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdCellMap_Sheet1.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.OperationMode = FarPoint.Win.Spread.OperationMode.ReadOnly;
            this.spdCellMap_Sheet1.PrintInfo.ShowColor = true;
            this.spdCellMap_Sheet1.PrintInfo.UseSmartPrint = true;
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(0, 0).Value = "A";
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(1, 0).Value = "B";
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(2, 0).Value = "C";
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(3, 0).Value = "D";
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(4, 0).Value = "E";
            this.spdCellMap_Sheet1.RowHeader.Cells.Get(5, 0).Value = "F";
            this.spdCellMap_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spdCellMap_Sheet1.RowHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.RowHeader.Columns.Get(0).Width = 40F;
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.Parent = "HeaderDefault";
            this.spdCellMap_Sheet1.RowHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.RowHeader.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.RowHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.RowHeader.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.Rows.Get(0).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(0).Label = "A";
            this.spdCellMap_Sheet1.Rows.Get(1).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(1).Label = "B";
            this.spdCellMap_Sheet1.Rows.Get(2).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(2).Label = "C";
            this.spdCellMap_Sheet1.Rows.Get(3).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(3).Label = "D";
            this.spdCellMap_Sheet1.Rows.Get(4).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(4).Label = "E";
            this.spdCellMap_Sheet1.Rows.Get(5).Height = 25F;
            this.spdCellMap_Sheet1.Rows.Get(5).Label = "F";
            this.spdCellMap_Sheet1.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(164)))), ((int)(((byte)(238)))));
            this.spdCellMap_Sheet1.SelectionStyle = FarPoint.Win.Spread.SelectionStyles.SelectionColors;
            this.spdCellMap_Sheet1.SheetCornerHorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.SheetCornerStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdCellMap_Sheet1.SheetCornerStyle.Font = new System.Drawing.Font("맑은 고딕", 9.75F, System.Drawing.FontStyle.Bold);
            this.spdCellMap_Sheet1.SheetCornerStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdCellMap_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdCellMap_Sheet1.SheetCornerStyle.Parent = "HeaderDefault";
            this.spdCellMap_Sheet1.SheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdCellMap_Sheet1.SheetCornerVerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.ShowRowSelector = true;
            this.spdCellMap_Sheet1.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdCellMap_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // btnFieldsReset
            // 
            this.btnFieldsReset._UseOITheme = true;
            this.btnFieldsReset._UseStyle = SOI.OIFrx.SOIButtonStyle.DefaultStyle;
            this.btnFieldsReset.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            appearance17.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance17.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance17.BackColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            appearance17.BackColorDisabled2 = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            appearance17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance17.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance17.FontData.BoldAsString = "True";
            appearance17.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance17.ForeColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnFieldsReset.Appearance = appearance17;
            this.btnFieldsReset.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.btnFieldsReset.Cursor = System.Windows.Forms.Cursors.Hand;
            appearance18.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance18.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance18.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            this.btnFieldsReset.HotTrackAppearance = appearance18;
            this.btnFieldsReset.Location = new System.Drawing.Point(0, 0);
            this.btnFieldsReset.Margin = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnFieldsReset.Name = "btnFieldsReset";
            appearance19.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance19.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance19.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            this.btnFieldsReset.PressedAppearance = appearance19;
            this.btnFieldsReset.ShowFocusRect = false;
            this.btnFieldsReset.ShowOutline = false;
            this.btnFieldsReset.Size = new System.Drawing.Size(140, 40);
            this.btnFieldsReset.TabIndex = 4;
            this.btnFieldsReset.Text = "Fields Reset";
            this.btnFieldsReset.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnFieldsReset.UseHotTracking = Infragistics.Win.DefaultableBoolean.True;
            this.btnFieldsReset.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnFieldsReset.Click += new System.EventHandler(this.btnFieldsReset_Click);
            // 
            // frmCWIPCellLocationPopup
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1000, 490);
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "frmCWIPCellLocationPopup";
            this.Padding = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.Text = "frmCellLocationPopup";
            this.Load += new System.EventHandler(this.frmCellLocationPopup_Load);
            this.pnlPopupTop.ResumeLayout(false);
            this.pnlPopupBottom.ResumeLayout(false);
            this.pnlPopupMiddle.ResumeLayout(false);
            this.pnlPopupTopMargin.ResumeLayout(false);
            this.pnlPopupBottomMargin.ResumeLayout(false);
            this.pnlPopupMiddleMargin.ResumeLayout(false);
            this.soiPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spdCellMap)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdCellMap_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private OIFrx.SOIControls.SOIPanel soiPanel1;
        private OIFrx.SOIControls.SOISpread spdCellMap;
        private FarPoint.Win.Spread.SheetView spdCellMap_Sheet1;
        private OIFrx.SOIControls.SOIButton btnFieldsReset;

    }
}