[Basic]
MESplusCompany="Miracom Inc."
MESplusSiteID="MPT1"
MESplusTNS="MESDB"
MESplusUID="mesmgr"
MESplusPWD="mesmgr"
MESplusUseLocalDB="N"
MESplusConnectString="localhost:10101"
MESplusH101InterStationMode="N"
MESplusTibRvService=""
MESplusTibRvNetwork=""
;Upgrade method (MSG, FTP)
MESplusUpgradeMethod="FTP"
; MESplusUpgradeVersion have to belong 4 word by separated dot
MESplusUpgradeVersion="5.3.4.0"
;If UpgradeMethod="FTP" then set following record
MESplusUpgradeAddress="127.0.0.1"
MESplusUpgradeUser="mesmgr"
MESplusUpgradePassword="mesmgr"
MESplusLabelRemoteConnect="Y"
MESplusSharedLibPoolCount=10
MESplusLanguage="1"
MESplusMaxReconnectCount=10

[Directories]
MESplusHomeDir="D:\MESplusV5"
MESplusBinDir="D:\MESplusV5\bin"
MESplusCommandDir="D:\MESplusV5\cmd"
MESplusLogDir="D:\MESplusV5\log"
MESplusTempDir="D:\MESplusV5\temp"
MESplusSLibDir="D:\MESplusV5\lib"
MESplusScreenDir="D:\MESplusV5\data\screen"
MESplusDocTempDir="D:\MESplusV5\data\doctemp"
MESplusAlarmAttachDir="D:\MESplusV5\data\alarm"
MESplusBBSAttachDir="D:\MESplusV5\data\bbs"
MESplusSpecAttachDir="D:\MESplusV5\data\specification"
MESplusWorkProcStatusAttachDir="D:\MESplusV5\data\workprocess"
MESplusPopAttachDir="D:\MESplusV5\data\label"
MESplusLicenseDir="D:\MESplusV5\lic"
MESplusUpgradeDir="/upgrade"
;MESplusUpgradeDir="/user1/users/mpmgr/MESplus/upgrade/"

[Alarm]
MESplusSMTPServerName="mail.miracom.co.kr"
MESplusSMTPUserName="mesadmin"
MESplusSMTPPassword="mes"
MESplusFromID="mesadmin@miracom.co.kr"
MESplusContentsFileDel="Y"
MESplusContentsFileCopy="Y"
MESplusContentsDir="D:\MESplusV5\mail\contents"
MESplusContentsBackupDir="D:\MESplusV5\mail\contents\backup"
MESplusAlarmKeeping="Y"
;MESplusAlarmKeeping="Y" - Do not execute the action for the alarm occurrence directly but process it collectively only when the service is successful.
;MESplusAlarmKeeping="N" - Exectue the action immediately when alarm occurs.
MESplusCustomContentsTemplateDir="D:\MESplusV5\mail\template"

[SPC]
MESplusRuleCheckType="1"
;MESplusRuleCheckType = "1" Rule Check within the same managmet limit.
;MESplusRuleCheckType = "2" Each Rule Check regardless of management limit.

[ASC]
;MESplusUseASC="Y"              : "Y" or "N" - Set whether to use Advanced Security Control
;MESplusPasswordMinLength=6     : The minimum length of User Password, 0 <= length <= 20
;MESplusPasswordExpireNotice=3  : Set the number of days that should be informed before changing User Password
;MESplusPasswordCharNumber=2    : The minimum number of alphabet characters that should be included in User Password, number <= 20
;MESplusPasswordLockCount=5     : The count decides the number of User Password errors that make the user not use the current password, count >= 0
MESplusUseASC="Y"
MESplusPasswordMinLength=6
MESplusPasswordExpireNotice=3
MESplusPasswordCharNumber=2
MESplusPasswordLockCount=5

