[StartOption]
ProcessName="MESServer.exe"
ServerName="MESServer"
;MaxMsgLength Maximum middleware message length (byte)
MaxMsgLength=5100100

;
; Communication Channel Information
;
; MainChannel     : listen channel for request reply (Mandatory)
; AllowModuleList : Allow module list for main channel (Optional), If empty then allow all module's service.
; StopChannel     : listen subscribe channel for stop processor (Mandatory)
; AdminChannel    : listen subscribe channel for management processor (Mandatory)
; ExtraChannel    : listen channel for extra purpose (Optional)
;              Ex : /MPT1/MESServer/EQ:D;/MPT1/MESServer/EQ:S;/MPT1/MESServer/EQ:G;/MPT1/MESServer/EQ:M
;                 : each channel divided ';'
;                 : :D - process distributed queue(Unicast), :S - process subscribe(Multicast), :G - Guaranteed Unicast, :M - Guaranteed Multicast
; ExtraAllowModuleList : Allow module list for extra channel (Optional)
;                   Ex : WIP,RAS;FMB
;                      : each module divided ',' and the ';' character means assigned each extra channel
;
MainChannel="/MPT1/MESServer"
AllowModuleList=""
StopChannel="/STOP/MPT1/MESServer"
AdminChannel="/ADMIN/MPT1/MESServer"
ExtraChannel=""
ExtraAllowModuleList=""

;
; Highway101 Guaranteed Message Confirmation Point
; P - Before Prologue.
; A - After Epilogue, Always Confirmation.
; S - After Epilogue, It only confirm message when result of the request service is success.
;
ConfirmationPointForGuaranteedMessage="P"

;
;  Interval Unit : Seconds
;
ServerTimer1=0
ServerTimer2=0
ServerTimer3=0
ServerTimer4=0
ServerTimer5=0
ServerTimer6=0
ServerTimer7=0
ServerTimer8=0
ServerTimer9=0

;
; Database Connection Information.
; If set below value, MESServer use it to connect database instead of connecting information in MESplus.ini.
;
DatabaseTNS=""
DatabaseUID=""
DatabasePWD=""
DatabaseUseLocalDB=""

;
; Log Related Start Options
;
; LogMode : Set how to manage log file in several MESServer Processors.
; 1 = All Server Processors save the log by sharing a file.
; 2 = Each MEServer Processor saves the log with its own log file.
;
; LogLevel : Define the level of the log saved in the log file.
; 0 = Save all the logs of Error, Warning, Information, Debug
; 1 = Save all the logs of Error, Warning, Information
; 2 = Save only the log at Error, Warning
; 3 = Save only the log at Error
;
; LogFileSize : The maximum size that a log file can create. The unit is Kilo Byte.
; LogFileCount : The maximum number of the log file. The maximum value is 99. 
; LogWriteXML : The indicator whether to write XML string coming from client.
; LogFileByTime : The indicator whether to separate log file by hour.
; LogFromIntervalTimeOfQuery : The from time to write log for interval time of SQL query. time unit is seconds and it can define float value.
;                              If it defined under zero value then default value is 1 seconds
; LogWriteIntervalTime : determines whether to log SQL Query exceeding interval time in LogFromIntervalTimeOfQuery 
; LogNotWriteClientID : The indicator whether to write Client ID.
;

LogMode=1
LogLevel=1
LogFileSize=2000
LogFileCount=20
LogWriteXML="N"
LogFileByTime="N"
LogFromIntervalTimeOfQuery=0.9
LogWriteIntervalTime="N"
LogNotWriteClientID="N"

;
; RTD Option
;
UseRTD="N"
ProcessRTD="N"
RTDMaxProcessSubno="10"
RTDDelayTimeSec=5

; Define to 86400 if do not use RTD.
RTDServerPollingSec=86400

;=============================================================================
; Character converting option values for ICONV library on Linux
;
; European languages
;     ASCII, ISO-8859-{1,2,3,4,5,7,9,10,13,14,15,16}, KOI8-R, KOI8-U, KOI8-RU, CP{1250,1251,1252,1253,1254,1257}, CP{850,866,1131},
;     Mac{Roman,CentralEurope,Iceland,Croatian,Romania}, Mac{Cyrillic,Ukraine,Greek,Turkish}, Macintosh
; 
; Semitic languages
;     ISO-8859-{6,8}, CP{1255,1256}, CP862, Mac{Hebrew,Arabic}
; 
; Japanese
;     EUC-JP, SHIFT_JIS, CP932, ISO-2022-JP, ISO-2022-JP-2, ISO-2022-JP-1
; 
; Chinese
;     EUC-CN, HZ, GBK, CP936, GB18030, EUC-TW, BIG5, CP950, BIG5-HKSCS, BIG5-HKSCS:2001, BIG5-HKSCS:1999, ISO-2022-CN, ISO-2022-CN-EXT
; 
; Korean
;     EUC-KR, CP949, ISO-2022-KR, JOHAB
; 
; Armenian
;     ARMSCII-8
; 
; Georgian
;     Georgian-Academy, Georgian-PS
; 
; Tajik
;     KOI8-T
; 
; Kazakh
;     PT154, RK1048
; 
; Thai
;     TIS-620, CP874, MacThai
; 
; Laotian
;     MuleLao-1, CP1133
; 
; Vietnamese
;     VISCII, TCVN, CP1258
; 
; Platform specifics
;     HP-ROMAN8, NEXTSTEP
; 
; Full Unicode
;     UTF-8
;     UCS-2, UCS-2BE, UCS-2LE
;     UCS-4, UCS-4BE, UCS-4LE
;     UTF-16, UTF-16BE, UTF-16LE
;     UTF-32, UTF-32BE, UTF-32LE
;     UTF-7
;     C99, JAVA
; 
; Full Unicode, in terms of uint16_t or uint32_t (with machine dependent endianness and alignment)
;     UCS-2-INTERNAL, UCS-4-INTERNAL
; 
; Locale dependent, in terms of char or wchar_t (with machine dependent endianness and alignment, and with semantics depending on the OS and the current LC_CTYPE locale facet) char, wchar_t
; When configured with the option --enable-extra-encodings, it also provides support for a few extra encodings:
; 
;     European languages
;         CP{437,737,775,852,853,855,857,858,860,861,863,865,869,1125}
; 
;     Semitic languages
;         CP864
; 
;     Japanese
;         EUC-JISX0213, Shift_JISX0213, ISO-2022-JP-3
; 
;     Chinese
;         BIG5-2003 (experimental)
; 
;     Turkmen
;         TDS565
; 
;     Platform specifics
;         ATARIST, RISCOS-LATIN1
;
;=============================================================================
;
; Character converting option values on Windows
;
; Primary language    Sublanguage                 Language string
; ------------------- --------------------------- -----------------------------------------
; Chinese             Chinese                     "chinese"
; Chinese             Chinese (simplified)        "chinese-simplified" or "chs"
; Chinese             Chinese (traditional)       "chinese-traditional" or "cht"
; Czech               Czech                       "csy" or "czech"
; Danish              Danish                      "dan" or "danish"
; Dutch               Dutch (default)             "dutch" or "nld"
; Dutch               Dutch (Belgium)             "belgian", "dutch-belgian", or "nlb"
; English             English (default)           "english"
; English             English (Australia)         "australian", "ena", or "english-aus"
; English             English (Canada)            "canadian", "enc", or "english-can"
; English             English (New Zealand)       "english-nz" or "enz"
; English             English (United Kingdom)    "eng", "english-uk", or "uk"
; English             English (United States)     "american", "american english", "american-english", "english-american", "english-us", "english-usa", "enu", "us", or "usa"
; Finnish             Finnish                     "fin" or "finnish"
; French              French (default)            "fra" or "french"
; French              French (Belgium)            "frb" or "french-belgian"
; French              French (Canada)             "frc" or "french-canadian"
; French              French (Switzerland)        "french-swiss" or "frs"
; German              German (default)            "deu" or "german"
; German              German (Austria)            "dea" or "german-austrian"
; German              German (Switzerland)        "des", "german-swiss", or "swiss"
; Greek               Greek                       "ell" or "greek"
; Hungarian           Hungarian                   "hun" or "hungarian"
; Icelandic           Icelandic                   "icelandic" or "isl"
; Italian             Italian (default)           "ita" or "italian"
; Italian             Italian (Switzerland)       "italian-swiss" or "its"
; Japanese            Japanese                    "japanese" or "jpn"
; Korean              Korean                      "kor" or "korean"
; Norwegian           Norwegian (default)         "norwegian"
; Norwegian           Norwegian (Bokmal)          "nor" or "norwegian-bokmal"
; Norwegian           Norwegian (Nynorsk)         "non" or "norwegian-nynorsk"
; Polish              Polish                      "plk" or "polish"
; Portuguese          Portuguese (default)        "portuguese" or "ptg"
; Portuguese          Portuguese (Brazil)         "portuguese-brazilian" or "ptb"
; Russian             Russian (default)           "rus" or "russian"
; Slovak              Slovak                      "sky" or "slovak"
; Spanish             Spanish (default)           "esp" or "spanish"
; Spanish             Spanish (Mexico)            "esm" or "spanish-mexican"
; Spanish             Spanish (Modern)            "esn" or "spanish-modern"
; Swedish             Swedish                     "sve" or "swedish"
; Turkish             Turkish                     "trk" or "turkish"
;
;=============================================================================
;
; If "CharacterLocale" is "UTF-8" then it does not convert XML String to local character.
; 
; In case of Windows, "CharacterLocale" value is three-letter Country/Region-name codes are from the International Organization for Standardization and International Electrotechnical Commission (ISO/IEC) specification 3166.
;
;CharacterLocale="kor"
CharacterLocale="UTF-8"

;Ignore Time Zone Offset value, even if offset is diffrent, no recalulate date
;Once this flag is set to 'Y', no recalculation is applied even if offset from client is different from server.
TimeZoneOffSetIgnore="N"

;If this value is not set, system time will be automatically the standard.
;When TimeZoneOffSet is manually set, winter time should be standard.
TimeZoneOffSet="+0900"


;Originally, DATE_TYPE format from server is "YYYY-MM-DDThh:mm:ss.nnn+hh:mm"
;When flag,ShortXMLDateFormat, is set to 'Y', the DATE_TYPE format from server will be changed to "YYYY-MM-DDThh:mm:ss".
ShortXMLDateFormat="N"

CaseSensitiveName="Y"

;Use Daylight Saving Time Option
;DSTEndTime is for the end time of Daylight Saving Time.
;The format of the DSTEndTime is as "MONTH/FIRST(SECOND, THIRD, FOURTH, LAST)/SUN(MON,TUE,WED,THU,FRI,SAT) HOUR"
DSTTimeCompress="N"
DSTEndTime="10/LAST/SUN 03"

;
; Whether Validate XML value or not
;
ValidateXMLValue="N"

;
; Use Common Shared Library for Prologue and Epilogue
;
UseProEpiCommonSharedLibrary="N"

;
; Use Custom XML format
;
UseCustomXMLFormat="N"

;
; Check Memory Allocation Status (Monitoring, Logging)
;
CheckMemoryAllocation="N"

;
; EDC Option - Spec out mask character, Default Value '_'
;
UseSpecOutMaskCharacter="_"

;
;Collect Performance Information and Error Logging at DB Table
;If the service is more than specified second, Logging it
;
;CollectPerformanceInfo="Y" : Collect the information of service performance or not.
;CollectPerformanceCompressType="D"(day) or "M"(month) : Compression period is month or day.
;CollectPerformanceCompress="0" or month/day. : 0 is not use compression. if the value is not 0, it means to use to compress the service performance data before "month/day" value.
;CollectErrorLogging="Y" : Collect the information of service error or not.
;CollectedErrorKeeppingLimit="0" or day. : 0 is not delete the error log. if the value is not 0, it means to delete the service error log before "day" value.
;CollectTimeLimitSec="10" : The elapsed time of the service to check long processing service. if elapsed time over then this value then MESServer write log as "TIM-0000" code into collect error log.
;CollectNode="MPT1_MESServer" : The server name to indicate several MESServer.
;SubNoCompressDeleteErrorLog="01" : The Sub Number of the MESServer to perform compressing data of collected service performance and deleting data of collected service error log.

;CollectTableSpaceIncreaseInfo="Y" : Collect Tablespace increase information.
;CollectTableSpaceCheckSize="100" : MByte
;CollectLongQueryRankingInfo="Y" : Collect SQL Query ranking information.
;CollectLongQueryRankingType="B" : T(base on 10 minutes collect time), S(base on tablespace size), B(Both)
;CollectSQLTraceInfo="Y" : Collect SQL Trace information.

CollectPerformanceInfo="N"
CollectPerformanceCompressType="M"
CollectPerformanceCompress="1"
CollectErrorLogging="N"
CollectedErrorKeeppingLimit="20"
CollectTimeLimitSec="10"
CollectNode="MPT1_MESServer"
SubNoCompressDeleteErrorLog="01"

CollectTableSpaceIncreaseInfo="N"
CollectTableSpaceCheckSize="1000"
CollectLongQueryRankingInfo="N"
CollectLongQueryRankingType="B"
CollectSQLTraceInfo="N"

;
; WinForm Log Max Line Count Option
;
WinLogMaxLineCount="50"

;
; Batch Job Process Option
; BatchJobProcDelayMinute : Delay minute time for executing a single batch job processor when already it's running in the other processor.
;                           this value must be greater than 0. if the value is 0, default value will be 5.
BatchJobProcDelayMinute="5"

;
; Not use that transfer binary data Client and Server.
; This option set to 'Y' When just transfer xml data in Equipment Interface Server.
;
NotUseBinaryData="N"

;
; Max Windows in a row in MES Server
; Default Value is 3
;
MaxWindowsInRow=3

;
; Whether to hide the window of server
; Default Value is "N"
;
HideServerWindow="N"

;
; MES-EAI Interface Option
; H101EAIConnectString : The connection string for MESplus <-> Highway101 EAI interface.
;  Ex) H101EAIConnectString="xxx.xxx.xxx.xxx:10101"
; H101EAIInterStationMode : The station mode for MESplus <-> Highway101 EAI interface.
H101EAIConnectString=""
H101EAIInterStationMode="N"

;
; SQL Statement executed on start-up
; Default Value is ""
;
StartUpSQL1=""
StartUpSQL2=""
StartUpSQL3=""
StartUpSQL4=""
StartUpSQL5=""
StartUpSQL6=""
StartUpSQL7=""
StartUpSQL8=""
StartUpSQL9=""

