/*******************************************************************************
' RPTBASType.cs
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2010-01-29 13:54:48
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
'******************************************************************************/

using System;
using com.miracom.transceiverx.message.former;


namespace SOI.OIFrx
{
    public class Cmn_Out_Tag
    {
        public char h_status_value;
        public string h_msg_code;
        public string h_msg;
        public string h_field_msg;
        public string h_db_err_msg;
    }
    public class RPT_SQL_Query_In_Tag_cond_tbl
    {
        public string cond_id;
        public string cond_type;
        public string cond;
        public int cond_int;
        public double cond_dbl;
        public float cond_float;
    }
    public class RPT_SQL_Query_In_Tag
    {
        public string h_passport;
        public char h_language;
        public string h_factory;
        public string h_user_id;
        public string h_password;
        public char h_proc_step;
        public string sql;
        public int next_row;
        public string func_name;
        public string view_id;
        public string user_id;
        public string data_1;
        public string data_2;
        public string data_3;
        public string data_4;
        public string data_5;
        public string data_6;
        public string data_7;
        public string data_8;
        public string data_9;
        public string data_10;
        public string data_11;
        public string data_12;
        public string data_13;
        public string data_14;
        public string data_15;
        public string data_16;
        public string data_17;
        public string data_18;
        public string data_19;
        public string data_20;
        public int _size_cond_tbl;
        public RPT_SQL_Query_In_Tag_cond_tbl[] cond_tbl;
        public char icon_flag;
        public char bgcolor_flag;
    }

    public class RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl
    {
        public int data;
    }

    public class RPT_SQL_Query_DataTable_Result_Out_Tag
    {
        public char h_status_value;
        public string h_msg_code;
        public string h_msg;
        public string h_field_msg;
        public string h_db_err_msg;
        public int binary_length;
        public int col_count;
        public int row_count;
        public int data_count;
        public int next_row;
        public int _size_data_tbl;
        public RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl[] data_tbl;
        public char icon_flag;
        public char bgcolor_flag;
        public string s_sql_data;
    }
    public class h101type
    {
        protected static string deleteNull(string str)
        {
            if (null == str)
                return "";
            else
                return str.TrimEnd();
        }

        protected static string padding(string str, int size)
        {
            if (null != str)
            {
                while (str.Length < size)
                {
                    str += " ";
                }
            }
            return str;
        }
        protected static string withoutSpace(string str)
        {
            if (null != str)
            {
                str.TrimEnd();
            }
            return str;
        }
    }
    public class RPTBASType : h101type
    {
        public RPTBASType()
        {
        }

        public static void serialize_Cmn_Out_Tag(StreamTransformer former, Cmn_Out_Tag target)
        {
            former.writeMsgChar(target.h_status_value);
            former.writeMsgString(withoutSpace(target.h_msg_code));
            former.writeMsgString(withoutSpace(target.h_msg));
            former.writeMsgString(withoutSpace(target.h_field_msg));
            former.writeMsgString(withoutSpace(target.h_db_err_msg));
        }

        public static void transform_Cmn_Out_Tag(StreamTransformer former, ref Cmn_Out_Tag source)
        {
            source.h_status_value = former.readMsgChar();
            source.h_msg_code = deleteNull(former.readMsgString());
            source.h_msg = deleteNull(former.readMsgString());
            source.h_field_msg = deleteNull(former.readMsgString());
            source.h_db_err_msg = deleteNull(former.readMsgString());
        }
        public static void serialize_RPT_SQL_Query_In_Tag_cond_tbl(StreamTransformer former, RPT_SQL_Query_In_Tag_cond_tbl target)
        {
            former.writeMsgString(target.cond_id);
            former.writeMsgString(target.cond_type);
            former.writeMsgString(target.cond);
            former.writeMsgInt(target.cond_int);
            former.writeMsgDouble(target.cond_dbl);
            former.writeMsgFloat(target.cond_float);
        }
        public static void serialize_RPT_SQL_Query_In_Tag(StreamTransformer former, RPT_SQL_Query_In_Tag target)
        {
            former.writeMsgString(withoutSpace(target.h_passport));
            former.writeMsgChar(target.h_language);
            former.writeMsgString(withoutSpace(target.h_factory));
            former.writeMsgString(withoutSpace(target.h_user_id));
            former.writeMsgString(withoutSpace(target.h_password));
            former.writeMsgChar(target.h_proc_step);
            former.writeMsgString(withoutSpace(target.sql));
            former.writeMsgInt(target.next_row);
            former.writeMsgString(withoutSpace(target.func_name));
            former.writeMsgString(withoutSpace(target.view_id));
            former.writeMsgString(withoutSpace(target.user_id));
            former.writeMsgString(withoutSpace(target.data_1));
            former.writeMsgString(withoutSpace(target.data_2));
            former.writeMsgString(withoutSpace(target.data_3));
            former.writeMsgString(withoutSpace(target.data_4));
            former.writeMsgString(withoutSpace(target.data_5));
            former.writeMsgString(withoutSpace(target.data_6));
            former.writeMsgString(withoutSpace(target.data_7));
            former.writeMsgString(withoutSpace(target.data_8));
            former.writeMsgString(withoutSpace(target.data_9));
            former.writeMsgString(withoutSpace(target.data_10));
            former.writeMsgString(withoutSpace(target.data_11));
            former.writeMsgString(withoutSpace(target.data_12));
            former.writeMsgString(withoutSpace(target.data_13));
            former.writeMsgString(withoutSpace(target.data_14));
            former.writeMsgString(withoutSpace(target.data_15));
            former.writeMsgString(withoutSpace(target.data_16));
            former.writeMsgString(withoutSpace(target.data_17));
            former.writeMsgString(withoutSpace(target.data_18));
            former.writeMsgString(withoutSpace(target.data_19));
            former.writeMsgString(withoutSpace(target.data_20));
            former.writeMsgInt(target._size_cond_tbl);
            for (int i = 0; i < target._size_cond_tbl; i++)
            {
                serialize_RPT_SQL_Query_In_Tag_cond_tbl(former, target.cond_tbl[i]);
            }
            former.writeMsgChar(target.icon_flag);
            former.writeMsgChar(target.bgcolor_flag);
        }
        public static void transform_RPT_SQL_Query_In_Tag_cond_tbl(StreamTransformer former, ref RPT_SQL_Query_In_Tag_cond_tbl source)
        {
            source.cond_id = deleteNull(former.readMsgString());
            source.cond_type = deleteNull(former.readMsgString());
            source.cond = deleteNull(former.readMsgString());
            source.cond_int = former.readMsgInt();
            source.cond_dbl = former.readMsgDouble();
            source.cond_float = former.readMsgFloat();
        }
        public static void transform_RPT_SQL_Query_In_Tag(StreamTransformer former, ref RPT_SQL_Query_In_Tag source)
        {
            source.h_passport = deleteNull(former.readMsgString());
            source.h_language = former.readMsgChar();
            source.h_factory = deleteNull(former.readMsgString());
            source.h_user_id = deleteNull(former.readMsgString());
            source.h_password = deleteNull(former.readMsgString());
            source.h_proc_step = former.readMsgChar();
            source.sql = deleteNull(former.readMsgString());
            source.next_row = former.readMsgInt();
            source.func_name = deleteNull(former.readMsgString());
            source.view_id = deleteNull(former.readMsgString());
            source.user_id = deleteNull(former.readMsgString());
            source.data_1 = deleteNull(former.readMsgString());
            source.data_2 = deleteNull(former.readMsgString());
            source.data_3 = deleteNull(former.readMsgString());
            source.data_4 = deleteNull(former.readMsgString());
            source.data_5 = deleteNull(former.readMsgString());
            source.data_6 = deleteNull(former.readMsgString());
            source.data_7 = deleteNull(former.readMsgString());
            source.data_8 = deleteNull(former.readMsgString());
            source.data_9 = deleteNull(former.readMsgString());
            source.data_10 = deleteNull(former.readMsgString());
            source.data_11 = deleteNull(former.readMsgString());
            source.data_12 = deleteNull(former.readMsgString());
            source.data_13 = deleteNull(former.readMsgString());
            source.data_14 = deleteNull(former.readMsgString());
            source.data_15 = deleteNull(former.readMsgString());
            source.data_16 = deleteNull(former.readMsgString());
            source.data_17 = deleteNull(former.readMsgString());
            source.data_18 = deleteNull(former.readMsgString());
            source.data_19 = deleteNull(former.readMsgString());
            source.data_20 = deleteNull(former.readMsgString());
            source._size_cond_tbl = former.readMsgInt();
            source.cond_tbl = new RPT_SQL_Query_In_Tag_cond_tbl[source._size_cond_tbl];
            for (int i = 0; i < source._size_cond_tbl; i++)
            {
                source.cond_tbl[i] = new RPT_SQL_Query_In_Tag_cond_tbl();
                transform_RPT_SQL_Query_In_Tag_cond_tbl(former, ref source.cond_tbl[i]);
            }
            source.icon_flag = former.readMsgChar();
            source.bgcolor_flag = former.readMsgChar();
        }

        public static void serialize_RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl(StreamTransformer former, RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl target)
        {
            former.writeMsgInt(target.data);
        }

        public static void serialize_RPT_SQL_Query_DataTable_Result_Out_Tag(StreamTransformer former, RPT_SQL_Query_DataTable_Result_Out_Tag target)
        {
            former.writeMsgChar(target.h_status_value);
            former.writeMsgString(withoutSpace(target.h_msg_code));
            former.writeMsgString(withoutSpace(target.h_msg));
            former.writeMsgString(withoutSpace(target.h_field_msg));
            former.writeMsgString(withoutSpace(target.h_db_err_msg));
            former.writeMsgInt(target.binary_length);
            former.writeMsgInt(target.col_count);
            former.writeMsgInt(target.row_count);
            former.writeMsgInt(target.data_count);
            former.writeMsgInt(target.next_row);
            target._size_data_tbl = (10000000 >= target._size_data_tbl ? target._size_data_tbl : 10000000);
            former.writeMsgInt(target._size_data_tbl);
            for (int i = 0; i < target._size_data_tbl; i++)
            {
                serialize_RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl(former, target.data_tbl[i]);
            }
            former.writeMsgChar(target.icon_flag);
            former.writeMsgChar(target.bgcolor_flag);
            former.writeMsgString(withoutSpace(target.s_sql_data));
        }

        public static void transform_RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl(StreamTransformer former, ref RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl source)
        {
            source.data = former.readMsgInt();
        }

        public static void transform_RPT_SQL_Query_DataTable_Result_Out_Tag(StreamTransformer former, ref RPT_SQL_Query_DataTable_Result_Out_Tag source)
        {
            source.h_status_value = former.readMsgChar();
            source.h_msg_code = deleteNull(former.readMsgString());
            source.h_msg = deleteNull(former.readMsgString());
            source.h_field_msg = deleteNull(former.readMsgString());
            source.h_db_err_msg = deleteNull(former.readMsgString());
            source.binary_length = former.readMsgInt();
            source.col_count = former.readMsgInt();
            source.row_count = former.readMsgInt();
            source.data_count = former.readMsgInt();
            source.next_row = former.readMsgInt();
            source._size_data_tbl = former.readMsgInt();
            source.data_tbl = new RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl[source._size_data_tbl];
            for (int i = 0; i < source._size_data_tbl; i++)
            {
                source.data_tbl[i] = new RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl();
                transform_RPT_SQL_Query_DataTable_Result_Out_Tag_data_tbl(former, ref source.data_tbl[i]);
            }
            source.icon_flag = former.readMsgChar();
            source.bgcolor_flag = former.readMsgChar();
            source.s_sql_data = deleteNull(former.readMsgString());
        }
    }
}