/*******************************************************************************
' WIPCaster.cs
'
' Copyright (c) 2007 by Miracom,Inc.
' All rights reserved.
'
' Generated by DevTool XMLGen 1.0
'
' Created at 2008/07/04 15:53:51
'
' Author : Miracom. R&D.
' Description : DevTool Xml Generator Version 1.0
*******************************************************************************/
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Runtime.Serialization.Formatters.Binary;
using System.Data;
using System.Windows.Forms;
using System.Drawing;

using Miracom.CliFrx;
using Miracom.TRSCore;
using Miracom.MESCore;
using Miracom.MsgHandler;
//using Infragistics.Win.UltraWinListView;

namespace SOI.OIFrx
{
    public sealed class TPDR
    {
        public static int giMaxDataConut = 0;
        public static int DEFAULT_MAX_DATA_COUNT = 50000;

        public static TRSNode gTRSImage = new TRSNode("ImageList");

        public static string MP_GCM_LINE_BY_OPER = "C@LINE_BY_OPER";

        public static string MP_VL_INV_LOT_LIST_01 = "VL_INV_LOT_LIST_01";
        public static string MP_VL_INV_LOT_LIST_02 = "VL_INV_LOT_LIST_02";
        public static string MP_VL_INV_MAT_LIST_01 = "VL_INV_MAT_LIST_01";

        public static bool bUseIcon;
        public static bool bUseBGColor;

        public struct DirectViewCond
        {
            public string sCondtion_ID;
            public string sCondition_Type;
            public object sCondition_Value;
            public int iCondition_Value;
            public double dCondition_Value;
            public float fCondition_Value;
        }

        public static void initImage()
        {
            gTRSImage.SetInt("FACTORY", 0);
            gTRSImage.SetInt("SHIP_FACTORY", 2);
            gTRSImage.SetInt("TRANSACTION", 10);
            gTRSImage.SetInt("SETUP", 11);
            gTRSImage.SetInt("EVENT", 12);
            gTRSImage.SetInt("CODE_TABLE", 13);
            gTRSImage.SetInt("CODE_DATA", 14);
            gTRSImage.SetInt("MATERIAL", 15);
            gTRSImage.SetInt("FLOW", 16);
            gTRSImage.SetInt("REWORK_FLOW", 17);
            gTRSImage.SetInt("OPER", 18);
            gTRSImage.SetInt("MFO", 19);
            gTRSImage.SetInt("SEC_GROUP", 20);
            gTRSImage.SetInt("USER", 21);
            gTRSImage.SetInt("RESOURCE", 22);
            gTRSImage.SetInt("RESOURCE_PROC", 23);
            gTRSImage.SetInt("RESOURCE_DOWN", 24);
            gTRSImage.SetInt("RESOURCE_GROUP", 25);
            gTRSImage.SetInt("SUB_EQUIP", 26);
            gTRSImage.SetInt("STATUS", 27);
            gTRSImage.SetInt("CHARACTER", 28);
            gTRSImage.SetInt("COL_SET", 29);
            gTRSImage.SetInt("COL_SET_VERSION", 29);
            gTRSImage.SetInt("COL_SET_DELETE", 30);
            gTRSImage.SetInt("COL_SET_AUTO", 31);
            gTRSImage.SetInt("CARRIER", 32);
            gTRSImage.SetInt("CARRIER_EMPTY", 33);
            gTRSImage.SetInt("CARRIER_FULL", 34);
            gTRSImage.SetInt("LOT", 35);
            gTRSImage.SetInt("LOT_CHECK", 36);
            gTRSImage.SetInt("LOT_HOLD", 37);
            gTRSImage.SetInt("LOT_HOLD_CHECK", 38);
            gTRSImage.SetInt("LOT_RELEASE", 39);
            gTRSImage.SetInt("LOT_REWORK", 40);
            gTRSImage.SetInt("LOT_REWORK_CHECK", 41);
            gTRSImage.SetInt("LOT_ALTER", 42);
            gTRSImage.SetInt("LOT_ALTER_CHECK", 43);
            gTRSImage.SetInt("LOT_START", 44);
            gTRSImage.SetInt("LOT_START_CHECK", 45);
            gTRSImage.SetInt("CHART", 46);
            gTRSImage.SetInt("CHART_LINE", 47);
            gTRSImage.SetInt("LOG_SHEET", 48);
            gTRSImage.SetInt("AREA", 49);
            gTRSImage.SetInt("SUB_AREA", 50);
            gTRSImage.SetInt("FUNCTION_GROUP", 51);
            gTRSImage.SetInt("FUNCTION", 52);
            gTRSImage.SetInt("MESSAGE_GROUP", 53);
            gTRSImage.SetInt("MESSAGE", 54);
            gTRSImage.SetInt("PRIORITY", 55);
            gTRSImage.SetInt("BOM", 56);
            gTRSImage.SetInt("PORT", 57);
            gTRSImage.SetInt("ORDER", 58);
            gTRSImage.SetInt("ORDER_DELETE", 59);
            gTRSImage.SetInt("PART", 60);
            gTRSImage.SetInt("INQUIRY", 61);
            gTRSImage.SetInt("SUB_LOT", 62);
            gTRSImage.SetInt("HISTORY", 63);
            gTRSImage.SetInt("HISTORY_DELETE", 64);
            gTRSImage.SetInt("ALARM", 65);
            gTRSImage.SetInt("DEPARTMENT", 66);
            gTRSImage.SetInt("CALENDAR", 67);
            gTRSImage.SetInt("KEY", 68);
            gTRSImage.SetInt("CUSTOMER", 69);
            gTRSImage.SetInt("CATEGORY", 70);
            gTRSImage.SetInt("YEAR", 71);
            gTRSImage.SetInt("MONTH", 72);
            gTRSImage.SetInt("PM", 73);
            gTRSImage.SetInt("POLICY", 74);
            gTRSImage.SetInt("OPTION", 75);
            gTRSImage.SetInt("SLOT_EMPTY", 76);
            gTRSImage.SetInt("SLOT_FULL", 77);
            gTRSImage.SetInt("SLOT_FULL_NEW", 78);
            gTRSImage.SetInt("SLOT_COMBINE", 79);
            gTRSImage.SetInt("RECIPE", 80);
            gTRSImage.SetInt("STOCKER", 81);
            gTRSImage.SetInt("PRIVILEGE", 82);
            gTRSImage.SetInt("PRIVILEGE_GROUP", 83);
            gTRSImage.SetInt("LABEL", 84);
            gTRSImage.SetInt("TOOL", 85);
            gTRSImage.SetInt("TOOL_EVENT", 86);
            gTRSImage.SetInt("TOOL_TYPE", 87);
            gTRSImage.SetInt("ALARM_ERROR", 88);
            gTRSImage.SetInt("ALARM_WARN", 89);
            gTRSImage.SetInt("ALARM_INFO", 90);
            gTRSImage.SetInt("TOOL_SCRAP", 91);
            gTRSImage.SetInt("REPAIR_LOT", 92);
            gTRSImage.SetInt("DISPATCHER", 93);
            gTRSImage.SetInt("TOOL_RETURN", 94);
            gTRSImage.SetInt("EQ_TYPE", 95);
            gTRSImage.SetInt("RCP_MGR_DIR", 96);
            gTRSImage.SetInt("MODULE_DIR", 97);
            gTRSImage.SetInt("MODULE", 98);
            gTRSImage.SetInt("RCP_HOLD", 99);
            gTRSImage.SetInt("VERSION", 100);
            gTRSImage.SetInt("VERSION_REQUEST", 101);
            gTRSImage.SetInt("VERSION_APPROVAL", 102);
            gTRSImage.SetInt("VERSION_ACTIVATE", 103);
            gTRSImage.SetInt("WHITE_IMAGE", 104);
            gTRSImage.SetInt("PRIVILEGE_SERVICE", 105);
            gTRSImage.SetInt("SUB_RES_DOWN", 106);
            gTRSImage.SetInt("PORT_DOWN", 107);
            return;
        }

        public static void DataDecompress(byte[] _BinaryDataZip, ref byte[] _BinaryData, int _BinaryDataLength)
        {
            MemoryStream ms = null;
            GZipStream zipStream = null;
            try
            {
                // Use the newly created memory stream for the decompressed data.
                ms = new MemoryStream(_BinaryDataZip);
                zipStream = new GZipStream(ms, CompressionMode.Decompress);
                _BinaryData = new byte[_BinaryDataLength];
                zipStream.Read(_BinaryData, 0, _BinaryDataLength);
                zipStream.Close();
                ms.Close();
                zipStream.Dispose();
                ms.Dispose();
            }
            catch (Exception ex)
            {
                throw ex;
                //MessageBox.Show(ex.Message);
                ////MPCF.ShowMsgBox(ex.Message);
                //return;
            }
            finally
            {
                if (zipStream != null) { zipStream.Close(); zipStream.Dispose(); zipStream = null; }
                if (ms != null) { ms.Close(); ms.Dispose(); ms = null; }
            }
        }

        public static bool deserializeFromBinary(byte[] _BinaryData, ref DataTable dt)
        {
            BinaryFormatter binFormatter = null;
            MemoryStream memStm = null;
            try
            {
                binFormatter = new BinaryFormatter();
                memStm = new MemoryStream(_BinaryData);
                if (memStm.Length == 0)
                {
                    return false;
                }
                //if (memStm.Length > 134217728)
                //{
                //    MPCF.ShowMsgBox(MPCF.GetMessage(202));
                //    return false;
                //}
                dt = (DataTable)binFormatter.Deserialize(memStm);
                memStm.Dispose();

                GC.Collect();
                GC.GetTotalMemory(true);
                return true;
            }
            catch (Exception ex)
            {
                MPCF.ShowMsgBox(ex.Message);
                GC.Collect();
                GC.GetTotalMemory(true);
                return false;
            }
            finally
            {
                binFormatter = null;
                if (memStm != null)
                {
                    
                    memStm.Dispose();
                    memStm = null;
                }
            }
        }


        //
        // DirectViewOne()
        //       - Get Direct View Result
        // Return Value
        //       - true/false
        // Arguments
        //        - string ViewID                : View ID
        //        - params string[] Cond         : Condition List   $C_X   ex) $C_1, $C_2, $C_3,......
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt)
        {
            return DirectViewOne(oDisplay, ViewID, ref dt, true, true, null, true, false);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, DirectViewCond[] Cond)
        {
            return DirectViewOne(oDisplay, ViewID, ref dt, true, true, Cond, true, false);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor)
        {
            return DirectViewOne(oDisplay, ViewID, ref dt, bIcon, bBGColor, null, true, false);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor, DirectViewCond[] Cond)
        {
            return DirectViewOne(oDisplay, ViewID, ref dt, bIcon, bBGColor, Cond, true, false);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor, DirectViewCond[] Cond, bool bColumnFit)
        {
            return DirectViewOne(oDisplay, ViewID, ref dt, bIcon, bBGColor, Cond, bColumnFit, false);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor, DirectViewCond[] Cond, bool bColumnFit, bool bAutoSort)
        {
            string sTemp = string.Empty;

            return DirectViewOne(oDisplay, ViewID, ref dt, bIcon, bBGColor, Cond, bColumnFit, bAutoSort, ref sTemp);
        }
        public static bool DirectViewOne(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor, DirectViewCond[] Cond, bool bColumnFit, bool bAutoSort, ref string sSql)
        {
            int i;
            int iBGIndex;
            int iFirstIndex;
            int iIndex;
            int iSortIndWidth = 0;
            int iColWidth;
            int iDataWidth;
            int itemWidth = 0;

            string s_column = "";
            string sColor;

            FarPoint.Win.Spread.CellType.NumberCellType numCell = new FarPoint.Win.Spread.CellType.NumberCellType();
           

            try
            {
                numCell.DecimalPlaces = 3;
                numCell.ShowSeparator = true;
                numCell.FixedPoint = false;


                //Get Data from server. 
                //Currently no meaning for sql. it work with 'View ID'
                if (GetDataOne(s_column, ref dt, ViewID, Cond, bIcon, bBGColor, ref sSql) == false)
                    return false;

                //Target Object Spread case
                if (oDisplay is FarPoint.Win.Spread.FpSpread)
                {
                    //Convert object type
                    FarPoint.Win.Spread.FpSpread spdDisplay;
                    spdDisplay = (FarPoint.Win.Spread.FpSpread)oDisplay;

                    //Initialize Spread
                    spdDisplay.ActiveSheet.RowCount = 0;
                   

                    if (dt.Rows.Count == 0)
                        return true;

                    //Bind Data Table
                    
                    spdDisplay.ActiveSheet.ColumnCount = 0;
                    spdDisplay.DataSource = null;
                    spdDisplay.DataSource = dt;


                    //Get first column index (Icon data column, BackColor data column) 
                    iFirstIndex = 0;
                    //if (bIcon == true)
                    if (bUseIcon == true)
                        iFirstIndex++;

                    //if (bBGColor == true)
                    if (bUseBGColor == true)
                        iFirstIndex++;


                    //Display Icon and Back Color
                    //if (bIcon == true)
                    if (bUseIcon == true || bUseBGColor == true)
                    {
                        FarPoint.Win.Spread.CellType.ImageCellType imgCellType = new FarPoint.Win.Spread.CellType.ImageCellType();

                        //Add Icon Column
                        spdDisplay.ActiveSheet.Columns.Add(0, 1);
                        spdDisplay.ActiveSheet.Columns[0].CellType = imgCellType;
                        spdDisplay.ActiveSheet.ColumnHeader.Cells[0, 0].Text = "-";

                        TPDR.initImage();

                        //Get Image list from Main screen
                        ImageList iTemp = MPGV.gIMdiForm.GetSmallIconList();  

                        for (i = 0; i < spdDisplay.ActiveSheet.RowCount; i++)
                        {
                            //Apply Icon image
                            if(bUseIcon == true)
                            {
                                spdDisplay.ActiveSheet.Cells[i, 0].Value = iTemp.Images[gTRSImage.GetInt(dt.Rows[i].ItemArray.GetValue(0).ToString())];
                            }

                            //Apply Background color
                            //if (bBGColor == true)
                            if (bUseIcon == true && bUseBGColor == true)
                            {
                                sColor = dt.Rows[i].ItemArray.GetValue(1).ToString();
                                if (MPCF.Trim(sColor) != "")
                                    spdDisplay.ActiveSheet.Rows[i].BackColor = Color.FromName(dt.Rows[i].ItemArray.GetValue(1).ToString());
                            }
                            else if (bUseIcon == false && bUseBGColor == true)
                            {
                                sColor = dt.Rows[i].ItemArray.GetValue(0).ToString();
                                if (MPCF.Trim(sColor) != "")
                                    spdDisplay.ActiveSheet.Rows[i].BackColor = Color.FromName(dt.Rows[i].ItemArray.GetValue(0).ToString());
                            }
                        }

                        //Remove Icon and Background color data column
                        //if (bIcon == true)
                        if (bUseIcon == true)
                            spdDisplay.ActiveSheet.Columns[1].Remove();
                        //if (bBGColor == true)
                        if (bUseIcon == true && bUseBGColor == true)
                        {
                            spdDisplay.ActiveSheet.Columns[1].Remove();
                        }
                        else if (bUseIcon == false && bUseBGColor == true)
                        {
                            spdDisplay.ActiveSheet.Columns[0].Remove();
                            spdDisplay.ActiveSheet.Columns[0].Remove();
                        }
                            
                    }

                    for (i = 0; i < spdDisplay.ActiveSheet.ColumnCount; i++)
                    {
                        // Header Caption 

                        //spdDisplay.ActiveSheet.ColumnHeader.Cells[0, i].Text = GenCaptionText(spdDisplay.ActiveSheet.ColumnHeader.Cells[0, i].Text);

                        spdDisplay.ActiveSheet.Columns[i].Label = GenCaptionText(spdDisplay.ActiveSheet.Columns[i].Label);

                        if (spdDisplay.Sheets[0].Columns[i].CellType is FarPoint.Win.Spread.CellType.NumberCellType)
                        {                            
                            spdDisplay.Sheets[0].Columns[i].CellType = numCell;
                        }
                    }

                    //Fit column size with maximum data length.
                    //Can not use function MPCF.FitColumnHeader  -> Too slow

                    //MPCF.FitColumnHeader(spdDisplay);
                    if (bColumnFit == true)
                    {
                        Graphics g = spdDisplay.CreateGraphics();

                        for (i = 0; i < spdDisplay.ActiveSheet.ColumnCount; i++)
                        {
                            itemWidth = 0;
                            //Fit Icon column size
                            //if (i == 0 && bIcon == true)
                            if (i == 0 && bUseIcon == true)
                            {
                                spdDisplay.ActiveSheet.Columns[0].Width = spdDisplay.ActiveSheet.GetPreferredColumnWidth(0, false, false, false);
                                continue;
                            }

                            if (bAutoSort == true)
                                iSortIndWidth = 10;
                            else
                                iSortIndWidth = 0;

                                for (int j = 0; j < spdDisplay.ActiveSheet.RowCount; j++)
                                {
                                    iIndex = i;
                                     
                                    if (bUseIcon == true)
                                        iIndex = i - 1;

                                    //if (bUseBGColor == true)
                                    //    iIndex = i + 1;
                                    iDataWidth = System.Convert.ToInt32(g.MeasureString(spdDisplay.ActiveSheet.Cells[j, i].Text, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH;
                                    iColWidth = System.Convert.ToInt32(g.MeasureString(spdDisplay.ActiveSheet.Columns[i].Label, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + iSortIndWidth;

                                    if (iColWidth < iDataWidth)
                                        iColWidth = iDataWidth;

                                    if (iColWidth > itemWidth)
                                        itemWidth = iColWidth;

                                    //if (System.Convert.ToInt32(g.MeasureString(spdDisplay.ActiveSheet.Cells[j, i].Text, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + iSortIndWidth > itemWidth)
                                    //    itemWidth = System.Convert.ToInt32(g.MeasureString(spdDisplay.ActiveSheet.Cells[j, i].Text, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + iSortIndWidth;

                                    ////compare with column header text
                                    //if (System.Convert.ToInt32(g.MeasureString(dt.Columns[iFirstIndex + iIndex].ColumnName, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + iSortIndWidth > itemWidth)
                                    //    itemWidth = System.Convert.ToInt32(g.MeasureString(dt.Columns[iFirstIndex + iIndex].ColumnName, spdDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + iSortIndWidth;

                                }
                            spdDisplay.ActiveSheet.Columns[i].Width = (int)itemWidth;

                            //Vertical Alignment to Center
                            spdDisplay.ActiveSheet.Columns[i].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                        }

                        g.Dispose();
                    }

                    // Add Auto Sort Option to Spread
                    if (bAutoSort == true)
                    {
                        for (i = 0; i < spdDisplay.ActiveSheet.ColumnCount; i++)
                        {
                            spdDisplay.ActiveSheet.Columns[i].AllowAutoSort = true;
                            //sheetX.Columns[i].SortIndicator = FarPoint.Win.Spread.Model.SortIndicator.None;
                            //sheetX.Columns[i].ShowSortIndicator = false;
                            //sheetX.SetColumnShowSortIndicator(i, false);
                            spdDisplay.ActiveSheet.Columns[i].Width += 15;
                        }
                    }

                    return true;
                }

                //List View Object
                else if (oDisplay is ListView)
                {
                    ListView lisDisplay;
                    lisDisplay = (ListView)oDisplay;

                    //Initialize List View
                    MPCF.InitListView(lisDisplay);
                    lisDisplay.Columns.Clear();

                    if (dt.Rows.Count == 0)
                        return true;

                   

                    //Get Image list from main screen
                    lisDisplay.SmallImageList = MPGV.gIMdiForm.GetSmallIconList();


                    //Get first column index (Icon data column, BackColor data column) 
                    iBGIndex = 0;
                    iFirstIndex = 0;
                    //if (bIcon == true)
                    if (bUseIcon == true)
                        iFirstIndex++;

                    //if (bBGColor == true)
                    if (bUseBGColor == true)
                    {
                        iFirstIndex++;
                        iBGIndex = iFirstIndex - 1;
                    }

                    //Make column header
                    for (i = iFirstIndex; i < dt.Columns.Count; i++)
                    {
                        lisDisplay.Columns.Add(GenCaptionText(dt.Columns[i].ColumnName));
                    }

                    //Display Data, Icon, Background color by each recored
                    foreach (DataRow dr in dt.Rows)
                    {
                        ListViewItem itemX = new ListViewItem();

                        //Display Icon
                        //if (bIcon == true)
                        if (bUseIcon == true)
                            itemX = new ListViewItem(dr[iFirstIndex].ToString(), MPCF.ToInt(gTRSImage.GetInt(dr[0].ToString())));
                        else
                            itemX = new ListViewItem(dr[iFirstIndex].ToString());

                        //Display Background Color for first column
                        //if (bBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                        if (bUseBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                            itemX.BackColor = Color.FromName(dr[iBGIndex].ToString());

                        //Display Background Color from second column
                        for (i = iFirstIndex+1; i < dt.Columns.Count; i++)
                        {
                            string sTemp = dr[iBGIndex].ToString();
                            //if (bBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                            if (bUseBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                                itemX.SubItems.Add(dr[i].ToString(), Color.Black, Color.FromName(dr[iBGIndex].ToString()), null);
                            else
                                itemX.SubItems.Add(dr[i].ToString());
                        }

                        lisDisplay.Items.Add(itemX);
                    }

                    if (bColumnFit)
                    {
                        MPCF.FitColumnHeader(lisDisplay);
                        Graphics g = lisDisplay.CreateGraphics();

                        for (i = 0; i < lisDisplay.Columns.Count; i++)
                        {
                            itemWidth = 0;
                            for (int j = 0; j < lisDisplay.Items.Count; j++)
                            {
                                iIndex = i;

                                if (i == 0)
                                    iDataWidth = System.Convert.ToInt32(g.MeasureString(lisDisplay.Items[j].SubItems[i].Text, lisDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + lisDisplay.SmallImageList.ImageSize.Width;
                                else
                                    iDataWidth = System.Convert.ToInt32(g.MeasureString(lisDisplay.Items[j].SubItems[i].Text, lisDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH;
                                iColWidth = System.Convert.ToInt32(g.MeasureString(lisDisplay.Columns[i].Text, lisDisplay.Font).Width) + MPGC.LV_BONUS_COLUMN_WIDTH + MPGC.LV_BONUS_COLUMN_WIDTH_WITH_IMAGE;

                                if (iColWidth < iDataWidth)
                                    iColWidth = iDataWidth;

                                if (iColWidth > itemWidth)
                                    itemWidth = iColWidth;
                            }

                            lisDisplay.Columns[i].Width = (int)itemWidth + MPGC.LV_BONUS_COLUMN_WIDTH_WITH_IMAGE;
                        }

                        g.Dispose();
                    }
                    //Remove Icon and Background Color data column
                    //lisDisplay.Columns[0].Text = lisDisplay.Columns[iFirstIndex].Text;
                    //for (i = iFirstIndex; i > 0; i--)
                    //    lisDisplay.Columns.Remove(lisDisplay.Columns[i]);

                }

                return true;
            }
            catch (Exception ex)
            {
                MPCF.ShowMsgBox(ex.Message);
                return false;
            }


        }

        public static string GenCaptionText(string sOrgText)
        {
            int j;
            int iTotal;
            string sTemp = string.Empty;
            string sTarget = string.Empty;

            bool bSpace;

            try
            {
                if (MPCF.Trim(sOrgText) == "")
                    return " ";

                sTemp = MPCF.Trim(sOrgText);
                sTemp = sTemp.Replace("_", " ");
                sTemp = MPCF.ToLower(sTemp);

                iTotal = sTemp.Length;

                sTarget = MPCF.ToUpper(sTemp.Substring(0, 1));
                bSpace = false;

                for (j = 1; j < iTotal; j++)
                {
                    if (sTemp.Substring(j, 1) == " ")
                    {
                        sTarget = sTarget + " ";
                        bSpace = true;
                        continue;
                    }

                    if (bSpace == true)
                    {
                        sTarget = sTarget + MPCF.ToUpper(sTemp.Substring(j, 1));
                        bSpace = false;
                    }
                    else
                        sTarget = sTarget + sTemp.Substring(j, 1);
                }
                sTarget = sTarget.Replace(" Id ", " ID ");
                if (sTarget.Length > 3)
                {
                    if (sTarget.Substring(sTarget.Length - 3, 3) == " Id")
                        sTarget = sTarget.Substring(0, sTarget.Length - 3) + " ID";
                }

                sTarget = MPCF.FindLanguage(sTarget, CAPTION_TYPE.LABEL);

                return sTarget;
            }
            catch (Exception ex)
            {
                MPCF.ShowMsgBox(ex.Message);
                return sTarget;
            }
        }

        private static string SetParamType(object sParamValue)
        {
            string sTypeName;

            sTypeName = sParamValue.GetType().Name;

            if (sTypeName == "Int16" || sTypeName == "Int32" || sTypeName == "Int64")
                return "INT";
            else if (sTypeName == "Double")
                return "DOUBLE";
            else if (sTypeName == "Single")
                return "FLOAT";
            else if (sTypeName == "Char")
                return "STRING";
            else if (sTypeName == "Table")
                return "TABLE";
            else
                return "STRING";
        }

        public static bool GetDataOne(string QueryStatement, ref DataTable dt, string ViewID, DirectViewCond[] Cond, bool bIcon, bool bBGColor)
        {
            string sTemp = string.Empty;
            return GetDataOne(QueryStatement, ref dt, ViewID, Cond, bIcon, bBGColor, ref sTemp);
        }
        public static bool GetDataOne(string QueryStatement, ref DataTable dt, string ViewID, DirectViewCond[] Cond, bool bIcon, bool bBGColor, ref string sSql)
        {
            TPDR.initImage();
            string channel = "/" + MPGV.gsSiteID + "/RPTServer";
            return GetDataOne(QueryStatement, channel, ref dt, ViewID, Cond, bIcon, bBGColor, ref sSql);
        }
        public static bool GetDataOne(string QueryStatement, string channel, ref DataTable dt, string ViewID, DirectViewCond[] Cond, bool bIcon, bool bBGColor)
        {
            string sTemp = string.Empty;
            return GetDataOne(QueryStatement, channel, ref dt, ViewID, Cond, bIcon, bBGColor, ref sTemp);
        }
        public static bool GetDataOne(string QueryStatement, string channel, ref DataTable dt, string ViewID, DirectViewCond[] Cond, bool bIcon, bool bBGColor, ref string sSql)
        {
            RPT_SQL_Query_In_Tag _In = new RPT_SQL_Query_In_Tag();
            RPT_SQL_Query_DataTable_Result_Out_Tag _Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();
            dt = null;
            DataTable dt2 = null;
            byte[] BinaryData = null;
            byte[] BinaryDataZip = null;
            int i = 0;
            string sQueryStatement = string.Empty;


            string[] str = new string[1];
            string s_tmp = "";


            try
            {
                //dt.
                //////if (RPTV.gbConnected == false)
                //////{
                //////    if (RPTH101.Init() == false)
                //////    {
                //////        RPTV.gbConnected = false;
                //////        MessageBox.Show("You have been disconnected from the MES server. Connect again");
                //////        return null;
                //////    }
                //////}

                if (MPCF.Trim(channel) == "")
                    channel = "/" + MPGV.gsSiteID + "/RPTServer";

                
                if (TPDR.giMaxDataConut > 0)
                {
                    _In.data_1 = TPDR.giMaxDataConut.ToString();
                }
                else
                {
                    _In.data_1 = TPDR.DEFAULT_MAX_DATA_COUNT.ToString();
                }
                _In.view_id = ViewID;
                _In.user_id = MPGV.gsUserID;
                //_In.user_id = "ADMIN";
                _In.h_factory = MPGV.gsFactory;
                //ICON, BGCOLOR FLAG 추가
                if (bIcon == true)
                {
                    _In.icon_flag = 'Y';
                }
                else
                {
                    _In.icon_flag = 'N';
                }

                if (bBGColor == true)
                {
                    _In.bgcolor_flag = 'Y';
                }
                else
                {
                    _In.bgcolor_flag = 'N';
                }
                

                if (Cond != null)
                {
                    _In._size_cond_tbl = Cond.Length;
                    _In.cond_tbl = new RPT_SQL_Query_In_Tag_cond_tbl[_In._size_cond_tbl];
                    
                    for (i = 0; i < Cond.Length; i++)
                    {
                        _In.cond_tbl[i] = new RPT_SQL_Query_In_Tag_cond_tbl();
                        _In.cond_tbl[i].cond_id = Cond[i].sCondtion_ID;

                        if (Cond[i].sCondition_Type == "TABLE")
                        {
                            _In.cond_tbl[i].cond_type = Cond[i].sCondition_Type;
                            _In.cond_tbl[i].cond = Cond[i].sCondition_Value.ToString();
                        }
                        else if (Cond[i].sCondition_Type == "" || Cond[i].sCondition_Type == null)
                        {
                            s_tmp = SetParamType(Cond[i].sCondition_Value);
                            _In.cond_tbl[i].cond_type = s_tmp;
                            if (s_tmp == "STRING")
                                _In.cond_tbl[i].cond = Cond[i].sCondition_Value.ToString();
                            else if (s_tmp == "INT")
                                _In.cond_tbl[i].cond_int = MPCF.ToInt(Cond[i].iCondition_Value);
                            else if (s_tmp == "DOUBLE")
                                _In.cond_tbl[i].cond_dbl = MPCF.ToDbl(Cond[i].dCondition_Value);
                            else
                                _In.cond_tbl[i].cond_float = Convert.ToSingle(Cond[i].fCondition_Value);
                        }
                        else if (Cond[i].sCondition_Type == "TEXT")
                        {
                            _In.cond_tbl[i].cond_type = Cond[i].sCondition_Type;
                            _In.cond_tbl[i].cond = Cond[i].sCondition_Value.ToString();
                            _In.cond_tbl[i].cond_int = Cond[i].iCondition_Value;
                            _In.cond_tbl[i].cond_dbl = Cond[i].dCondition_Value;
                            _In.cond_tbl[i].cond_float = Cond[i].fCondition_Value;
                        }
                    }
                }

                if (TPDRCaster.RPT_View_Dynamic(_In, ref _Out, channel) == false)
                {
                    //RPTV.gbConnected = false;
                    // Report 서버 죽었을때, 메세지 added by BS CHO 2010.11.15
                    if (MPMH.StatusMessage == "Invalid Channel")
                        throw new Exception("You can't select Report Data. Because Report Server has some Problem. \n Please Contact to MES System Manager.");
                    else
                        throw new Exception(MPMH.StatusMessage);
                }
 
                //if (MPGV.gsQueryStatementLOGCount >= 30)
                //{
                //    str[0] = "------------------------------------------------------------------------------------------------------";
                //    tmp = MPGV.gsQueryStatementLOG.Split(str, StringSplitOptions.None);

                //    MPGV.gsQueryStatementLOG = "";
                //    for (int k = 2; k < tmp.Length; k++)
                //    {
                //        MPGV.gsQueryStatementLOG += "------------------------------------------------------------------------------------------------------" + tmp[k];
                //    }

                //    MPGV.gsQueryStatementLOG = MPGV.gsQueryStatementLOG + GetSeparatorString(ViewID) + _Out.s_sql_data + "\n\n\n"; // 다중 Query문 저장
                //    MPGV.gsQueryStatementLOGCount = 30;
                //}
                //else
                //{
                //    MPGV.gsQueryStatementLOG = MPGV.gsQueryStatementLOG + GetSeparatorString(ViewID) + _Out.s_sql_data + "\n\n\n"; // 다중 Query문 저장
                //    MPGV.gsQueryStatementLOGCount++;
                //}

                sSql = _Out.s_sql_data;
                for (i = 0; i < Cond.Length; i++)
                {
                    if (Cond[i].sCondition_Type == "TABLE")
                    {
                        sSql = sSql.Replace(":" + _In.cond_tbl[i].cond_id, _In.cond_tbl[i].cond);
                    }
                    else if (Cond[i].sCondition_Type == "" || Cond[i].sCondition_Type == null)
                    {
                        s_tmp = SetParamType(Cond[i].sCondition_Value);
                        if (s_tmp == "STRING")
                            sSql = sSql.Replace(":" + _In.cond_tbl[i].cond_id, "'" + _In.cond_tbl[i].cond + "'");
                        else
                            sSql = sSql.Replace(":" + _In.cond_tbl[i].cond_id, Cond[i].sCondition_Value.ToString());
                    }
                    else
                    {
                        sSql = sSql.Replace(":" + _In.cond_tbl[i].cond_id, "'" + _In.cond_tbl[i].cond + "'");
                    }
                }

                //icon, bgcolor flag값 변경
                if (_Out.icon_flag == 'Y')
                {
                    bUseIcon = true;
                }
                else
                {
                    bUseIcon = false;
                }

                if (_Out.bgcolor_flag == 'Y')
                {
                    bUseBGColor = true;
                }
                else
                {
                    bUseBGColor = false;
                }

                if (_Out.h_status_value != '0')
                {
                    if (string.IsNullOrEmpty(MPCF.Trim(_Out.h_db_err_msg)))
                    {
                        MPCF.ShowMsgBox(_Out.h_msg);
                    }
                    else
                    {
                        // 2011-11-03 일 변경
                        // 내용 : Transaction(Insert, Delete, Update) 시 영향받는 Row가 0 일때 "SQL_NOT_FOUND" Message 창 Show
                        //        임시로 제거 했음.
                        ////////////////////////////////////////////////////////
                        // 기존 Code===========================================>
                        //MessageBox.Show(_Out.h_db_err_msg);
                        // ====================================================>

                        // 변경 Code===========================================>
                        if (_Out.h_db_err_msg != "SQL_NOT_FOUND")
                        {
                            MPCF.ShowMsgBox(_Out.h_db_err_msg);
                        }
                        // ====================================================>
                    }
                    return false;
                }
                BinaryDataZip = new byte[_Out.data_count];
                for (i = 0; i < _Out.data_count; i++)
                {
                    BinaryDataZip[i] = (byte)_Out.data_tbl[i].data;
                }

                DataDecompress(BinaryDataZip, ref BinaryData, _Out.binary_length);

                if (deserializeFromBinary(BinaryData, ref dt) == false)
                    return false;
                GC.Collect();
                GC.GetTotalMemory(true);
                if (dt == null || dt.Rows.Count <= 0) return false;
                #region " Next Row "
                if (_Out.next_row > 0)
                {
                    // Next row 적용 : 데이터가 10000건 이상인 경우 10000건씩 끊어서 가져옴.
                    // 데이터가 너무 많은 경우 OutOfMemory에러로 인해 데이터를 가져올 수 없음*.
                    dt2 = null;
                    _In.next_row = _Out.next_row;
                    do
                    {
                        if (BinaryData != null) { BinaryData.Initialize(); BinaryData = null; }
                        if (BinaryDataZip != null) { BinaryDataZip.Initialize(); BinaryDataZip = null; }
                        _Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();
                        if (TPDRCaster.RPT_SQL_Query_DataTable_Result(_In, ref _Out, channel) == false)
                        { 
                            MPCF.ShowMsgBox(MPMH.StatusMessage);
                            return false;
                        }
                        //2011.02.22 Blocked by BSCHO, 만건이상 조회시 에러 발생되는것 막음
                        //if (_Out.h_status_value != '0')
                        //{
                        //    MessageBox.Show(_Out.h_msg);
                        //    return null;
                        //}
                        BinaryDataZip = new byte[_Out.data_count];
                        for (i = 0; i < _Out.data_count; i++)
                        {
                            BinaryDataZip[i] = (byte)_Out.data_tbl[i].data;
                        }

                        DataDecompress(BinaryDataZip, ref BinaryData, _Out.binary_length);

                        if (deserializeFromBinary(BinaryData, ref dt2) == false)
                        {
                            return false;
                        }
                        GC.Collect();
                        GC.GetTotalMemory(true);
                        foreach (DataRow dr in dt2.Rows)
                        {
                            dt.Rows.Add(dr.ItemArray);
                        }
                        _In.next_row = _Out.next_row;
                        if (dt2 != null) { dt2.Clear(); dt2.Dispose(); dt2 = null; }
                    } while (_Out.next_row > 0);
                }

                _Out.data_tbl = null;
                _Out = null;
                GC.Collect();
                GC.GetTotalMemory(true);
                return true;
                #endregion
            }
            catch (Exception ex)
            {
                _Out.data_tbl = null;
                _Out = null;
                GC.Collect();
                GC.GetTotalMemory(true);
                throw ex;
                //return false;
            }
            finally
            {
                if (BinaryData != null) { BinaryData.Initialize(); BinaryData = null; }
                if (BinaryDataZip != null) { BinaryDataZip.Initialize(); BinaryDataZip = null; }
                if (dt2 != null) { dt2.Dispose(); dt2 = null; }
                TPDR.giMaxDataConut = TPDR.DEFAULT_MAX_DATA_COUNT;
                GC.Collect();
                GC.GetTotalMemory(true);
            }

        }

        public static string GetSeparatorString(string queryID)
        {
            string results = Environment.NewLine + Environment.NewLine
                + "------------------------------------------------------------------------------------------------------\r\n";

            if (!String.IsNullOrEmpty(queryID))
            {
                results += String.Format("/* {0} */\r\n", queryID);
                results += "----------------------------------------------------------------------------------------------------";
            }

            return results + Environment.NewLine + Environment.NewLine;
        }

        //
        // DirectView()
        //       - Get Direct View Result
        // Return Value
        //       - true/false
        // Arguments
        //        - string ViewID                : View ID
        //        - params string[] Cond         : Condition List   $C_X   ex) $C_1, $C_2, $C_3,......
        public static bool DirectView(Control oDisplay, string ViewID, ref DataTable dt)
        {
            return DirectView(oDisplay, ViewID, ref dt, false, false, true, null);
        }
        public static bool DirectView(Control oDisplay, string ViewID, ref DataTable dt,bool bColumnFit)
        {
            return DirectView(oDisplay, ViewID, ref dt, false, false, bColumnFit, null);
        }
        public static bool DirectView(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor)
        {
            return DirectView(oDisplay, ViewID,  ref dt, bIcon, bBGColor, true, null);
        }
        public static bool DirectView(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor, params string[] Cond)
        {
            return DirectView(oDisplay, ViewID, ref dt, bIcon, bBGColor, true, Cond);
        }
        public static bool DirectView(Control oDisplay, string ViewID, ref DataTable dt, bool bIcon, bool bBGColor,bool bColumnFit, params string[] Cond)
        {
            //TRSNode in_node;
            //TRSNode out_node;

            DataTable dt2 = new DataTable();

            int i;
            int iBGIndex;
            int iFirstIndex;
            float icolwidth;
            //float iSortIndSize;

            string s_column="";
            string s_sql="";
            string s_replace="";
            string sColor;

            bool bUserHeader = false;

            try
            {
                s_sql = "SELECT W.VIEW_ID,W.COL_NAME, DECODE(W.DISPLAY_NAME,' ', W.COL_NAME, W.DISPLAY_NAME), W.COL_DESC, TO_CHAR(NVL(U.COL_SEQ,99999)), ";
                s_sql = s_sql + " V.SQL_1, V.SQL_2, V.SQL_3, V.SQL_4, V.SQL_5, V.SQL_6, V.SQL_7, V.SQL_8, V.SQL_9, V.SQL_10 ";
                s_sql = s_sql + " FROM MTAPDVWHDR W, MTAPDVUHDR U, MTAPSQLDEF V ";
                s_sql = s_sql + " WHERE 1=1 ";
                s_sql = s_sql + " AND W.VIEW_ID=U.VIEW_ID(+) ";
                s_sql = s_sql + " AND W.COL_NAME = U.COL_NAME(+) ";
                s_sql = s_sql + " AND W.VIEW_ID='"+ViewID+"'";
                s_sql = s_sql + " AND U.VIEW_ID(+)='"+ViewID+"' ";
                s_sql = s_sql + " AND U.FACTORY(+)='"+MPGV.gsFactory+"' ";
                s_sql = s_sql + " AND U.USER_ID(+)='"+MPGV.gsUserID+"' ";
                s_sql = s_sql + " AND V.VIEW_ID='" + ViewID + "' ";
                s_sql = s_sql + " ORDER BY U.COL_SEQ ";

                 if (GetData(s_sql, ref dt2) == false)
                 {
                     dt2.Dispose();
                    return false;
                 }

                if (dt2.Rows[0].ItemArray[4].ToString() != "99999")
                    bUserHeader = true;
                else
                    bUserHeader = false;
                s_column = "SELECT";
                for (i = 0; i < dt2.Rows.Count; i++)
                {
                    if (bUserHeader == true && dt2.Rows[i].ItemArray[4].ToString() == "99999")
                        continue;

                    s_column = s_column + " " + dt2.Rows[i].ItemArray[1].ToString() + " ";
                    s_column = s_column + "\"" + dt2.Rows[i].ItemArray[2].ToString() + "\",";
                }

                s_column = s_column.Substring(0, s_column.Length - 1);
                s_column = s_column + " FROM ( ";

               
                s_sql="";
                s_sql = s_sql + dt2.Rows[0].ItemArray[5].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[6].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[7].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[8].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[9].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[10].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[11].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[12].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[13].ToString();
                s_sql = s_sql + dt2.Rows[0].ItemArray[14].ToString();
                
                if (Cond != null)
                {
                    for (i = 0; i < Cond.Length; i++)
                    {
                        s_replace = "$C_" + i.ToString();
                        s_sql.Replace(s_replace, Cond[i]);
                    }
                }
                s_column = s_column + s_sql;
                s_column = s_column + " )";

                if (GetData(s_column, ref dt) == false)
                    return false;

                
                if (oDisplay is FarPoint.Win.Spread.FpSpread)
                {
                    FarPoint.Win.Spread.FpSpread spdDisplay;
                    spdDisplay = (FarPoint.Win.Spread.FpSpread)oDisplay;
                    spdDisplay.DataSource = dt;

                    
                    if (bIcon == true)
                    {
                        FarPoint.Win.Spread.CellType.ImageCellType imgCellType = new FarPoint.Win.Spread.CellType.ImageCellType();

                        spdDisplay.ActiveSheet.Columns.Add(0, 1);
                        spdDisplay.ActiveSheet.Columns[0].CellType = imgCellType;
                        spdDisplay.ActiveSheet.ColumnHeader.Cells[0, 0].Text = "-";

                        ImageList iTemp = MPGV.gIMdiForm.GetSmallIconList();

                        for (i = 0; i < spdDisplay.ActiveSheet.RowCount; i++)
                        {
                            spdDisplay.ActiveSheet.Cells[i, 0].Value = iTemp.Images[gTRSImage.GetInt(dt.Rows[i].ItemArray.GetValue(0).ToString())];

                            if (bBGColor == true)
                            {
                                sColor = dt.Rows[i].ItemArray.GetValue(1).ToString();
                                if (MPCF.Trim(sColor) != "")
                                    spdDisplay.ActiveSheet.Rows[i].BackColor = Color.FromName(dt.Rows[i].ItemArray.GetValue(1).ToString());
                            }
                        }
                        
                    }
                    else if (bBGColor == true)
                    {
                        sColor = dt.Rows[i].ItemArray.GetValue(0).ToString();
                        if (MPCF.Trim(sColor) != "")
                            spdDisplay.ActiveSheet.Rows[i].BackColor = Color.FromName(dt.Rows[i].ItemArray.GetValue(0).ToString());
                    }

                    if (bIcon == true)
                        spdDisplay.ActiveSheet.Columns[1].Remove();
                    if (bBGColor == true)
                        spdDisplay.ActiveSheet.Columns[1].Remove();

                    if (bColumnFit == true)
                    {
                        for (i = 0; i < spdDisplay.ActiveSheet.ColumnCount; i++)
                        {
                            icolwidth = spdDisplay.ActiveSheet.GetPreferredColumnWidth(i, false, false, false);
                            spdDisplay.ActiveSheet.Columns[i].Width = icolwidth;
                            spdDisplay.ActiveSheet.Columns[i].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                        }
                    }


                }
                else if(oDisplay is ListView)
                {
                    ListView lisDisplay;
                    lisDisplay = (ListView)oDisplay;

                    MPCF.InitListView(lisDisplay);
                    lisDisplay.Columns.Clear();

                    if (dt.Rows.Count == 0)
                        return true;

                    for(i=0;i<dt.Columns.Count;i++)
                    {
                        lisDisplay.Columns.Add(dt.Columns[i].ColumnName);
                    }
                    lisDisplay.SmallImageList = MPGV.gIMdiForm.GetSmallIconList();

                    iBGIndex = 0;
                    iFirstIndex = 0;

                    if (bIcon == true)
                        iFirstIndex++;

                    if (bBGColor == true)
                    {
                        iFirstIndex++;
                        iBGIndex = iFirstIndex - 1;
                    }

                    foreach (DataRow dr in dt.Rows)
                    {
                        ListViewItem itemX = new ListViewItem();

                        
                        if(bIcon==true)
                        {
                            itemX = new ListViewItem(dr[iFirstIndex].ToString(), MPCF.ToInt(gTRSImage.GetInt(dr[0].ToString())));
                        }
                        else
                        {
                            itemX = new ListViewItem(dr[iFirstIndex].ToString());
                        }

                        if (bBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                            itemX.BackColor = Color.FromName(dr[iBGIndex].ToString());

                        
                        for (i = 1; i < dt.Columns.Count; i++)
                        {
                            //itemX.SubItems.Add(dr[i].ToString());

                            if (bBGColor == true && MPCF.Trim(dr[iBGIndex].ToString()) != "")
                                itemX.SubItems.Add(dr[i].ToString(), Color.Black, Color.FromName(dr[iBGIndex].ToString()), null);
                            else
                                itemX.SubItems.Add(dr[i].ToString());
                        }
                        lisDisplay.Items.Add(itemX); 
                    }
                    lisDisplay.Columns[0].Text = lisDisplay.Columns[iFirstIndex].Text;

                    
                    for (i = iFirstIndex; i > 0; i--)
                        lisDisplay.Columns.Remove(lisDisplay.Columns[i]);

                    if (bColumnFit == true)
                    {
                        MPCF.FitColumnHeader(lisDisplay);
                    }
                }    
                


                return true;
            }
            catch (Exception ex)
            {
                MPCF.ShowMsgBox(ex.Message);
                return false;
            }

            
        }
        public static bool GetData(string QueryStatement, ref DataTable dt)
        {
            string channel = "/" + MPGV.gsSiteID + "/RPTServer";
            return GetData(QueryStatement, channel, ref dt);
        }
        public static bool GetData(string QueryStatement, string channel,ref DataTable dt)
        {
            RPT_SQL_Query_In_Tag _In = new RPT_SQL_Query_In_Tag();
            RPT_SQL_Query_DataTable_Result_Out_Tag _Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();
            dt = null;
            DataTable dt2 = null;
            byte[] BinaryData = null;
            byte[] BinaryDataZip = null;
            int i = 0;
            string sQueryStatement = string.Empty;
            try
            {
                //dt.
                //////if (RPTV.gbConnected == false)
                //////{
                //////    if (RPTH101.Init() == false)
                //////    {
                //////        RPTV.gbConnected = false;
                //////        MessageBox.Show("You have been disconnected from the MES server. Connect again");
                //////        return null;
                //////    }
                //////}

                if (MPCF.Trim(channel) == "")
                    channel = "/" + MPGV.gsSiteID + "/RPTServer";

                sQueryStatement = MPCF.Trim(QueryStatement);
                if (string.IsNullOrEmpty(sQueryStatement)) return false;

                _In.sql = QueryStatement;
                if (TPDR.giMaxDataConut > 0)
                {
                    _In.data_1 = TPDR.giMaxDataConut.ToString();
                }
                else
                {
                    _In.data_1 = TPDR.DEFAULT_MAX_DATA_COUNT.ToString();
                }
                if (TPDRCaster.RPT_SQL_Query_DataTable_Result(_In, ref _Out, channel) == false)
                {
                    //RPTV.gbConnected = false;
                    // Report 서버 죽었을때, 메세지 added by BS CHO 2010.11.15
                    if (MPMH.StatusMessage == "Invalid Channel")
                        throw new Exception("You can't select Report Data. Because Report Server has some Problem. \n Please Contact to MES System Manager.");
                    else
                        throw new Exception(MPMH.StatusMessage);
                }
                if (_Out.h_status_value != '0')
                {
                    if (string.IsNullOrEmpty(MPCF.Trim(_Out.h_db_err_msg)))
                    {
                        MPCF.ShowMsgBox(_Out.h_msg);
                    }
                    else
                    {
                        // 2011-11-03 일 변경
                        // 내용 : Transaction(Insert, Delete, Update) 시 영향받는 Row가 0 일때 "SQL_NOT_FOUND" Message 창 Show
                        //        임시로 제거 했음.
                        ////////////////////////////////////////////////////////
                        // 기존 Code===========================================>
                        //MessageBox.Show(_Out.h_db_err_msg);
                        // ====================================================>

                        // 변경 Code===========================================>
                        if (_Out.h_db_err_msg != "SQL_NOT_FOUND")
                        {
                            MPCF.ShowMsgBox(_Out.h_db_err_msg);
                        }
                        // ====================================================>
                    }
                    return false;
                }
                BinaryDataZip = new byte[_Out.data_count];
                for (i = 0; i < _Out.data_count; i++)
                {
                    BinaryDataZip[i] = (byte)_Out.data_tbl[i].data;
                }

                DataDecompress(BinaryDataZip, ref BinaryData, _Out.binary_length);

                if(deserializeFromBinary(BinaryData, ref dt)==false)
                    return false;
                GC.Collect();
                GC.GetTotalMemory(true);
                if (dt == null || dt.Rows.Count <= 0) return false;
                #region " Next Row "
                if (_Out.next_row > 0)
                {
                    // Next row 적용 : 데이터가 10000건 이상인 경우 10000건씩 끊어서 가져옴.
                    // 데이터가 너무 많은 경우 OutOfMemory에러로 인해 데이터를 가져올 수 없음*.
                    dt2 = null;
                    _In.next_row = _Out.next_row;
                    do
                    {
                        if (BinaryData != null) { BinaryData.Initialize(); BinaryData = null; }
                        if (BinaryDataZip != null) { BinaryDataZip.Initialize(); BinaryDataZip = null; }
                        _Out = new RPT_SQL_Query_DataTable_Result_Out_Tag();
                        if (TPDRCaster.RPT_SQL_Query_DataTable_Result(_In, ref _Out,channel) == false)
                        {
                            MPCF.ShowMsgBox(MPMH.StatusMessage);
                            return false;
                        }
                        //2011.02.22 Blocked by BSCHO, 만건이상 조회시 에러 발생되는것 막음
                        //if (_Out.h_status_value != '0')
                        //{
                        //    MessageBox.Show(_Out.h_msg);
                        //    return null;
                        //}
                        BinaryDataZip = new byte[_Out.data_count];
                        for (i = 0; i < _Out.data_count; i++)
                        {
                            BinaryDataZip[i] = (byte)_Out.data_tbl[i].data;
                        }

                        DataDecompress(BinaryDataZip, ref BinaryData, _Out.binary_length);

                        if (deserializeFromBinary(BinaryData, ref dt2) == false)
                        {
                            return false;
                        }
                        GC.Collect();
                        GC.GetTotalMemory(true);
                        foreach (DataRow dr in dt2.Rows)
                        {
                            dt.Rows.Add(dr.ItemArray);
                        }
                        _In.next_row = _Out.next_row;
                        if (dt2 != null) { dt2.Clear();  dt2.Dispose(); dt2 = null; }
                    } while (_Out.next_row > 0);
                }
                _Out.data_tbl = null;
                _Out = null;
                GC.Collect();
                GC.GetTotalMemory(true);
                return true;
                #endregion
            }
            catch (Exception ex)
            {
                _Out.data_tbl = null;
                _Out = null;
                GC.Collect();
                GC.GetTotalMemory(true);
                throw ex;
                //return false;
            }
            finally
            {


                if (BinaryData != null) { BinaryData.Initialize(); BinaryData = null; }
                if (BinaryDataZip != null) { BinaryDataZip.Initialize(); BinaryDataZip = null; }
                if (dt2 != null) { dt2.Dispose(); dt2 = null; }
                TPDR.giMaxDataConut = TPDR.DEFAULT_MAX_DATA_COUNT;
                GC.Collect();
                GC.GetTotalMemory(true);
            }
            
        }
        public static void SetDirectViewCondition(string sViewID, Object oTemp)
        {
            TRSNode in_node = new TRSNode("VIEW_DIRECT_VIEW_CONDITION_LIST_IN");
            TRSNode out_node = new TRSNode("VIEW_DIRECT_VIEW_CONDITION_LIST_OUT");
            int i;
            int iRow=0;
            FarPoint.Win.Spread.FpSpread spdCondition;

            try
            {
                spdCondition = (FarPoint.Win.Spread.FpSpread)oTemp;
                spdCondition.Sheets[0].RowHeader.ColumnCount = 0;
                spdCondition.Sheets[0].RowCount = 0;
                spdCondition.Sheets[0].ColumnCount = 0;
                spdCondition.Sheets[0].ColumnHeader.Columns.Count = 0;
                spdCondition.Sheets[0].ColumnHeader.RowCount = 0;
                spdCondition.Sheets[0].ColumnHeader.Columns.Count=6;
                spdCondition.Sheets[0].ColumnHeader.RowCount = 1;
                
                spdCondition.Sheets[0].ColumnHeader.Cells[0, 0].Text = "Condition";
                spdCondition.Sheets[0].ColumnHeader.Cells[0, 1].Text = "Value";
                spdCondition.Sheets[0].ColumnHeader.Cells[0, 1].ColumnSpan = 2;

                spdCondition.Sheets[0].ColumnHeader.Cells[0, 3].Text = "Condition";
                spdCondition.Sheets[0].ColumnHeader.Cells[0, 4].Text = "Value";
                spdCondition.Sheets[0].ColumnHeader.Cells[0, 4].ColumnSpan = 2;

                spdCondition.Sheets[0].Columns[0].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                spdCondition.Sheets[0].Columns[1].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                spdCondition.Sheets[0].Columns[2].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                spdCondition.Sheets[0].Columns[3].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                spdCondition.Sheets[0].Columns[4].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
                spdCondition.Sheets[0].Columns[5].VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;


                MPCR.SetInMsg(in_node);
                in_node.ProcStep = '1';
                in_node.SetString("VIEW_ID", sViewID);

                Font ff = new Font("맑은 고딕", 8);

                do
                {

                    if (MPCR.CallService("TAP", "TAP_View_Direct_View_Condition_List", in_node, ref out_node) == false)
                    {
                        return;
                    }

                    for (i = 0; i < out_node.GetList("LIST").Count; i++)
                    {

                        iRow = (i) / 2;

                        if ((i+1) % 2 == 1)
                        {
                            spdCondition.Sheets[0].RowCount++;



                            if (out_node.GetList("LIST")[i].GetChar("REQ_FLAG") == 'Y')
                                spdCondition.Sheets[0].Cells[iRow, 0].Font = new Font(ff, FontStyle.Bold); ;

                            spdCondition.Sheets[0].Cells[iRow, 0].Text = "  " + out_node.GetList("LIST")[i].GetString("COND_DESC");
                            spdCondition.Sheets[0].Cells[iRow, 0].Tag = out_node.GetList("LIST")[i].GetString("COND_NAME");
                            spdCondition.Sheets[0].Cells[iRow, 0].BackColor = SystemColors.Control;
                            spdCondition.Sheets[0].Cells[iRow, 1].Tag = out_node.GetList("LIST")[i].GetString("DATA_TYPE");
                            if (out_node.GetList("LIST")[iRow].GetString("INPUT_TYPE") == "TextBox")
                            {
                                spdCondition.Sheets[0].Cells[iRow, 1].ColumnSpan = 2;
                                spdCondition.Sheets[0].Cells[iRow, 1].Column.Width = 200;
                            }
                            else
                            {
                                spdCondition.Sheets[0].Cells[iRow, 1].Column.Width = 200;
                                spdCondition.Sheets[0].Cells[iRow, 2].Tag = out_node.GetList("LIST")[i].GetString("DATA_TBL");
                                FarPoint.Win.Spread.CellType.ButtonCellType btn = new FarPoint.Win.Spread.CellType.ButtonCellType();
                                btn.Text = "...";
                                spdCondition.Sheets[0].Cells[iRow, 2].CellType = btn;
                                spdCondition.Sheets[0].Cells[iRow, 2].Column.Width = 20;
                            }

                            if (i == out_node.GetList("LIST").Count - 1)
                            {
                                spdCondition.Sheets[0].Cells[iRow, 3].ColumnSpan = 3;
                                spdCondition.Sheets[0].Cells[iRow, 3].BackColor = Color.DarkGray;
                            }
                        }
                        else
                        {
                            if (out_node.GetList("LIST")[i].GetChar("REQ_FLAG") == 'Y')
                                spdCondition.Sheets[0].Cells[iRow, 3].Font = new Font(frmAbout.DefaultFont, FontStyle.Bold); ;

                            spdCondition.Sheets[0].Cells[iRow, 3].Text = "  " + out_node.GetList("LIST")[i].GetString("COND_DESC");
                            spdCondition.Sheets[0].Cells[iRow, 3].Tag = out_node.GetList("LIST")[i].GetString("COND_NAME");
                            spdCondition.Sheets[0].Cells[iRow, 3].BackColor = SystemColors.Control;

                            spdCondition.Sheets[0].Cells[iRow, 4].Tag = out_node.GetList("LIST")[i].GetString("DATA_TYPE");
                            if (out_node.GetList("LIST")[i].GetString("INPUT_TYPE") == "TextBox")
                            {
                                spdCondition.Sheets[0].Cells[iRow, 4].Column.Width = 200;
                                spdCondition.Sheets[0].Cells[iRow, 4].ColumnSpan = 2;
                            }
                            else
                            {
                                spdCondition.Sheets[0].Cells[iRow, 4].Column.Width = 200;
                                spdCondition.Sheets[0].Cells[iRow, 5].Tag = out_node.GetList("LIST")[i].GetString("DATA_TBL");
                                FarPoint.Win.Spread.CellType.ButtonCellType btn = new FarPoint.Win.Spread.CellType.ButtonCellType();
                                btn.Text = "...";
                                spdCondition.Sheets[0].Cells[iRow, 5].CellType = btn;
                                spdCondition.Sheets[0].Cells[iRow, 5].Column.Width = 20;
                            }
                        }

                    }

                    in_node.SetInt("NEXT_COND_SEQ", out_node.GetInt("NEXT_COND_SEQ"));

                } while (in_node.GetInt("NEXT_COND_SEQ") != 0);


                return;
            }
            catch (Exception ex)
            {
                MPCF.ShowMsgBox(ex.Message);
                return;
            }
        }
    }
}