namespace BOI.WIPCus.Controls
{
    partial class BOIOrderInfo
    {
        /// <summary> 
        /// 필수 디자이너 변수입니다.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 사용 중인 모든 리소스를 정리합니다.
        /// </summary>
        /// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 구성 요소 디자이너에서 생성한 코드

        /// <summary> 
        /// 디자이너 지원에 필요한 메서드입니다. 
        /// 이 메서드의 내용을 코드 편집기로 수정하지 마십시오.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Infragistics.Win.Appearance appearance23 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance24 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance22 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance2 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance3 = new Infragistics.Win.Appearance();
            Infragistics.Win.Appearance appearance4 = new Infragistics.Win.Appearance();
            FarPoint.Win.Spread.EnhancedScrollBarRenderer enhancedScrollBarRenderer1 = new FarPoint.Win.Spread.EnhancedScrollBarRenderer();
            FarPoint.Win.Spread.EnhancedScrollBarRenderer enhancedScrollBarRenderer2 = new FarPoint.Win.Spread.EnhancedScrollBarRenderer();
            FarPoint.Win.Spread.CellType.TextCellType textCellType1 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType2 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType3 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType4 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType5 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType6 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType1 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType7 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType8 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType9 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType2 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType10 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType3 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType4 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType5 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType6 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType11 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType12 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType13 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType14 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType15 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType16 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType7 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType17 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType18 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType8 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType19 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType20 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType21 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType22 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType23 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType24 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType9 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType25 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType26 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType10 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType27 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType28 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType29 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType30 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType11 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType12 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType13 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType14 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.NumberCellType numberCellType15 = new FarPoint.Win.Spread.CellType.NumberCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType31 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType32 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType33 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType34 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType35 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType36 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType37 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType38 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType39 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType40 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType41 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType42 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType43 = new FarPoint.Win.Spread.CellType.TextCellType();
            FarPoint.Win.Spread.CellType.TextCellType textCellType44 = new FarPoint.Win.Spread.CellType.TextCellType();
            this.soiGroupBox1 = new SOI.OIFrx.SOIControls.SOIGroupBox(this.components);
            this.soiTableLayoutPanel1 = new SOI.OIFrx.SOIControls.SOITableLayoutPanel(this.components);
            this.btnViewWorkOrder = new SOI.OIFrx.SOIControls.SOIButton(this.components);
            this.spdOrderInfo = new BOI.OIFrx.BOIControls.BOISpread();
            this.spdOrderInfo_Sheet1 = new FarPoint.Win.Spread.SheetView();
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).BeginInit();
            this.soiGroupBox1.SuspendLayout();
            this.soiTableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.spdOrderInfo)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdOrderInfo_Sheet1)).BeginInit();
            this.SuspendLayout();
            // 
            // soiGroupBox1
            // 
            this.soiGroupBox1._UseOITheme = true;
            this.soiGroupBox1._UseStyle = SOI.OIFrx.SOIGroupBoxStyle.DefaultStyle;
            appearance23.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(223)))), ((int)(((byte)(224)))), ((int)(((byte)(228)))));
            appearance23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            this.soiGroupBox1.Appearance = appearance23;
            this.soiGroupBox1.BorderStyle = Infragistics.Win.Misc.GroupBoxBorderStyle.None;
            appearance24.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance24.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.soiGroupBox1.ContentAreaAppearance = appearance24;
            this.soiGroupBox1.Controls.Add(this.soiTableLayoutPanel1);
            this.soiGroupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiGroupBox1.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            appearance22.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            appearance22.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(200)))), ((int)(((byte)(200)))), ((int)(((byte)(200)))));
            appearance22.FontData.BoldAsString = "True";
            appearance22.FontData.SizeInPoints = 14F;
            appearance22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(45)))), ((int)(((byte)(45)))), ((int)(((byte)(45)))));
            appearance22.TextHAlignAsString = "Right";
            this.soiGroupBox1.HeaderAppearance = appearance22;
            this.soiGroupBox1.Location = new System.Drawing.Point(0, 0);
            this.soiGroupBox1.Margin = new System.Windows.Forms.Padding(0);
            this.soiGroupBox1.Name = "soiGroupBox1";
            this.soiGroupBox1.Size = new System.Drawing.Size(800, 145);
            this.soiGroupBox1.TabIndex = 2;
            this.soiGroupBox1.Text = "Order Information";
            this.soiGroupBox1.ViewStyle = Infragistics.Win.Misc.GroupBoxViewStyle.VisualStudio2005;
            // 
            // soiTableLayoutPanel1
            // 
            this.soiTableLayoutPanel1._UseOITheme = true;
            this.soiTableLayoutPanel1.BackColor = System.Drawing.Color.Transparent;
            this.soiTableLayoutPanel1.ColumnCount = 3;
            this.soiTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.soiTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.soiTableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.soiTableLayoutPanel1.Controls.Add(this.btnViewWorkOrder, 2, 0);
            this.soiTableLayoutPanel1.Controls.Add(this.spdOrderInfo, 0, 0);
            this.soiTableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.soiTableLayoutPanel1.Location = new System.Drawing.Point(1, 32);
            this.soiTableLayoutPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.soiTableLayoutPanel1.Name = "soiTableLayoutPanel1";
            this.soiTableLayoutPanel1.RowCount = 1;
            this.soiTableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.soiTableLayoutPanel1.Size = new System.Drawing.Size(798, 112);
            this.soiTableLayoutPanel1.TabIndex = 0;
            // 
            // btnViewWorkOrder
            // 
            this.btnViewWorkOrder._UseOITheme = true;
            this.btnViewWorkOrder._UseStyle = SOI.OIFrx.SOIButtonStyle.DefaultStyle;
            appearance2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance2.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance2.BackColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            appearance2.BackColorDisabled2 = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            appearance2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance2.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance2.FontData.BoldAsString = "True";
            appearance2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            appearance2.ForeColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(160)))), ((int)(((byte)(160)))));
            this.btnViewWorkOrder.Appearance = appearance2;
            this.btnViewWorkOrder.ButtonStyle = Infragistics.Win.UIElementButtonStyle.Office2003ToolbarButton;
            this.btnViewWorkOrder.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnViewWorkOrder.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnViewWorkOrder.Font = new System.Drawing.Font("맑은 고딕", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
            appearance3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance3.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            appearance3.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(117)))), ((int)(((byte)(179)))));
            this.btnViewWorkOrder.HotTrackAppearance = appearance3;
            this.btnViewWorkOrder.Location = new System.Drawing.Point(698, 0);
            this.btnViewWorkOrder.Margin = new System.Windows.Forms.Padding(0);
            this.btnViewWorkOrder.Name = "btnViewWorkOrder";
            appearance4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance4.BackColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            appearance4.BorderColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(43)))), ((int)(((byte)(127)))), ((int)(((byte)(189)))));
            this.btnViewWorkOrder.PressedAppearance = appearance4;
            this.btnViewWorkOrder.ShowFocusRect = false;
            this.btnViewWorkOrder.ShowOutline = false;
            this.btnViewWorkOrder.Size = new System.Drawing.Size(100, 50);
            this.btnViewWorkOrder.TabIndex = 10;
            this.btnViewWorkOrder.Text = "Work Order";
            this.btnViewWorkOrder.UseFlatMode = Infragistics.Win.DefaultableBoolean.True;
            this.btnViewWorkOrder.UseHotTracking = Infragistics.Win.DefaultableBoolean.True;
            this.btnViewWorkOrder.UseOsThemes = Infragistics.Win.DefaultableBoolean.False;
            this.btnViewWorkOrder.Click += new System.EventHandler(this.btnViewWorkOrder_Click);
            // 
            // spdOrderInfo
            // 
            this.spdOrderInfo._UseAutoHeight = false;
            this.spdOrderInfo._UseOITheme = true;
            this.spdOrderInfo.AccessibleDescription = "spdOrderInfo, Sheet1, Row 0, Column 0, ";
            this.spdOrderInfo.AllowUserZoom = false;
            this.spdOrderInfo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdOrderInfo.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.spdOrderInfo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.spdOrderInfo.Font = new System.Drawing.Font("맑은 고딕", 12F);
            this.spdOrderInfo.HorizontalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdOrderInfo.HorizontalScrollBar.Name = "";
            enhancedScrollBarRenderer1.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ArrowHoveredColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ArrowSelectedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer1.ButtonBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer1.ButtonBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer1.ButtonHoveredBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonHoveredBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.ButtonSelectedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer1.TrackBarBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
            enhancedScrollBarRenderer1.TrackBarSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.spdOrderInfo.HorizontalScrollBar.Renderer = enhancedScrollBarRenderer1;
            this.spdOrderInfo.HorizontalScrollBar.TabIndex = 154;
            this.spdOrderInfo.HorizontalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdOrderInfo.Location = new System.Drawing.Point(0, 0);
            this.spdOrderInfo.Margin = new System.Windows.Forms.Padding(0);
            this.spdOrderInfo.Name = "spdOrderInfo";
            this.spdOrderInfo.ScrollBarTrackPolicy = FarPoint.Win.Spread.ScrollBarTrackPolicy.Both;
            this.spdOrderInfo.ScrollTipPolicy = FarPoint.Win.Spread.ScrollTipPolicy.Both;
            this.spdOrderInfo.Sheets.AddRange(new FarPoint.Win.Spread.SheetView[] {
            this.spdOrderInfo_Sheet1});
            this.spdOrderInfo.Size = new System.Drawing.Size(678, 112);
            this.spdOrderInfo.SOICellHeight = 50;
            this.spdOrderInfo.SOIColumnHeight = 30;
            this.spdOrderInfo.TabIndex = 9;
            this.spdOrderInfo.TabStop = false;
            this.spdOrderInfo.TextTipPolicy = FarPoint.Win.Spread.TextTipPolicy.Floating;
            this.spdOrderInfo.UseEnterKeyForMove = true;
            this.spdOrderInfo.UseKeyPad = true;
            this.spdOrderInfo.UseSOIContextMenu = true;
            this.spdOrderInfo.VerticalScrollBar.Buttons = new FarPoint.Win.Spread.FpScrollBarButtonCollection("BackwardLineButton,ThumbTrack,ForwardLineButton");
            this.spdOrderInfo.VerticalScrollBar.Name = "";
            enhancedScrollBarRenderer2.ArrowColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ArrowHoveredColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ArrowSelectedColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            enhancedScrollBarRenderer2.ButtonBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer2.ButtonBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(151)))), ((int)(((byte)(151)))), ((int)(((byte)(151)))));
            enhancedScrollBarRenderer2.ButtonHoveredBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonHoveredBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.ButtonSelectedBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            enhancedScrollBarRenderer2.TrackBarBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(227)))), ((int)(((byte)(227)))), ((int)(((byte)(227)))));
            enhancedScrollBarRenderer2.TrackBarSelectedBackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(141)))), ((int)(((byte)(141)))), ((int)(((byte)(141)))));
            this.spdOrderInfo.VerticalScrollBar.Renderer = enhancedScrollBarRenderer2;
            this.spdOrderInfo.VerticalScrollBar.TabIndex = 155;
            this.spdOrderInfo.VerticalScrollBarPolicy = FarPoint.Win.Spread.ScrollBarPolicy.AsNeeded;
            this.spdOrderInfo.VisualStyles = FarPoint.Win.VisualStyles.Off;
            // 
            // spdOrderInfo_Sheet1
            // 
            this.spdOrderInfo_Sheet1.Reset();
            spdOrderInfo_Sheet1.SheetName = "Sheet1";
            // Formulas and custom names must be loaded with R1C1 reference style
            this.spdOrderInfo_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.R1C1;
            spdOrderInfo_Sheet1.ColumnCount = 59;
            spdOrderInfo_Sheet1.RowCount = 1;
            spdOrderInfo_Sheet1.RowHeader.ColumnCount = 0;
            this.spdOrderInfo_Sheet1.ActiveSkin = FarPoint.Win.Spread.DefaultSkins.Classic1;
            this.spdOrderInfo_Sheet1.ColumnFooter.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.ForeColor = System.Drawing.Color.White;
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.Parent = "HeaderDefault";
            this.spdOrderInfo_Sheet1.ColumnFooter.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnFooter.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(51)))), ((int)(((byte)(51)))));
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.Font = new System.Drawing.Font("굴림", 9F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.ForeColor = System.Drawing.Color.White;
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.Parent = "HeaderDefault";
            this.spdOrderInfo_Sheet1.ColumnFooterSheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 0).Value = "Factory";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 1).Value = "Order ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 2).Value = "Order Desc";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 3).Value = "Order Type";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 4).Value = "Lot ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 5).Value = "Flow";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 6).Value = "Flow Seq Num";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 7).Value = "Oper";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 8).Value = "Res ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 9).Value = "Mat ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 10).Value = "Mat Ver";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 11).Value = "Mat Bom Type";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 12).Value = "Ord Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 13).Value = "Prod Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 14).Value = "Remain Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 15).Value = "Loss Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 16).Value = "Unit";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 17).Value = "Shop Code";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 18).Value = "Line ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 19).Value = "Lot Type";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 20).Value = "Ord Date";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 21).Value = "Plan Date";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 22).Value = "Plan Priority";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 23).Value = "Ord Reg Date";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 24).Value = "Org Plan Date";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 25).Value = "Org Ord Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 26).Value = "Plan Start Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 27).Value = "Plan End Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 28).Value = "Ord Start Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 29).Value = "Ord End Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 30).Value = "Close Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 31).Value = "Label Code";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 32).Value = "Pack Qty";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 33).Value = "Cust ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 34).Value = "Erp So No";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 35).Value = "Erp So Seq";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 36).Value = "Order Status";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 37).Value = "Comment1";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 38).Value = "Comment2";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 39).Value = "Comment3";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 40).Value = "Ord Qty 1";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 41).Value = "Ord Qty 2";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 42).Value = "Ord Qty 3";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 43).Value = "Ord Qty 4";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 44).Value = "Ord Qty 5";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 45).Value = "Ord Cmf 1";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 46).Value = "Ord Cmf 2";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 47).Value = "Ord Cmf 3";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 48).Value = "Ord Cmf 4";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 49).Value = "Ord Cmf 5";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 50).Value = "Ord Cmf 6";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 51).Value = "Ord Cmf 7";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 52).Value = "Ord Cmf 8";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 53).Value = "Ord Cmf 9";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 54).Value = "Ord Cmf 10";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 55).Value = "Create User ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 56).Value = "Create Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 57).Value = "Update User ID";
            this.spdOrderInfo_Sheet1.ColumnHeader.Cells.Get(0, 58).Value = "Update Time";
            this.spdOrderInfo_Sheet1.ColumnHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.Parent = "HeaderDefault";
            this.spdOrderInfo_Sheet1.ColumnHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnHeader.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.ColumnHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.ColumnHeader.Rows.Get(0).Height = 50F;
            this.spdOrderInfo_Sheet1.ColumnHeader.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.Columns.Get(0).CellType = textCellType1;
            this.spdOrderInfo_Sheet1.Columns.Get(0).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(0).Label = "Factory";
            this.spdOrderInfo_Sheet1.Columns.Get(0).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(0).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(0).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(1).CellType = textCellType2;
            this.spdOrderInfo_Sheet1.Columns.Get(1).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(1).Label = "Order ID";
            this.spdOrderInfo_Sheet1.Columns.Get(1).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(1).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(1).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(2).CellType = textCellType3;
            this.spdOrderInfo_Sheet1.Columns.Get(2).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(2).Label = "Order Desc";
            this.spdOrderInfo_Sheet1.Columns.Get(2).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(2).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(2).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(3).CellType = textCellType4;
            this.spdOrderInfo_Sheet1.Columns.Get(3).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(3).Label = "Order Type";
            this.spdOrderInfo_Sheet1.Columns.Get(3).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(3).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(3).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(4).CellType = textCellType5;
            this.spdOrderInfo_Sheet1.Columns.Get(4).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(4).Label = "Lot ID";
            this.spdOrderInfo_Sheet1.Columns.Get(4).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(4).Width = 192F;
            this.spdOrderInfo_Sheet1.Columns.Get(5).CellType = textCellType6;
            this.spdOrderInfo_Sheet1.Columns.Get(5).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(5).Label = "Flow";
            this.spdOrderInfo_Sheet1.Columns.Get(5).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(5).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(5).Width = 100F;
            numberCellType1.DecimalPlaces = 0;
            this.spdOrderInfo_Sheet1.Columns.Get(6).CellType = numberCellType1;
            this.spdOrderInfo_Sheet1.Columns.Get(6).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(6).Label = "Flow Seq Num";
            this.spdOrderInfo_Sheet1.Columns.Get(6).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(6).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(6).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(7).CellType = textCellType7;
            this.spdOrderInfo_Sheet1.Columns.Get(7).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(7).Label = "Oper";
            this.spdOrderInfo_Sheet1.Columns.Get(7).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(7).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(7).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(8).CellType = textCellType8;
            this.spdOrderInfo_Sheet1.Columns.Get(8).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(8).Label = "Res ID";
            this.spdOrderInfo_Sheet1.Columns.Get(8).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(8).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(8).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(9).CellType = textCellType9;
            this.spdOrderInfo_Sheet1.Columns.Get(9).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(9).Label = "Mat ID";
            this.spdOrderInfo_Sheet1.Columns.Get(9).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(9).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(9).Width = 100F;
            numberCellType2.DecimalPlaces = 0;
            this.spdOrderInfo_Sheet1.Columns.Get(10).CellType = numberCellType2;
            this.spdOrderInfo_Sheet1.Columns.Get(10).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(10).Label = "Mat Ver";
            this.spdOrderInfo_Sheet1.Columns.Get(10).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(10).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(10).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(11).CellType = textCellType10;
            this.spdOrderInfo_Sheet1.Columns.Get(11).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(11).Label = "Mat Bom Type";
            this.spdOrderInfo_Sheet1.Columns.Get(11).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(11).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(11).Width = 100F;
            numberCellType3.DecimalPlaces = 2;
            numberCellType3.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(12).CellType = numberCellType3;
            this.spdOrderInfo_Sheet1.Columns.Get(12).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(12).Label = "Ord Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(12).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(12).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(12).Width = 100F;
            numberCellType4.DecimalPlaces = 2;
            numberCellType4.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(13).CellType = numberCellType4;
            this.spdOrderInfo_Sheet1.Columns.Get(13).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(13).Label = "Prod Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(13).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(13).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(13).Width = 100F;
            numberCellType5.DecimalPlaces = 2;
            numberCellType5.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(14).CellType = numberCellType5;
            this.spdOrderInfo_Sheet1.Columns.Get(14).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(14).Label = "Remain Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(14).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(14).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(14).Width = 100F;
            numberCellType6.DecimalPlaces = 2;
            numberCellType6.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(15).CellType = numberCellType6;
            this.spdOrderInfo_Sheet1.Columns.Get(15).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(15).Label = "Loss Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(15).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(15).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(15).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(16).CellType = textCellType11;
            this.spdOrderInfo_Sheet1.Columns.Get(16).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(16).Label = "Unit";
            this.spdOrderInfo_Sheet1.Columns.Get(16).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(16).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(16).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(17).CellType = textCellType12;
            this.spdOrderInfo_Sheet1.Columns.Get(17).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(17).Label = "Shop Code";
            this.spdOrderInfo_Sheet1.Columns.Get(17).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(17).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(17).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(18).CellType = textCellType13;
            this.spdOrderInfo_Sheet1.Columns.Get(18).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(18).Label = "Line ID";
            this.spdOrderInfo_Sheet1.Columns.Get(18).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(18).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(18).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(19).CellType = textCellType14;
            this.spdOrderInfo_Sheet1.Columns.Get(19).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(19).Label = "Lot Type";
            this.spdOrderInfo_Sheet1.Columns.Get(19).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(19).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(19).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(20).CellType = textCellType15;
            this.spdOrderInfo_Sheet1.Columns.Get(20).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(20).Label = "Ord Date";
            this.spdOrderInfo_Sheet1.Columns.Get(20).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(20).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(20).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(21).CellType = textCellType16;
            this.spdOrderInfo_Sheet1.Columns.Get(21).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(21).Label = "Plan Date";
            this.spdOrderInfo_Sheet1.Columns.Get(21).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(21).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(21).Width = 100F;
            numberCellType7.DecimalPlaces = 0;
            this.spdOrderInfo_Sheet1.Columns.Get(22).CellType = numberCellType7;
            this.spdOrderInfo_Sheet1.Columns.Get(22).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(22).Label = "Plan Priority";
            this.spdOrderInfo_Sheet1.Columns.Get(22).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(22).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(22).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(23).CellType = textCellType17;
            this.spdOrderInfo_Sheet1.Columns.Get(23).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(23).Label = "Ord Reg Date";
            this.spdOrderInfo_Sheet1.Columns.Get(23).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(23).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(23).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(24).CellType = textCellType18;
            this.spdOrderInfo_Sheet1.Columns.Get(24).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(24).Label = "Org Plan Date";
            this.spdOrderInfo_Sheet1.Columns.Get(24).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(24).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(24).Width = 100F;
            numberCellType8.DecimalPlaces = 2;
            numberCellType8.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(25).CellType = numberCellType8;
            this.spdOrderInfo_Sheet1.Columns.Get(25).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(25).Label = "Org Ord Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(25).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(25).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(25).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(26).CellType = textCellType19;
            this.spdOrderInfo_Sheet1.Columns.Get(26).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(26).Label = "Plan Start Time";
            this.spdOrderInfo_Sheet1.Columns.Get(26).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(26).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(26).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(27).CellType = textCellType20;
            this.spdOrderInfo_Sheet1.Columns.Get(27).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(27).Label = "Plan End Time";
            this.spdOrderInfo_Sheet1.Columns.Get(27).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(27).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(27).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(28).CellType = textCellType21;
            this.spdOrderInfo_Sheet1.Columns.Get(28).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(28).Label = "Ord Start Time";
            this.spdOrderInfo_Sheet1.Columns.Get(28).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(28).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(28).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(29).CellType = textCellType22;
            this.spdOrderInfo_Sheet1.Columns.Get(29).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(29).Label = "Ord End Time";
            this.spdOrderInfo_Sheet1.Columns.Get(29).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(29).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(29).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(30).CellType = textCellType23;
            this.spdOrderInfo_Sheet1.Columns.Get(30).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(30).Label = "Close Time";
            this.spdOrderInfo_Sheet1.Columns.Get(30).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(30).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(30).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(31).CellType = textCellType24;
            this.spdOrderInfo_Sheet1.Columns.Get(31).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(31).Label = "Label Code";
            this.spdOrderInfo_Sheet1.Columns.Get(31).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(31).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(31).Width = 100F;
            numberCellType9.DecimalPlaces = 2;
            numberCellType9.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(32).CellType = numberCellType9;
            this.spdOrderInfo_Sheet1.Columns.Get(32).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(32).Label = "Pack Qty";
            this.spdOrderInfo_Sheet1.Columns.Get(32).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(32).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(32).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(33).CellType = textCellType25;
            this.spdOrderInfo_Sheet1.Columns.Get(33).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(33).Label = "Cust ID";
            this.spdOrderInfo_Sheet1.Columns.Get(33).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(33).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(33).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(34).CellType = textCellType26;
            this.spdOrderInfo_Sheet1.Columns.Get(34).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(34).Label = "Erp So No";
            this.spdOrderInfo_Sheet1.Columns.Get(34).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(34).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(34).Width = 100F;
            numberCellType10.DecimalPlaces = 0;
            this.spdOrderInfo_Sheet1.Columns.Get(35).CellType = numberCellType10;
            this.spdOrderInfo_Sheet1.Columns.Get(35).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(35).Label = "Erp So Seq";
            this.spdOrderInfo_Sheet1.Columns.Get(35).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(35).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(35).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(36).CellType = textCellType27;
            this.spdOrderInfo_Sheet1.Columns.Get(36).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(36).Label = "Order Status";
            this.spdOrderInfo_Sheet1.Columns.Get(36).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(36).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(36).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(37).CellType = textCellType28;
            this.spdOrderInfo_Sheet1.Columns.Get(37).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(37).Label = "Comment1";
            this.spdOrderInfo_Sheet1.Columns.Get(37).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(37).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(37).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(38).CellType = textCellType29;
            this.spdOrderInfo_Sheet1.Columns.Get(38).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(38).Label = "Comment2";
            this.spdOrderInfo_Sheet1.Columns.Get(38).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(38).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(38).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(39).CellType = textCellType30;
            this.spdOrderInfo_Sheet1.Columns.Get(39).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(39).Label = "Comment3";
            this.spdOrderInfo_Sheet1.Columns.Get(39).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(39).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(39).Width = 100F;
            numberCellType11.DecimalPlaces = 2;
            numberCellType11.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(40).CellType = numberCellType11;
            this.spdOrderInfo_Sheet1.Columns.Get(40).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(40).Label = "Ord Qty 1";
            this.spdOrderInfo_Sheet1.Columns.Get(40).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(40).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(40).Width = 100F;
            numberCellType12.DecimalPlaces = 2;
            numberCellType12.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(41).CellType = numberCellType12;
            this.spdOrderInfo_Sheet1.Columns.Get(41).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(41).Label = "Ord Qty 2";
            this.spdOrderInfo_Sheet1.Columns.Get(41).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(41).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(41).Width = 100F;
            numberCellType13.DecimalPlaces = 2;
            numberCellType13.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(42).CellType = numberCellType13;
            this.spdOrderInfo_Sheet1.Columns.Get(42).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(42).Label = "Ord Qty 3";
            this.spdOrderInfo_Sheet1.Columns.Get(42).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(42).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(42).Width = 100F;
            numberCellType14.DecimalPlaces = 2;
            numberCellType14.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(43).CellType = numberCellType14;
            this.spdOrderInfo_Sheet1.Columns.Get(43).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(43).Label = "Ord Qty 4";
            this.spdOrderInfo_Sheet1.Columns.Get(43).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(43).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(43).Width = 100F;
            numberCellType15.DecimalPlaces = 2;
            numberCellType15.ShowSeparator = true;
            this.spdOrderInfo_Sheet1.Columns.Get(44).CellType = numberCellType15;
            this.spdOrderInfo_Sheet1.Columns.Get(44).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Right;
            this.spdOrderInfo_Sheet1.Columns.Get(44).Label = "Ord Qty 5";
            this.spdOrderInfo_Sheet1.Columns.Get(44).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(44).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(44).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(45).CellType = textCellType31;
            this.spdOrderInfo_Sheet1.Columns.Get(45).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(45).Label = "Ord Cmf 1";
            this.spdOrderInfo_Sheet1.Columns.Get(45).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(45).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(45).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(46).CellType = textCellType32;
            this.spdOrderInfo_Sheet1.Columns.Get(46).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(46).Label = "Ord Cmf 2";
            this.spdOrderInfo_Sheet1.Columns.Get(46).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(46).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(46).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(47).CellType = textCellType33;
            this.spdOrderInfo_Sheet1.Columns.Get(47).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(47).Label = "Ord Cmf 3";
            this.spdOrderInfo_Sheet1.Columns.Get(47).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(47).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(47).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(48).CellType = textCellType34;
            this.spdOrderInfo_Sheet1.Columns.Get(48).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(48).Label = "Ord Cmf 4";
            this.spdOrderInfo_Sheet1.Columns.Get(48).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(48).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(48).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(49).CellType = textCellType35;
            this.spdOrderInfo_Sheet1.Columns.Get(49).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(49).Label = "Ord Cmf 5";
            this.spdOrderInfo_Sheet1.Columns.Get(49).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(49).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(49).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(50).CellType = textCellType36;
            this.spdOrderInfo_Sheet1.Columns.Get(50).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(50).Label = "Ord Cmf 6";
            this.spdOrderInfo_Sheet1.Columns.Get(50).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(50).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(50).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(51).CellType = textCellType37;
            this.spdOrderInfo_Sheet1.Columns.Get(51).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(51).Label = "Ord Cmf 7";
            this.spdOrderInfo_Sheet1.Columns.Get(51).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(51).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(51).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(52).CellType = textCellType38;
            this.spdOrderInfo_Sheet1.Columns.Get(52).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(52).Label = "Ord Cmf 8";
            this.spdOrderInfo_Sheet1.Columns.Get(52).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(52).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(52).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(53).CellType = textCellType39;
            this.spdOrderInfo_Sheet1.Columns.Get(53).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(53).Label = "Ord Cmf 9";
            this.spdOrderInfo_Sheet1.Columns.Get(53).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(53).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(53).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(54).CellType = textCellType40;
            this.spdOrderInfo_Sheet1.Columns.Get(54).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(54).Label = "Ord Cmf 10";
            this.spdOrderInfo_Sheet1.Columns.Get(54).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(54).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(54).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(55).CellType = textCellType41;
            this.spdOrderInfo_Sheet1.Columns.Get(55).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(55).Label = "Create User ID";
            this.spdOrderInfo_Sheet1.Columns.Get(55).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(55).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(55).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(56).CellType = textCellType42;
            this.spdOrderInfo_Sheet1.Columns.Get(56).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(56).Label = "Create Time";
            this.spdOrderInfo_Sheet1.Columns.Get(56).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(56).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(56).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(57).CellType = textCellType43;
            this.spdOrderInfo_Sheet1.Columns.Get(57).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(57).Label = "Update User ID";
            this.spdOrderInfo_Sheet1.Columns.Get(57).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(57).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(57).Width = 100F;
            this.spdOrderInfo_Sheet1.Columns.Get(58).CellType = textCellType44;
            this.spdOrderInfo_Sheet1.Columns.Get(58).HorizontalAlignment = FarPoint.Win.Spread.CellHorizontalAlignment.Left;
            this.spdOrderInfo_Sheet1.Columns.Get(58).Label = "Update Time";
            this.spdOrderInfo_Sheet1.Columns.Get(58).Locked = true;
            this.spdOrderInfo_Sheet1.Columns.Get(58).VerticalAlignment = FarPoint.Win.Spread.CellVerticalAlignment.Center;
            this.spdOrderInfo_Sheet1.Columns.Get(58).Width = 100F;
            this.spdOrderInfo_Sheet1.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdOrderInfo_Sheet1.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.spdOrderInfo_Sheet1.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.DefaultStyle.Parent = "DataAreaDefault";
            this.spdOrderInfo_Sheet1.GrayAreaBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.spdOrderInfo_Sheet1.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.OperationMode = FarPoint.Win.Spread.OperationMode.RowMode;
            this.spdOrderInfo_Sheet1.PrintInfo.ShowColor = true;
            this.spdOrderInfo_Sheet1.PrintInfo.UseSmartPrint = true;
            this.spdOrderInfo_Sheet1.RowHeader.Columns.Default.Resizable = false;
            this.spdOrderInfo_Sheet1.RowHeader.Columns.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.Parent = "HeaderDefault";
            this.spdOrderInfo_Sheet1.RowHeader.DefaultStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.RowHeader.HorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.RowHeader.Rows.Default.Resizable = true;
            this.spdOrderInfo_Sheet1.RowHeader.Rows.Default.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.RowHeader.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.RowHeader.Visible = false;
            this.spdOrderInfo_Sheet1.Rows.Default.Height = 50F;
            this.spdOrderInfo_Sheet1.Rows.Default.Resizable = true;
            this.spdOrderInfo_Sheet1.SelectionStyle = FarPoint.Win.Spread.SelectionStyles.SelectionColors;
            this.spdOrderInfo_Sheet1.SheetCornerHorizontalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.SheetCornerStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(114)))), ((int)(((byte)(114)))), ((int)(((byte)(114)))));
            this.spdOrderInfo_Sheet1.SheetCornerStyle.Font = new System.Drawing.Font("맑은 고딕", 12F, System.Drawing.FontStyle.Bold);
            this.spdOrderInfo_Sheet1.SheetCornerStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.spdOrderInfo_Sheet1.SheetCornerStyle.NoteIndicatorColor = System.Drawing.Color.Red;
            this.spdOrderInfo_Sheet1.SheetCornerStyle.Parent = "HeaderDefault";
            this.spdOrderInfo_Sheet1.SheetCornerStyle.VisualStyles = FarPoint.Win.VisualStyles.Off;
            this.spdOrderInfo_Sheet1.SheetCornerVerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.VerticalGridLine = new FarPoint.Win.Spread.GridLine(FarPoint.Win.Spread.GridLineType.Flat, System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), System.Drawing.Color.FromArgb(((int)(((byte)(152)))), ((int)(((byte)(152)))), ((int)(((byte)(152))))), 1);
            this.spdOrderInfo_Sheet1.ReferenceStyle = FarPoint.Win.Spread.Model.ReferenceStyle.A1;
            // 
            // BOIOrderInfo
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.soiGroupBox1);
            this.Name = "BOIOrderInfo";
            this.Size = new System.Drawing.Size(800, 145);
            this.Load += new System.EventHandler(this.BOIOrderInfo_Load);
            ((System.ComponentModel.ISupportInitialize)(this.soiGroupBox1)).EndInit();
            this.soiGroupBox1.ResumeLayout(false);
            this.soiTableLayoutPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.spdOrderInfo)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.spdOrderInfo_Sheet1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private SOI.OIFrx.SOIControls.SOIGroupBox soiGroupBox1;
        private SOI.OIFrx.SOIControls.SOITableLayoutPanel soiTableLayoutPanel1;
        private SOI.OIFrx.SOIControls.SOIButton btnViewWorkOrder;
        private FarPoint.Win.Spread.SheetView spdOrderInfo_Sheet1;
        internal OIFrx.BOIControls.BOISpread spdOrderInfo;
    }
}
