//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.3053
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// 이 소스 코드는 xsd, 버전=2.0.50727.42에서 자동 생성되었습니다.
// 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Reference
{
    private string languageField;

    private string nameField;

    private double versionField;

    private List<ReferenceData> listField;

    private Dictionary<string, string> dataDic;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Data", IsNullable = false)]
    public List<ReferenceData> List
    {
        get
        {
            return this.listField;
        }
        set
        {
            this.listField = value;
        }
    }

    [XmlIgnore]
    public string Language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    public Reference()
    {
        List = new List<ReferenceData>();
        languageField = "English";
        dataDic = new Dictionary<string, string>();
        dataDic = null;
    }

    public string GetValue(string key)
    {
        if (dataDic == null)
            MakeDic();

        if (dataDic.ContainsKey(key))
            return dataDic[key];

        return "";
    }

    public void MakeDic()
    {
        if (List.Count != 0)
        {
            if(dataDic ==null)
                dataDic = new Dictionary<string, string>();
            else
                dataDic.Clear();

            for (int i = 0; i < List.Count; i++)
            {
                if (dataDic.ContainsKey(List[i].Key) == false)
                {
                    switch(this.Language)
                    {
                        case "English":
                            dataDic.Add(List[i].Key, List[i].Desc1);
                            break;
                        case "2nd Language":
                            dataDic.Add(List[i].Key, List[i].Desc2);
                            break;
                        case "3rd Lanugage":
                            dataDic.Add(List[i].Key, List[i].Desc3);
                            break;
                        default:
                            dataDic.Add(List[i].Key, List[i].Desc1);
                            break;
                    }
                }
            }
        }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ReferenceData
{
    private string desc1Field;

    private string desc2Field;

    private string desc3Field;

    private string keyField;

    /// <remarks/>
    public string Desc1
    {
        get
        {
            return this.desc1Field;
        }
        set
        {
            this.desc1Field = value;
        }
    }

    /// <remarks/>
    public string Desc2
    {
        get
        {
            return this.desc2Field;
        }
        set
        {
            this.desc2Field = value;
        }
    }

    /// <remarks/>
    public string Desc3
    {
        get
        {
            return this.desc3Field;
        }
        set
        {
            this.desc3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Key
    {
        get
        {
            return this.keyField;
        }
        set
        {
            this.keyField = value;
        }
    }
}


