//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:2.0.50727.3053
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections.Generic;

// 
// 이 소스 코드는 xsd, 버전=2.0.50727.42에서 자동 생성되었습니다.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class ExchageModule
{   

    private string nameField;

    private List<Service> servicesField;

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public List<Service> Services
    {
        get
        {
            return this.servicesField;
        }
        set
        {
            this.servicesField = value;
        }
    }

    public ExchageModule()
    {
        servicesField = new List<Service>();
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Service
{

    private string desc1Field;

    private string desc2Field;

    private string desc3Field;

    private char securityCheckRequiredField;

    private char categoryField;

    private string modeField;

    private List<Member> inMembersField;

    private List<Member> outMembersField;

    private string nameField;

    private string createUserIdField;

    private string createTimeField;

    private string updateUserIdField;

    private string updateTimeField;

    private string sharedLibName;

    /// <remarks/>
    public string SharedLibName
    {
        get
        {
            return this.sharedLibName;
        }
        set
        {
            this.sharedLibName = value;
        }
    }

    /// <remarks/>
    public string Desc1
    {
        get
        {
            return this.desc1Field;
        }
        set
        {
            this.desc1Field = value;
        }
    }

    /// <remarks/>
    public string Desc2
    {
        get
        {
            return this.desc2Field;
        }
        set
        {
            this.desc2Field = value;
        }
    }

    /// <remarks/>
    public string Desc3
    {
        get
        {
            return this.desc3Field;
        }
        set
        {
            this.desc3Field = value;
        }
    }

    [XmlIgnore]
    public char SecurityCheckRequired
    {
        get
        {
            return this.securityCheckRequiredField;
        }
        set
        {
            this.securityCheckRequiredField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("SecurityCheckRequired", typeof(string))]
    public string _SecurityCheckRequired
    {
        get
        {
            if (this.securityCheckRequiredField == '\0' || this.securityCheckRequiredField == ' ')
            {
                return "";
            }

            return this.securityCheckRequiredField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.securityCheckRequiredField = value[0];
            }
            else
            {
                this.securityCheckRequiredField = ' ';
            }
        }
    }

    /// <remarks/>
    [XmlIgnore]
    public char Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("Category", typeof(string))]
    public string _Category
    {
        get
        {
            if (this.categoryField == '\0' || this.categoryField == ' ')
            {
                return "";
            }

            return this.categoryField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.categoryField = value[0];
            }
            else
            {
                this.categoryField = ' ';
            }
        }
    }

    /// <remarks/>
    public string Mode
    {
        get
        {
            return this.modeField;
        }
        set
        {
            this.modeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public List<Member> InMembers
    {
        get
        {
            return this.inMembersField;
        }
        set
        {
            this.inMembersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public List<Member> OutMembers
    {
        get
        {
            return this.outMembersField;
        }
        set
        {
            this.outMembersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    public string CreateUserId
    {
        get
        {
            return this.createUserIdField;
        }
        set
        {
            this.createUserIdField = value;
        }
    }

    public string CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }

    public string UpdateUserId
    {
        get
        {
            return this.updateUserIdField;
        }
        set
        {
            this.updateUserIdField = value;
        }
    }

    public string UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }

    public Service()
    {
        inMembersField = new List<Member>();
        outMembersField = new List<Member>();
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Member
{
    private string nameField;

    private string promptField;

    private string typeField;
    
    private string arrayTypeField;

    private int sizeField;

    private char directionField;

    private int depthField;

    private int sequenceField;

    private string desc1Field;

    private string desc2Field;

    private string desc3Field;

    private char requireFlagField;

    private string parentPathField;

    private char overrideFlagField;

    private char useRangeFlagField;

    private double rangeMinField;

    private double rangeMaxField;

    private string createUserIdField;

    private string createTimeField;

    private string updateUserIdField;

    private string updateTimeField;

    private string memberPath;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public string Prompt
    {
        get
        {
            return this.promptField;
        }
        set
        {
            this.promptField = value;
        }
    }

    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string ArrayType
    {
        get
        {
            return this.arrayTypeField;
        }
        set
        {
            this.arrayTypeField = value;
        }
    }

    /// <remarks/>
    public int Size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [XmlIgnore]
    public char Direction
    {
        get
        {
            return this.directionField;
        }
        set
        {
            this.directionField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("Direction", typeof(string))]
    public string _Direction
    {
        get
        {
            if (this.directionField == '\0' || this.directionField == ' ')
            {
                return "";
            }

            return this.directionField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.directionField = value[0];
            }
            else
            {
                this.directionField = ' ';
            }
        }
    }

    /// <remarks/>
    public int Depth
    {
        get
        {
            return this.depthField;
        }
        set
        {
            this.depthField = value;
        }
    }

    /// <remarks/>
    public int Sequence
    {
        get
        {
            return this.sequenceField;
        }
        set
        {
            this.sequenceField = value;
        }
    }

    /// <remarks/>
    public string Desc1
    {
        get
        {
            return this.desc1Field;
        }
        set
        {
            this.desc1Field = value;
        }
    }

    /// <remarks/>
    public string Desc2
    {
        get
        {
            return this.desc2Field;
        }
        set
        {
            this.desc2Field = value;
        }
    }
    
    /// <remarks/>
    public string Desc3
    {
        get
        {
            return this.desc3Field;
        }
        set
        {
            this.desc3Field = value;
        }
    }

    /// <remarks/>
    [XmlIgnore]
    public char RequireFlag
    {
        get
        {
            return this.requireFlagField;
        }
        set
        {
            this.requireFlagField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("RequireFlag", typeof(string))]
    public string _RequireFlag
    {
        get
        {
            if (this.requireFlagField == '\0' || this.requireFlagField == ' ')
            {
                return "";
            }

            return this.requireFlagField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.requireFlagField = value[0];
            }
            else
            {
                this.requireFlagField = ' ';
            }
        }
    }

    /// <remarks/>
    public string ParentPath
    {
        get
        {
            return this.parentPathField;
        }
        set
        {
            this.parentPathField = value;
        }
    }

    /// <remarks/>
    [XmlIgnore]
    public char OverrideFlag
    {
        get
        {
            return this.overrideFlagField;
        }
        set
        {
            this.overrideFlagField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("OverrideFlag", typeof(string))]
    public string _OverrideFlag
    {
        get
        {
            if (this.overrideFlagField == '\0' || this.overrideFlagField == ' ')
            {
                return "";
            }

            return this.overrideFlagField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.overrideFlagField = value[0];
            }
            else
            {
                this.overrideFlagField = ' ';
            }
        }
    }

    /// <remarks/>
    [XmlIgnore]
    public char UseRangeFlag
    {
        get
        {
            return this.useRangeFlagField;
        }
        set
        {
            this.useRangeFlagField = value;
        }
    }

    //[System.Xml.Serialization.XmlElementAttribute("UseRangeFlag", typeof(string))]
    public string _UseRangeFlag
    {
        get
        {
            if (this.useRangeFlagField == '\0' || this.useRangeFlagField == ' ')
            {
                return "";
            }

            return this.useRangeFlagField.ToString().Trim();
        }
        set
        {
            if (value.Trim().Length != 0)
            {
                this.useRangeFlagField = value[0];
            }
            else
            {
                this.useRangeFlagField = ' ';
            }
        }
    }

    /// <remarks/>
    public double RangeMin
    {
        get
        {
            return this.rangeMinField;
        }
        set
        {
            this.rangeMinField = value;
        }
    }

    /// <remarks/>
    public double RangeMax
    {
        get
        {
            return this.rangeMaxField;
        }
        set
        {
            this.rangeMaxField = value;
        }
    }

    public string CreateUserId
    {
        get
        {
            return this.createUserIdField;
        }
        set
        {
            this.createUserIdField = value;
        }
    }

    public string CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }

    public string UpdateUserId
    {
        get
        {
            return this.updateUserIdField;
        }
        set
        {
            this.updateUserIdField = value;
        }
    }

    public string UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }

    public string MemberPath
    {
        get
        {
            return this.memberPath;
        }
        set
        {
            this.memberPath = value;
        }
    }


}
